	.align 2
DirectSoundWaveData_sc88pro_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88pro_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88pro_organ2::
	.incbin "sound/direct_sound_samples/sc88pro_organ2.bin"

	.align 2
DirectSoundWaveData_sc88pro_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fretless_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_slap_bass::
	.incbin "sound/direct_sound_samples/sc88pro_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_synth_bass::
	.incbin "sound/direct_sound_samples/sc88pro_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani::
	.incbin "sound/direct_sound_samples/sc88pro_timpani.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_guitar_separates_power_chord::
	.incbin "sound/direct_sound_samples/unused_guitar_separates_power_chord.bin"

	.align 2
DirectSoundWaveData_unused_sc88pro_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88pro_unison_slap.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_ohtsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_ohtsuzumi.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_hyoushigi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_hyoushigi.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_kick::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_kick.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_snare::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_tr909_hand_clap::
	.incbin "sound/direct_sound_samples/sc88pro_tr909_hand_clap.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_snare::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_snare.bin"

	.align 2
DirectSoundWaveData_unused_sc55_tom::
	.incbin "sound/direct_sound_samples/unused_sc55_tom.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_open_hihat::
	.incbin "sound/direct_sound_samples/unknown_open_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_bell::
	.incbin "sound/direct_sound_samples/unknown_bell.bin"

	.align 2
DirectSoundWaveData_sc88pro_tambourine::
	.incbin "sound/direct_sound_samples/sc88pro_tambourine.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/trinity_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_mute_high_conga::
	.incbin "sound/direct_sound_samples/sc88pro_mute_high_conga.bin"

	.align 2
DirectSoundWaveData_sc88pro_open_low_conga::
	.incbin "sound/direct_sound_samples/sc88pro_open_low_conga.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.align 2
DirectSoundWaveData_sd90_cowbell::
	.incbin "sound/direct_sound_samples/sd90_cowbell.bin"

	.align 2
DirectSoundWaveData_unused_heart_of_asia_indian_drum::
	.incbin "sound/direct_sound_samples/unused_heart_of_asia_indian_drum.bin"

	.align 2
DirectSoundWaveData_sd90_open_triangle::
	.incbin "sound/direct_sound_samples/sd90_open_triangle.bin"

	.align 2
DirectSoundWaveData_sc88pro_jingle_bell::
	.incbin "sound/direct_sound_samples/sc88pro_jingle_bell.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_atarigane::
	.incbin "sound/direct_sound_samples/ethnic_flavours_atarigane.bin"

	.align 2
DirectSoundWaveData_sc88pro_taiko::
	.incbin "sound/direct_sound_samples/sc88pro_taiko.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_kotsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_kotsuzumi.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_48::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_48.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_60::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_72::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_84::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_39:: @N.B.: These tuba samples are actually sampled at 36 and 48, then pitched up
	.incbin "sound/direct_sound_samples/sc88pro_tuba_39.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_51::
	.incbin "sound/direct_sound_samples/sc88pro_tuba_51.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_flute::
	.incbin "sound/direct_sound_samples/sc88pro_flute.bin"

	.align 2
DirectSoundWaveData_sc88pro_fingered_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fingered_bass.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/unknown_koto_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/sd90_classical_shakuhachi.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/unknown_koto_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/heart_of_asia_gamelan.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_low::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_low.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_high::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_high.bin"

	.align 2
DirectSoundWaveData_unknown_female_voice::
	.incbin "sound/direct_sound_samples/unknown_female_voice.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_male_voice.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88pro_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_square_wave::
	.incbin "sound/direct_sound_samples/sc88pro_square_wave.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_unknown_1::
	.incbin "sound/direct_sound_samples/unknown_01.bin"

	.align 2
DirectSoundWaveData_sc88pro_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88pro_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_unknown_2::
	.incbin "sound/direct_sound_samples/unknown_02.bin"

	.align 2
DirectSoundWaveData_unknown_3::
	.incbin "sound/direct_sound_samples/unknown_03.bin"

	.align 2
DirectSoundWaveData_unknown_4::
	.incbin "sound/direct_sound_samples/unknown_04.bin"

	.align 2
DirectSoundWaveData_sc88pro_wind::
	.incbin "sound/direct_sound_samples/sc88pro_wind.bin"

	.align 2
DirectSoundWaveData_sc88pro_bubbles::
	.incbin "sound/direct_sound_samples/sc88pro_bubbles.bin"

	.align 2
DirectSoundWaveData_unknown_5::
	.incbin "sound/direct_sound_samples/unknown_05.bin"

	.align 2
DirectSoundWaveData_unknown_6::
	.incbin "sound/direct_sound_samples/unknown_06.bin"

	.align 2
DirectSoundWaveData_trinity_30303_mega_bass::
	.incbin "sound/direct_sound_samples/trinity_30303_mega_bass.bin"

	.align 2
DirectSoundWaveData_unknown_7::
	.incbin "sound/direct_sound_samples/unknown_07.bin"

	.align 2
DirectSoundWaveData_unknown_8::
	.incbin "sound/direct_sound_samples/unknown_08.bin"

	.align 2
DirectSoundWaveData_sc88pro_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88pro_tubular_bell.bin"

	.align 2
DirectSoundWaveData_unknown_9::
	.incbin "sound/direct_sound_samples/unknown_09.bin"

	.align 2
DirectSoundWaveData_trinity_big_boned::
	.incbin "sound/direct_sound_samples/trinity_big_boned.bin"

	.align 2
DirectSoundWaveData_sc88pro_harp::
	.incbin "sound/direct_sound_samples/sc88pro_harp.bin"

	.align 2
DirectSoundWaveData_sc88pro_xylophone::
	.incbin "sound/direct_sound_samples/sc88pro_xylophone.bin"

	.align 2
DirectSoundWaveData_unknown_10::
	.incbin "sound/direct_sound_samples/unknown_10.bin"

	.align 2
DirectSoundWaveData_unknown_11::
	.incbin "sound/direct_sound_samples/unknown_11.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion::
	.incbin "sound/direct_sound_samples/sc88pro_accordion.bin"

	.align 2
DirectSoundWaveData_unknown_12::
	.incbin "sound/direct_sound_samples/unknown_12.bin"

	.align 2
DirectSoundWaveData_unknown_13::
	.incbin "sound/direct_sound_samples/unknown_13.bin"

	.align 2
DirectSoundWaveData_unknown_14::
	.incbin "sound/direct_sound_samples/unknown_14.bin"

	.align 2
DirectSoundWaveData_unknown_15::
	.incbin "sound/direct_sound_samples/unknown_15.bin"

	.align 2
DirectSoundWaveData_unknown_16::
	.incbin "sound/direct_sound_samples/unknown_16.bin"

	.align 2
DirectSoundWaveData_unknown_17::
	.incbin "sound/direct_sound_samples/unknown_17.bin"

.if P_CRIES_ENABLED == TRUE
.if P_FAMILY_ARGOMON_F == TRUE
	.align 2
Cry_Argomon_f::
	.incbin "sound/direct_sound_samples/cries/argomon_f.bin"

	.align 2
Cry_Bombmon::
	.incbin "sound/direct_sound_samples/cries/bombmon.bin"

	.align 2
Cry_Bommon::
	.incbin "sound/direct_sound_samples/cries/bommon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_BommonMega::
	.incbin "sound/direct_sound_samples/cries/bommon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_ARGOMON_F

.if P_FAMILY_BOTAMON == TRUE
	.align 2
Cry_Botamon::
	.incbin "sound/direct_sound_samples/cries/botamon.bin"

	.align 2
Cry_Chibickmon::
	.incbin "sound/direct_sound_samples/cries/chibickmon.bin"

	.align 2
Cry_Chibomon::
	.incbin "sound/direct_sound_samples/cries/chibomon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_ChibomonMegaX::
	.incbin "sound/direct_sound_samples/cries/chibomon_mega_x.bin"

	.align 2
Cry_ChibomonMegaY::
	.incbin "sound/direct_sound_samples/cries/chibomon_mega_y.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_BOTAMON

.if P_FAMILY_CONOMON == TRUE
	.align 2
Cry_Conomon::
	.incbin "sound/direct_sound_samples/cries/conomon.bin"

	.align 2
Cry_Cotsucomon::
	.incbin "sound/direct_sound_samples/cries/cotsucomon.bin"

	.align 2
Cry_Curimon::
	.incbin "sound/direct_sound_samples/cries/curimon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_CurimonMega::
	.incbin "sound/direct_sound_samples/cries/curimon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_CONOMON

.if P_FAMILY_DATIRIMON == TRUE
	.align 2
Cry_Datirimon::
	.incbin "sound/direct_sound_samples/cries/datirimon.bin"

	.align 2
Cry_Dodomon::
	.incbin "sound/direct_sound_samples/cries/dodomon.bin"

	.align 2
Cry_Dokimon::
	.incbin "sound/direct_sound_samples/cries/dokimon.bin"
.endif @ P_FAMILY_DATIRIMON

.if P_FAMILY_FUFUMON == TRUE
	.align 2
Cry_Fufumon::
	.incbin "sound/direct_sound_samples/cries/fufumon.bin"

	.align 2
Cry_Jyarimon::
	.incbin "sound/direct_sound_samples/cries/jyarimon.bin"

	.align 2
Cry_Keemon::
	.incbin "sound/direct_sound_samples/cries/keemon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_KeemonMega::
	.incbin "sound/direct_sound_samples/cries/keemon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_FUFUMON

.if P_FAMILY_KETOMON == TRUE
	.align 2
Cry_Ketomon::
	.incbin "sound/direct_sound_samples/cries/ketomon.bin"

	.align 2
Cry_Kuramon::
	.incbin "sound/direct_sound_samples/cries/kuramon.bin"

	.align 2
Cry_Leafmon::
	.incbin "sound/direct_sound_samples/cries/leafmon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_LeafmonMega::
	.incbin "sound/direct_sound_samples/cries/leafmon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_KETOMON

.if P_FAMILY_CHOROMON == TRUE
	.align 2
Cry_Choromon::
	.incbin "sound/direct_sound_samples/cries/choromon.bin"

	.align 2
Cry_Mokumon::
	.incbin "sound/direct_sound_samples/cries/mokumon.bin"
.endif @ P_FAMILY_CHOROMON

.if P_FAMILY_NYOKIMON == TRUE
	.align 2
Cry_Nyokimon::
	.incbin "sound/direct_sound_samples/cries/nyokimon.bin"

	.align 2
Cry_Pabumon::
	.incbin "sound/direct_sound_samples/cries/pabumon.bin"
.endif @ P_FAMILY_NYOKIMON

.if P_FAMILY_PAFUMON == TRUE
	.align 2
Cry_Pafumon::
	.incbin "sound/direct_sound_samples/cries/pafumon.bin"

	.align 2
Cry_Paomon::
	.incbin "sound/direct_sound_samples/cries/paomon.bin"
.endif @ P_FAMILY_PAFUMON

.if P_FAMILY_PETITMON == TRUE
.if P_GEN_2_CROSS_EVOS == TRUE
	.align 2
Cry_Guilmon_x::
	.incbin "sound/direct_sound_samples/cries/guilmon_x.bin"
.endif @ P_GEN_2_CROSS_EVOS

	.align 2
Cry_Petitmon::
	.incbin "sound/direct_sound_samples/cries/petitmon.bin"

	.align 2
Cry_Pichimon::
	.incbin "sound/direct_sound_samples/cries/pichimon.bin"
.endif @ P_FAMILY_PETITMON

.if P_FAMILY_POPOMON == TRUE
	.align 2
Cry_Popomon::
	.incbin "sound/direct_sound_samples/cries/popomon.bin"

	.align 2
Cry_Poyomon::
	.incbin "sound/direct_sound_samples/cries/poyomon.bin"
.endif @ P_FAMILY_POPOMON

.if P_FAMILY_PUNIMON == TRUE
	.align 2
Cry_Punimon::
	.incbin "sound/direct_sound_samples/cries/punimon.bin"

	.align 2
Cry_Pupumon::
	.incbin "sound/direct_sound_samples/cries/pupumon.bin"

	.align 2
Cry_Pururumon::
	.incbin "sound/direct_sound_samples/cries/pururumon.bin"

	.align 2
Cry_Pusumon::
	.incbin "sound/direct_sound_samples/cries/pusumon.bin"

	.align 2
Cry_Puttimon::
	.incbin "sound/direct_sound_samples/cries/puttimon.bin"

	.align 2
Cry_Puwamon::
	.incbin "sound/direct_sound_samples/cries/puwamon.bin"
.endif @ P_FAMILY_PUNIMON

.if P_FAMILY_PUYOMON == TRUE
.if P_GEN_2_CROSS_EVOS == TRUE
	.align 2
Cry_Gumdramon::
	.incbin "sound/direct_sound_samples/cries/gumdramon.bin"
.endif @ P_GEN_2_CROSS_EVOS

	.align 2
Cry_Puyomon::
	.incbin "sound/direct_sound_samples/cries/puyomon.bin"

	.align 2
Cry_Pyonmon::
	.incbin "sound/direct_sound_samples/cries/pyonmon.bin"
.endif @ P_FAMILY_PUYOMON

.if P_FAMILY_RELEMON == TRUE
	.align 2
Cry_Relemon::
	.incbin "sound/direct_sound_samples/cries/relemon.bin"

	.align 2
Cry_Sakumon::
	.incbin "sound/direct_sound_samples/cries/sakumon.bin"
.endif @ P_FAMILY_RELEMON

.if P_FAMILY_SANDMON == TRUE
.if P_GEN_2_CROSS_EVOS == TRUE
	.align 2
Cry_Hackmon::
	.incbin "sound/direct_sound_samples/cries/hackmon.bin"
.endif @ P_GEN_2_CROSS_EVOS

	.align 2
Cry_Sandmon::
	.incbin "sound/direct_sound_samples/cries/sandmon.bin"

	.align 2
Cry_Tsubumon::
	.incbin "sound/direct_sound_samples/cries/tsubumon.bin"
.endif @ P_FAMILY_SANDMON

.if P_FAMILY_ICEBOTAMON == TRUE
	.align 2
Cry_Icebotamon::
	.incbin "sound/direct_sound_samples/cries/icebotamon.bin"

	.align 2
Cry_Yuramon::
	.incbin "sound/direct_sound_samples/cries/yuramon.bin"

.if P_GEN_2_CROSS_EVOS == TRUE
	.align 2
Cry_Gotsumon::
	.incbin "sound/direct_sound_samples/cries/gotsumon.bin"
.endif @ P_GEN_2_CROSS_EVOS
.endif @ P_FAMILY_ICEBOTAMON

.if P_FAMILY_ZERIMON == TRUE
	.align 2
Cry_Zerimon::
	.incbin "sound/direct_sound_samples/cries/zerimon.bin"

	.align 2
Cry_Zurumon::
	.incbin "sound/direct_sound_samples/cries/zurumon.bin"

	.align 2
Cry_Arcadiamon_it::
	.incbin "sound/direct_sound_samples/cries/arcadiamon_it.bin"

.if P_GEN_2_CROSS_EVOS == TRUE
	.align 2
Cry_Impmon_x::
	.incbin "sound/direct_sound_samples/cries/impmon_x.bin"
.endif @ P_GEN_2_CROSS_EVOS
.endif @ P_FAMILY_ZERIMON

.if P_FAMILY_ARGOMON_IT == TRUE
	.align 2
Cry_Argomon_it::
	.incbin "sound/direct_sound_samples/cries/argomon_it.bin"

	.align 2
Cry_Babydmon::
	.incbin "sound/direct_sound_samples/cries/babydmon.bin"
.endif @ P_FAMILY_ARGOMON_IT

.if P_FAMILY_BIBIMON == TRUE
	.align 2
Cry_Bibimon::
	.incbin "sound/direct_sound_samples/cries/bibimon.bin"

	.align 2
Cry_Bosamon::
	.incbin "sound/direct_sound_samples/cries/bosamon.bin"
.endif @ P_FAMILY_BIBIMON

.if P_FAMILY_BUDMON == TRUE
	.align 2
Cry_Budmon::
	.incbin "sound/direct_sound_samples/cries/budmon.bin"

	.align 2
Cry_Bukamon::
	.incbin "sound/direct_sound_samples/cries/bukamon.bin"
.endif @ P_FAMILY_BUDMON

.if P_FAMILY_CALUMON == TRUE
	.align 2
Cry_Calumon::
	.incbin "sound/direct_sound_samples/cries/calumon.bin"

	.align 2
Cry_Chapmon::
	.incbin "sound/direct_sound_samples/cries/chapmon.bin"

.if P_GALARIAN_FORMS == TRUE
	.align 2
Cry_Perrserker::
	.incbin "sound/direct_sound_samples/cries/perrserker.bin"

.endif @ P_GALARIAN_FORMS
.endif @ P_FAMILY_CALUMON

.if P_FAMILY_CHICCHIMON == TRUE
	.align 2
Cry_Chicchimon::
	.incbin "sound/direct_sound_samples/cries/chicchimon.bin"

	.align 2
Cry_Demmeramon::
	.incbin "sound/direct_sound_samples/cries/demmeramon.bin"
.endif @ P_FAMILY_CHICCHIMON

.if P_FAMILY_DEMIVEEMON == TRUE
	.align 2
Cry_Demiveemon::
	.incbin "sound/direct_sound_samples/cries/demiveemon.bin"

	.align 2
Cry_Dorimon::
	.incbin "sound/direct_sound_samples/cries/dorimon.bin"

.if P_GEN_9_CROSS_EVOS == TRUE
	.align 2
Cry_Annihilape::
	.incbin "sound/direct_sound_samples/cries/annihilape.bin"
.endif @ P_GEN_9_CROSS_EVOS
.endif @ P_FAMILY_DEMIVEEMON

.if P_FAMILY_FRIMON == TRUE
	.align 2
Cry_Frimon::
	.incbin "sound/direct_sound_samples/cries/frimon.bin"

	.align 2
Cry_Gigimon::
	.incbin "sound/direct_sound_samples/cries/gigimon.bin"
.endif @ P_FAMILY_FRIMON

.if P_FAMILY_GUMMYMON == TRUE
	.align 2
Cry_Gummymon::
	.incbin "sound/direct_sound_samples/cries/gummymon.bin"

	.align 2
Cry_Gurimon::
	.incbin "sound/direct_sound_samples/cries/gurimon.bin"

	.align 2
Cry_Hiyarimon::
	.incbin "sound/direct_sound_samples/cries/hiyarimon.bin"

.if P_GEN_2_CROSS_EVOS == TRUE
	.align 2
Cry_Kamemon::
	.incbin "sound/direct_sound_samples/cries/kamemon.bin"
.endif @ P_GEN_2_CROSS_EVOS
.endif @ P_FAMILY_GUMMYMON

.if P_FAMILY_HOPMON == TRUE
	.align 2
Cry_Hopmon::
	.incbin "sound/direct_sound_samples/cries/hopmon.bin"

	.align 2
Cry_Kakkinmon::
	.incbin "sound/direct_sound_samples/cries/kakkinmon.bin"

	.align 2
Cry_Kapurimon::
	.incbin "sound/direct_sound_samples/cries/kapurimon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_KapurimonMega::
	.incbin "sound/direct_sound_samples/cries/kapurimon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_HOPMON

.if P_FAMILY_KOKOMON == TRUE
	.align 2
Cry_Kokomon::
	.incbin "sound/direct_sound_samples/cries/kokomon.bin"

	.align 2
Cry_Koromon::
	.incbin "sound/direct_sound_samples/cries/koromon.bin"

	.align 2
Cry_Kozenimon::
	.incbin "sound/direct_sound_samples/cries/kozenimon.bin"
.endif @ P_FAMILY_KOKOMON

.if P_FAMILY_KYAROMON == TRUE
	.align 2
Cry_Kyaromon::
	.incbin "sound/direct_sound_samples/cries/kyaromon.bin"

	.align 2
Cry_Kyokyomon::
	.incbin "sound/direct_sound_samples/cries/kyokyomon.bin"

	.align 2
Cry_Kyupimon::
	.incbin "sound/direct_sound_samples/cries/kyupimon.bin"
.endif @ P_FAMILY_KYAROMON

.if P_FAMILY_MINOMON == TRUE
	.align 2
Cry_Minomon::
	.incbin "sound/direct_sound_samples/cries/minomon.bin"

	.align 2
Cry_Missimon::
	.incbin "sound/direct_sound_samples/cries/missimon.bin"
.endif @ P_FAMILY_MINOMON

.if P_FAMILY_MONIMON == TRUE
	.align 2
Cry_Monimon::
	.incbin "sound/direct_sound_samples/cries/monimon.bin"

	.align 2
Cry_Moonmon::
	.incbin "sound/direct_sound_samples/cries/moonmon.bin"

	.align 2
Cry_Motimon::
	.incbin "sound/direct_sound_samples/cries/motimon.bin"
.endif @ P_FAMILY_MONIMON

.if P_FAMILY_NEGAMON == TRUE
	.align 2
Cry_Negamon::
	.incbin "sound/direct_sound_samples/cries/negamon.bin"

	.align 2
Cry_Nyaromon::
	.incbin "sound/direct_sound_samples/cries/nyaromon.bin"
.endif @ P_FAMILY_NEGAMON

.if P_FAMILY_PAGUMON == TRUE
	.align 2
Cry_Pagumon::
	.incbin "sound/direct_sound_samples/cries/pagumon.bin"

	.align 2
Cry_Pickmon_silver::
	.incbin "sound/direct_sound_samples/cries/pickmon_silver.bin"

.if P_GEN_2_CROSS_EVOS == TRUE
	.align 2
Cry_Liollmon::
	.incbin "sound/direct_sound_samples/cries/liollmon.bin"
.endif @ P_GEN_2_CROSS_EVOS
.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_Pickmon_silverMega::
	.incbin "sound/direct_sound_samples/cries/pickmon_silver_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.if P_GALARIAN_FORMS == TRUE
	.align 2
Cry_PagumonGalarian::
	.incbin "sound/direct_sound_samples/cries/pagumon_galar.bin"

.endif @ P_GALARIAN_FORMS
.endif @ P_FAMILY_PAGUMON

.if P_FAMILY_PICKMON_WHITE == TRUE
	.align 2
Cry_Pickmon_white::
	.incbin "sound/direct_sound_samples/cries/pickmon_white.bin"

	.align 2
Cry_Pickmon_red::
	.incbin "sound/direct_sound_samples/cries/pickmon_red.bin"

.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Magnezone::
	.incbin "sound/direct_sound_samples/cries/magnezone.bin"
.endif @ P_GEN_4_CROSS_EVOS
.endif @ P_FAMILY_PICKMON_WHITE

.if P_FAMILY_PINAMON == TRUE
	.align 2
Cry_Pinamon::
	.incbin "sound/direct_sound_samples/cries/pinamon.bin"

.if P_GALARIAN_FORMS == TRUE
	.align 2
Cry_Sirfetchd::
	.incbin "sound/direct_sound_samples/cries/sirfetchd.bin"

.endif @ P_GALARIAN_FORMS
.endif @ P_FAMILY_PINAMON

.if P_FAMILY_POROMON == TRUE
	.align 2
Cry_Poromon::
	.incbin "sound/direct_sound_samples/cries/poromon.bin"

	.align 2
Cry_Puroromon::
	.incbin "sound/direct_sound_samples/cries/puroromon.bin"
.endif @ P_FAMILY_POROMON

.if P_FAMILY_PUSURIMON == TRUE
	.align 2
Cry_Pusurimon::
	.incbin "sound/direct_sound_samples/cries/pusurimon.bin"

	.align 2
Cry_Puyoyomon::
	.incbin "sound/direct_sound_samples/cries/puyoyomon.bin"
.endif @ P_FAMILY_PUSURIMON

.if P_FAMILY_SAKUTTOMON == TRUE
	.align 2
Cry_Sakuttomon::
	.incbin "sound/direct_sound_samples/cries/sakuttomon.bin"

	.align 2
Cry_Sunmon::
	.incbin "sound/direct_sound_samples/cries/sunmon.bin"
.endif @ P_FAMILY_SAKUTTOMON

.if P_FAMILY_TANEMON == TRUE
	.align 2
Cry_Tanemon::
	.incbin "sound/direct_sound_samples/cries/tanemon.bin"

	.align 2
Cry_Tokomon::
	.incbin "sound/direct_sound_samples/cries/tokomon.bin"
.endif @ P_FAMILY_TANEMON

.if P_FAMILY_TOKOMON_X == TRUE
	.align 2
Cry_Tokomon_x::
	.incbin "sound/direct_sound_samples/cries/tokomon_x.bin"

	.align 2
Cry_Torballmon::
	.incbin "sound/direct_sound_samples/cries/torballmon.bin"

	.align 2
Cry_Tsumemon::
	.incbin "sound/direct_sound_samples/cries/tsumemon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_TsumemonMega::
	.incbin "sound/direct_sound_samples/cries/tsumemon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_TOKOMON_X

.if P_FAMILY_TSUNOMON == TRUE
	.align 2
Cry_Tsunomon::
	.incbin "sound/direct_sound_samples/cries/tsunomon.bin"

.if P_GEN_2_CROSS_EVOS == TRUE
	.align 2
Cry_Kodekacmon::
	.incbin "sound/direct_sound_samples/cries/kodekacmon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_KodekacmonMega::
	.incbin "sound/direct_sound_samples/cries/kodekacmon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_GEN_2_CROSS_EVOS
.endif @ P_FAMILY_TSUNOMON

.if P_FAMILY_TUMBLEMON == TRUE
	.align 2
Cry_Tumblemon::
	.incbin "sound/direct_sound_samples/cries/tumblemon.bin"

	.align 2
Cry_Upamon::
	.incbin "sound/direct_sound_samples/cries/upamon.bin"
.endif @ P_FAMILY_TUMBLEMON

.if P_FAMILY_VIXIMON == TRUE
	.align 2
Cry_Viximon::
	.incbin "sound/direct_sound_samples/cries/viximon.bin"

	.align 2
Cry_Wanyamon::
	.incbin "sound/direct_sound_samples/cries/wanyamon.bin"
.endif @ P_FAMILY_VIXIMON

.if P_FAMILY_XIAOMON == TRUE
	.align 2
Cry_Xiaomon::
	.incbin "sound/direct_sound_samples/cries/xiaomon.bin"

	.align 2
Cry_Yaamon::
	.incbin "sound/direct_sound_samples/cries/yaamon.bin"
.endif @ P_FAMILY_XIAOMON

.if P_FAMILY_YOKOMON == TRUE
	.align 2
Cry_Yokomon::
	.incbin "sound/direct_sound_samples/cries/yokomon.bin"

	.align 2
Cry_Agumon::
	.incbin "sound/direct_sound_samples/cries/agumon.bin"
.endif @ P_FAMILY_YOKOMON

.if P_FAMILY_AGUMON_06 == TRUE
	.align 2
Cry_Agumon_06::
	.incbin "sound/direct_sound_samples/cries/agumon_06.bin"

	.align 2
Cry_Agumon_expert::
	.incbin "sound/direct_sound_samples/cries/agumon_expert.bin"
.endif @ P_FAMILY_AGUMON_06

.if P_FAMILY_HITMONS == TRUE
.if P_GEN_2_CROSS_EVOS == TRUE
	.align 2
Cry_Salamon::
	.incbin "sound/direct_sound_samples/cries/salamon.bin"
.endif @ P_GEN_2_CROSS_EVOS

	.align 2
Cry_Agumon_x::
	.incbin "sound/direct_sound_samples/cries/agumon_x.bin"

	.align 2
Cry_Angoramon::
	.incbin "sound/direct_sound_samples/cries/angoramon.bin"

.if P_GEN_2_CROSS_EVOS == TRUE
	.align 2
Cry_Salamon_x::
	.incbin "sound/direct_sound_samples/cries/salamon_x.bin"
.endif @ P_GEN_2_CROSS_EVOS
.endif @ P_FAMILY_HITMONS

.if P_FAMILY_ARCADIAMON_ROOKIE == TRUE
	.align 2
Cry_Arcadiamon_rookie::
	.incbin "sound/direct_sound_samples/cries/arcadiamon_rookie.bin"

.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Lickilicky::
	.incbin "sound/direct_sound_samples/cries/lickilicky.bin"
.endif @ P_GEN_4_CROSS_EVOS
.endif @ P_FAMILY_ARCADIAMON_ROOKIE

.if P_FAMILY_ARGOMON_ROOKIE == TRUE
	.align 2
Cry_Argomon_rookie::
	.incbin "sound/direct_sound_samples/cries/argomon_rookie.bin"

	.align 2
Cry_Armadilmon::
	.incbin "sound/direct_sound_samples/cries/armadilmon.bin"
.endif @ P_FAMILY_ARGOMON_ROOKIE

.if P_FAMILY_ARURAUMON == TRUE
	.align 2
Cry_Aruraumon::
	.incbin "sound/direct_sound_samples/cries/aruraumon.bin"

	.align 2
Cry_Bakomon::
	.incbin "sound/direct_sound_samples/cries/bakomon.bin"

.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Rhyperior::
	.incbin "sound/direct_sound_samples/cries/rhyperior.bin"
.endif @ P_GEN_4_CROSS_EVOS
.endif @ P_FAMILY_ARURAUMON

.if P_FAMILY_BEARMON == TRUE
.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Happiny::
	.incbin "sound/direct_sound_samples/cries/happiny.bin"
.endif @ P_GEN_4_CROSS_EVOS

	.align 2
Cry_Bearmon::
	.incbin "sound/direct_sound_samples/cries/bearmon.bin"

.if P_GEN_2_CROSS_EVOS == TRUE
	.align 2
Cry_Shoutmon::
	.incbin "sound/direct_sound_samples/cries/shoutmon.bin"
.endif @ P_GEN_2_CROSS_EVOS
.endif @ P_FAMILY_BEARMON

.if P_FAMILY_BETAMON == TRUE
	.align 2
Cry_Betamon::
	.incbin "sound/direct_sound_samples/cries/betamon.bin"

.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Tangrowth::
	.incbin "sound/direct_sound_samples/cries/tangrowth.bin"
.endif @ P_GEN_4_CROSS_EVOS
.endif @ P_FAMILY_BETAMON

.if P_FAMILY_BETAMON_X == TRUE
	.align 2
Cry_Betamon_x::
	.incbin "sound/direct_sound_samples/cries/betamon_x.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_Betamon_xMega::
	.incbin "sound/direct_sound_samples/cries/betamon_x_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_BETAMON_X

.if P_FAMILY_BIYOMON == TRUE
	.align 2
Cry_Biyomon::
	.incbin "sound/direct_sound_samples/cries/biyomon.bin"

	.align 2
Cry_Blkagumon::
	.incbin "sound/direct_sound_samples/cries/blkagumon.bin"

.if P_GEN_2_CROSS_EVOS == TRUE
	.align 2
Cry_Psychemon::
	.incbin "sound/direct_sound_samples/cries/psychemon.bin"
.endif @ P_GEN_2_CROSS_EVOS
.endif @ P_FAMILY_BIYOMON

.if P_FAMILY_BLKAGUMON_X == TRUE
	.align 2
Cry_Blkagumon_x::
	.incbin "sound/direct_sound_samples/cries/blkagumon_x.bin"

	.align 2
Cry_Blkgabumon::
	.incbin "sound/direct_sound_samples/cries/blkgabumon.bin"
.endif @ P_FAMILY_BLKAGUMON_X

.if P_FAMILY_BLKGUILMON == TRUE
	.align 2
Cry_Blkguilmon::
	.incbin "sound/direct_sound_samples/cries/blkguilmon.bin"

	.align 2
Cry_Bokomon::
	.incbin "sound/direct_sound_samples/cries/bokomon.bin"
.endif @ P_FAMILY_BLKGUILMON

.if P_FAMILY_BULUCOMON == TRUE
.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_MimeJr::
	.incbin "sound/direct_sound_samples/cries/mime_jr.bin"
.endif @ P_GEN_4_CROSS_EVOS

	.align 2
Cry_Bulucomon::
	.incbin "sound/direct_sound_samples/cries/bulucomon.bin"

.if P_GALARIAN_FORMS == TRUE
	.align 2
Cry_MrRime::
	.incbin "sound/direct_sound_samples/cries/mr_rime.bin"

.endif @ P_GALARIAN_FORMS
.endif @ P_FAMILY_BULUCOMON

.if P_FAMILY_BURGERMON == TRUE
	.align 2
Cry_Burgermon::
	.incbin "sound/direct_sound_samples/cries/burgermon.bin"

.if P_GEN_2_CROSS_EVOS == TRUE
	.align 2
Cry_Monodramon::
	.incbin "sound/direct_sound_samples/cries/monodramon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_MonodramonMega::
	.incbin "sound/direct_sound_samples/cries/monodramon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_GEN_2_CROSS_EVOS
.if P_GEN_8_CROSS_EVOS == TRUE
	.align 2
Cry_Kleavor::
	.incbin "sound/direct_sound_samples/cries/kleavor.bin"
.endif @ P_GEN_8_CROSS_EVOS
.endif @ P_FAMILY_BURGERMON

.if P_FAMILY_SAMUAGUMON == TRUE
.if P_GEN_2_CROSS_EVOS == TRUE
	.align 2
Cry_Sangomon::
	.incbin "sound/direct_sound_samples/cries/sangomon.bin"
.endif @ P_GEN_2_CROSS_EVOS

	.align 2
Cry_Samuagumon::
	.incbin "sound/direct_sound_samples/cries/samuagumon.bin"
.endif @ P_FAMILY_SAMUAGUMON

.if P_FAMILY_CANDLEMON == TRUE
.if P_GEN_2_CROSS_EVOS == TRUE
	.align 2
Cry_Santaagumon::
	.incbin "sound/direct_sound_samples/cries/santaagumon.bin"
.endif @ P_GEN_2_CROSS_EVOS

	.align 2
Cry_Candlemon::
	.incbin "sound/direct_sound_samples/cries/candlemon.bin"

.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Electivire::
	.incbin "sound/direct_sound_samples/cries/electivire.bin"
.endif @ P_GEN_4_CROSS_EVOS
.endif @ P_FAMILY_CANDLEMON

.if P_FAMILY_CHIKURIMON == TRUE
.if P_GEN_2_CROSS_EVOS == TRUE
	.align 2
Cry_Blktoyamon::
	.incbin "sound/direct_sound_samples/cries/blktoyamon.bin"
.endif @ P_GEN_2_CROSS_EVOS

	.align 2
Cry_Chikurimon::
	.incbin "sound/direct_sound_samples/cries/chikurimon.bin"

.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Magmortar::
	.incbin "sound/direct_sound_samples/cries/magmortar.bin"
.endif @ P_GEN_4_CROSS_EVOS
.endif @ P_FAMILY_CHIKURIMON

.if P_FAMILY_TYUTYUMON == TRUE
	.align 2
Cry_Tyutyumon::
	.incbin "sound/direct_sound_samples/cries/tyutyumon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_TyutyumonMega::
	.incbin "sound/direct_sound_samples/cries/tyutyumon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_TYUTYUMON

.if P_FAMILY_CHUUMON == TRUE
	.align 2
Cry_Chuumon::
	.incbin "sound/direct_sound_samples/cries/chuumon.bin"
.endif @ P_FAMILY_CHUUMON

.if P_FAMILY_HAZYAGUMON == TRUE
	.align 2
Cry_Hazyagumon::
	.incbin "sound/direct_sound_samples/cries/hazyagumon.bin"

	.align 2
Cry_Commdramon::
	.incbin "sound/direct_sound_samples/cries/commdramon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_CommdramonMega::
	.incbin "sound/direct_sound_samples/cries/commdramon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_HAZYAGUMON

.if P_FAMILY_CORONAMON == TRUE
	.align 2
Cry_Coronamon::
	.incbin "sound/direct_sound_samples/cries/coronamon.bin"
.endif @ P_FAMILY_CORONAMON

.if P_FAMILY_CRABMON == TRUE
	.align 2
Cry_Crabmon::
	.incbin "sound/direct_sound_samples/cries/crabmon.bin"
.endif @ P_FAMILY_CRABMON

.if P_FAMILY_CRABMON_X == TRUE
	.align 2
Cry_Crabmon_x::
	.incbin "sound/direct_sound_samples/cries/crabmon_x.bin"

	.align 2
Cry_Cutemon::
	.incbin "sound/direct_sound_samples/cries/cutemon.bin"

	.align 2
Cry_Damemon::
	.incbin "sound/direct_sound_samples/cries/damemon.bin"

	.align 2
Cry_Demidevmon::
	.incbin "sound/direct_sound_samples/cries/demidevmon.bin"

.if P_GEN_2_CROSS_EVOS == TRUE
	.align 2
Cry_Kunemon::
	.incbin "sound/direct_sound_samples/cries/kunemon.bin"

	.align 2
Cry_Labramon::
	.incbin "sound/direct_sound_samples/cries/labramon.bin"
.endif @ P_GEN_2_CROSS_EVOS
.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Leafeon::
	.incbin "sound/direct_sound_samples/cries/leafeon.bin"

	.align 2
Cry_Glaceon::
	.incbin "sound/direct_sound_samples/cries/glaceon.bin"
.endif @ P_GEN_4_CROSS_EVOS
.if P_GEN_6_CROSS_EVOS == TRUE
	.align 2
Cry_Sylveon::
	.incbin "sound/direct_sound_samples/cries/sylveon.bin"
.endif @ P_GEN_6_CROSS_EVOS
.endif @ P_FAMILY_CRABMON_X

.if P_FAMILY_DOKUNEMON == TRUE
	.align 2
Cry_Dokunemon::
	.incbin "sound/direct_sound_samples/cries/dokunemon.bin"

.if P_GEN_2_CROSS_EVOS == TRUE
	.align 2
Cry_Renamon_x::
	.incbin "sound/direct_sound_samples/cries/renamon_x.bin"

.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_PorygonZ::
	.incbin "sound/direct_sound_samples/cries/porygon_z.bin"
.endif @ P_GEN_4_CROSS_EVOS
.endif @ P_GEN_2_CROSS_EVOS
.endif @ P_FAMILY_DOKUNEMON

.if P_FAMILY_DONDOKOMON == TRUE
	.align 2
Cry_Dondokomon::
	.incbin "sound/direct_sound_samples/cries/dondokomon.bin"

	.align 2
Cry_Dorumon::
	.incbin "sound/direct_sound_samples/cries/dorumon.bin"
.endif @ P_FAMILY_DONDOKOMON

.if P_FAMILY_DOTAGUMON == TRUE
	.align 2
Cry_Dotagumon::
	.incbin "sound/direct_sound_samples/cries/dotagumon.bin"

	.align 2
Cry_Dotfalcmon::
	.incbin "sound/direct_sound_samples/cries/dotfalcmon.bin"
.endif @ P_FAMILY_DOTAGUMON

.if P_FAMILY_DRACMON == TRUE
	.align 2
Cry_Dracmon::
	.incbin "sound/direct_sound_samples/cries/dracmon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_DracmonMega::
	.incbin "sound/direct_sound_samples/cries/dracmon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_DRACMON

.if P_FAMILY_DRACOMON == TRUE
.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Munchlax::
	.incbin "sound/direct_sound_samples/cries/munchlax.bin"
.endif @ P_GEN_4_CROSS_EVOS

	.align 2
Cry_Dracomon::
	.incbin "sound/direct_sound_samples/cries/dracomon.bin"
.endif @ P_FAMILY_DRACOMON

.if P_FAMILY_DRACOMON_X == TRUE
	.align 2
Cry_Dracomon_x::
	.incbin "sound/direct_sound_samples/cries/dracomon_x.bin"
.endif @ P_FAMILY_DRACOMON_X

.if P_FAMILY_EBIBURGMON == TRUE
	.align 2
Cry_Ebiburgmon::
	.incbin "sound/direct_sound_samples/cries/ebiburgmon.bin"
.endif @ P_FAMILY_EBIBURGMON

.if P_FAMILY_EKAKIMON == TRUE
	.align 2
Cry_Ekakimon::
	.incbin "sound/direct_sound_samples/cries/ekakimon.bin"
.endif @ P_FAMILY_EKAKIMON

.if P_FAMILY_ELECMON == TRUE
	.align 2
Cry_Elecmon::
	.incbin "sound/direct_sound_samples/cries/elecmon.bin"

	.align 2
Cry_Elecmon_violet::
	.incbin "sound/direct_sound_samples/cries/elecmon_violet.bin"

	.align 2
Cry_Espimon::
	.incbin "sound/direct_sound_samples/cries/espimon.bin"
.endif @ P_FAMILY_ELECMON

.if P_FAMILY_AGUMON_FAKE_EXPERT == TRUE
	.align 2
Cry_Agumon_fake_expert::
	.incbin "sound/direct_sound_samples/cries/agumon_fake_expert.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_Agumon_fake_expertMegaX::
	.incbin "sound/direct_sound_samples/cries/agumon_fake_expert_mega_x.bin"

	.align 2
Cry_Agumon_fake_expertMegaY::
	.incbin "sound/direct_sound_samples/cries/agumon_fake_expert_mega_y.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_AGUMON_FAKE_EXPERT

.if P_FAMILY_FALCOMON == TRUE
	.align 2
Cry_Falcomon::
	.incbin "sound/direct_sound_samples/cries/falcomon.bin"
.endif @ P_FAMILY_FALCOMON

.if P_FAMILY_FALCOMON_06 == TRUE
	.align 2
Cry_Falcomon_06::
	.incbin "sound/direct_sound_samples/cries/falcomon_06.bin"

	.align 2
Cry_Fanbeemon::
	.incbin "sound/direct_sound_samples/cries/fanbeemon.bin"

	.align 2
Cry_Flamemon::
	.incbin "sound/direct_sound_samples/cries/flamemon.bin"
.endif @ P_FAMILY_FALCOMON_06

.if P_FAMILY_FLORAMON == TRUE
	.align 2
Cry_Floramon::
	.incbin "sound/direct_sound_samples/cries/floramon.bin"

	.align 2
Cry_Gabumon::
	.incbin "sound/direct_sound_samples/cries/gabumon.bin"

	.align 2
Cry_Gabumon_x::
	.incbin "sound/direct_sound_samples/cries/gabumon_x.bin"
.endif @ P_FAMILY_FLORAMON

.if P_FAMILY_GAMMAMON == TRUE
	.align 2
Cry_Gammamon::
	.incbin "sound/direct_sound_samples/cries/gammamon.bin"

	.align 2
Cry_Gaomon::
	.incbin "sound/direct_sound_samples/cries/gaomon.bin"

	.align 2
Cry_Gaossmon::
	.incbin "sound/direct_sound_samples/cries/gaossmon.bin"
.endif @ P_FAMILY_GAMMAMON

.if P_FAMILY_GAZIMON == TRUE
	.align 2
Cry_Gazimon::
	.incbin "sound/direct_sound_samples/cries/gazimon.bin"

	.align 2
Cry_Gazimon_x::
	.incbin "sound/direct_sound_samples/cries/gazimon_x.bin"
.endif @ P_FAMILY_GAZIMON

.if P_FAMILY_GHOSTMON == TRUE
	.align 2
Cry_Ghostmon::
	.incbin "sound/direct_sound_samples/cries/ghostmon.bin"

	.align 2
Cry_Gizamon::
	.incbin "sound/direct_sound_samples/cries/gizamon.bin"
.endif @ P_FAMILY_GHOSTMON

.if P_FAMILY_GIZUMON == TRUE
	.align 2
Cry_Gizumon::
	.incbin "sound/direct_sound_samples/cries/gizumon.bin"

	.align 2
Cry_Goblimon::
	.incbin "sound/direct_sound_samples/cries/goblimon.bin"
.endif @ P_FAMILY_GIZUMON

.if P_FAMILY_GOMAMON == TRUE
	.align 2
Cry_Gomamon::
	.incbin "sound/direct_sound_samples/cries/gomamon.bin"

	.align 2
Cry_Gomamon_x::
	.incbin "sound/direct_sound_samples/cries/gomamon_x.bin"
.endif @ P_FAMILY_GOMAMON

.if P_FAMILY_GOTSUMON_X == TRUE
	.align 2
Cry_Gotsumon_x::
	.incbin "sound/direct_sound_samples/cries/gotsumon_x.bin"

	.align 2
Cry_Guilmon::
	.incbin "sound/direct_sound_samples/cries/guilmon.bin"
.endif @ P_FAMILY_GOTSUMON_X

.if P_FAMILY_HAGURUMON == TRUE
	.align 2
Cry_Hagurumon::
	.incbin "sound/direct_sound_samples/cries/hagurumon.bin"

	.align 2
Cry_Hagurumon_x::
	.incbin "sound/direct_sound_samples/cries/hagurumon_x.bin"

.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Togekiss::
	.incbin "sound/direct_sound_samples/cries/togekiss.bin"
.endif @ P_GEN_4_CROSS_EVOS
.endif @ P_FAMILY_HAGURUMON

.if P_FAMILY_HAWKMON == TRUE
	.align 2
Cry_Hawkmon::
	.incbin "sound/direct_sound_samples/cries/hawkmon.bin"

	.align 2
Cry_Herissmon::
	.incbin "sound/direct_sound_samples/cries/herissmon.bin"
.endif @ P_FAMILY_HAWKMON

.if P_FAMILY_HYOKOMON == TRUE
	.align 2
Cry_Hyokomon::
	.incbin "sound/direct_sound_samples/cries/hyokomon.bin"

	.align 2
Cry_Ignitemon::
	.incbin "sound/direct_sound_samples/cries/ignitemon.bin"

	.align 2
Cry_Impmon::
	.incbin "sound/direct_sound_samples/cries/impmon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_ImpmonMega::
	.incbin "sound/direct_sound_samples/cries/impmon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_HYOKOMON

.if P_FAMILY_JAZAMON == TRUE
.if P_GEN_3_CROSS_EVOS == TRUE
	.align 2
Cry_Biostegmon::
	.incbin "sound/direct_sound_samples/cries/biostegmon.bin"
.endif @ P_GEN_3_CROSS_EVOS

	.align 2
Cry_Jazamon::
	.incbin "sound/direct_sound_samples/cries/jazamon.bin"

	.align 2
Cry_Jellymon::
	.incbin "sound/direct_sound_samples/cries/jellymon.bin"
.endif @ P_FAMILY_JAZAMON

.if P_FAMILY_JUNKMON == TRUE
	.align 2
Cry_Bonsly::
	.incbin "sound/direct_sound_samples/cries/bonsly.bin"

	.align 2
Cry_Junkmon::
	.incbin "sound/direct_sound_samples/cries/junkmon.bin"
.endif @ P_FAMILY_JUNKMON

.if P_FAMILY_KERAMON == TRUE
	.align 2
Cry_Keramon::
	.incbin "sound/direct_sound_samples/cries/keramon.bin"

	.align 2
Cry_Keramon_x::
	.incbin "sound/direct_sound_samples/cries/keramon_x.bin"

	.align 2
Cry_Kodokgumon::
	.incbin "sound/direct_sound_samples/cries/kodokgumon.bin"
.endif @ P_FAMILY_KERAMON

.if P_FAMILY_KOKABUIMON == TRUE
	.align 2
Cry_Kokabuimon::
	.incbin "sound/direct_sound_samples/cries/kokabuimon.bin"

	.align 2
Cry_Ambipom::
	.incbin "sound/direct_sound_samples/cries/ambipom.bin"
.endif @ P_FAMILY_KOKABUIMON

.if P_FAMILY_KOKUWAMON == TRUE
	.align 2
Cry_Kokuwamon::
	.incbin "sound/direct_sound_samples/cries/kokuwamon.bin"

	.align 2
Cry_Kokuwamon_x::
	.incbin "sound/direct_sound_samples/cries/kokuwamon_x.bin"
.endif @ P_FAMILY_KOKUWAMON

.if P_FAMILY_KOTEMON == TRUE
	.align 2
Cry_Kotemon::
	.incbin "sound/direct_sound_samples/cries/kotemon.bin"

.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Yanmega::
	.incbin "sound/direct_sound_samples/cries/yanmega.bin"
.endif @ P_GEN_4_CROSS_EVOS
.endif @ P_FAMILY_KOTEMON

.if P_FAMILY_KUDAMON == TRUE
	.align 2
Cry_Kudamon::
	.incbin "sound/direct_sound_samples/cries/kudamon.bin"

	.align 2
Cry_Kudamon_06::
	.incbin "sound/direct_sound_samples/cries/kudamon_06.bin"

.if P_PALDEAN_FORMS == TRUE
	.align 2
Cry_Clodsire::
	.incbin "sound/direct_sound_samples/cries/clodsire.bin"

.endif @ P_PALDEAN_FORMS
.endif @ P_FAMILY_KUDAMON

.if P_FAMILY_LALAMON == TRUE
	.align 2
Cry_Lalamon::
	.incbin "sound/direct_sound_samples/cries/lalamon.bin"

	.align 2
Cry_Honchkrow::
	.incbin "sound/direct_sound_samples/cries/honchkrow.bin"
.endif @ P_FAMILY_LALAMON

.if P_FAMILY_LOOGAMON == TRUE
	.align 2
Cry_Loogamon::
	.incbin "sound/direct_sound_samples/cries/loogamon.bin"

	.align 2
Cry_Mismagius::
	.incbin "sound/direct_sound_samples/cries/mismagius.bin"
.endif @ P_FAMILY_LOOGAMON

.if P_FAMILY_LOPMON == TRUE
	.align 2
Cry_Lopmon::
	.incbin "sound/direct_sound_samples/cries/lopmon.bin"
.endif @ P_FAMILY_LOPMON

.if P_FAMILY_LOPMONX == TRUE
.if P_GEN_3_CROSS_EVOS == TRUE
	.align 2
Cry_Exveemon::
	.incbin "sound/direct_sound_samples/cries/exveemon.bin"
.endif @ P_GEN_3_CROSS_EVOS

	.align 2
Cry_Lopmonx::
	.incbin "sound/direct_sound_samples/cries/lopmonx.bin"
.endif @ P_FAMILY_LOPMONX

.if P_FAMILY_LUCEMON == TRUE
	.align 2
Cry_Lucemon::
	.incbin "sound/direct_sound_samples/cries/lucemon.bin"

.if P_GEN_9_CROSS_EVOS == TRUE
	.align 2
Cry_Farigiraf::
	.incbin "sound/direct_sound_samples/cries/farigiraf.bin"
.endif @ P_GEN_9_CROSS_EVOS
.endif @ P_FAMILY_LUCEMON

.if P_FAMILY_LUDOMON == TRUE
	.align 2
Cry_Ludomon::
	.incbin "sound/direct_sound_samples/cries/ludomon.bin"

	.align 2
Cry_Lunamon::
	.incbin "sound/direct_sound_samples/cries/lunamon.bin"
.endif @ P_FAMILY_LUDOMON

.if P_FAMILY_LUXMON == TRUE
	.align 2
Cry_Luxmon::
	.incbin "sound/direct_sound_samples/cries/luxmon.bin"

.if P_GEN_9_CROSS_EVOS == TRUE
	.align 2
Cry_Dudunsparce::
	.incbin "sound/direct_sound_samples/cries/dudunsparce.bin"
.endif @ P_GEN_9_CROSS_EVOS
.endif @ P_FAMILY_LUXMON

.if P_FAMILY_METABEE == TRUE
	.align 2
Cry_Metabee::
	.incbin "sound/direct_sound_samples/cries/metabee.bin"

.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Gliscor::
	.incbin "sound/direct_sound_samples/cries/gliscor.bin"
.endif @ P_GEN_4_CROSS_EVOS
.endif @ P_FAMILY_METABEE

.if P_FAMILY_MODBETAMON == TRUE
	.align 2
Cry_Modbetamon::
	.incbin "sound/direct_sound_samples/cries/modbetamon.bin"

	.align 2
Cry_Monitamon::
	.incbin "sound/direct_sound_samples/cries/monitamon.bin"
.endif @ P_FAMILY_MODBETAMON

.if P_FAMILY_MONMON == TRUE
	.align 2
Cry_Monmon::
	.incbin "sound/direct_sound_samples/cries/monmon.bin"

.if P_HISUIAN_FORMS == TRUE
	.align 2
Cry_Overqwil::
	.incbin "sound/direct_sound_samples/cries/overqwil.bin"

.endif @ P_HISUIAN_FORMS
.endif @ P_FAMILY_MONMON

.if P_FAMILY_MORPHOMON == TRUE
	.align 2
Cry_Morphomon::
	.incbin "sound/direct_sound_samples/cries/morphomon.bin"
.endif @ P_FAMILY_MORPHOMON

.if P_FAMILY_MUCHOMON == TRUE
	.align 2
Cry_Muchomon::
	.incbin "sound/direct_sound_samples/cries/muchomon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_MuchomonMega::
	.incbin "sound/direct_sound_samples/cries/muchomon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_MUCHOMON

.if P_FAMILY_MUSHROOMON == TRUE
	.align 2
Cry_Mushroomon::
	.incbin "sound/direct_sound_samples/cries/mushroomon.bin"

.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Weavile::
	.incbin "sound/direct_sound_samples/cries/weavile.bin"
.endif @ P_GEN_4_CROSS_EVOS
.if P_HISUIAN_FORMS == TRUE
	.align 2
Cry_Sneasler::
	.incbin "sound/direct_sound_samples/cries/sneasler.bin"

.endif @ P_HISUIAN_FORMS
.endif @ P_FAMILY_MUSHROOMON

.if P_FAMILY_NEEMON == TRUE
	.align 2
Cry_Neemon::
	.incbin "sound/direct_sound_samples/cries/neemon.bin"

	.align 2
Cry_Otamamon::
	.incbin "sound/direct_sound_samples/cries/otamamon.bin"

.if P_GEN_8_CROSS_EVOS == TRUE
	.align 2
Cry_Ursaluna::
	.incbin "sound/direct_sound_samples/cries/ursaluna.bin"
.endif @ P_GEN_8_CROSS_EVOS
.endif @ P_FAMILY_NEEMON

.if P_FAMILY_OTAMAMON_RED == TRUE
	.align 2
Cry_Otamamon_red::
	.incbin "sound/direct_sound_samples/cries/otamamon_red.bin"

	.align 2
Cry_Otamamon_x::
	.incbin "sound/direct_sound_samples/cries/otamamon_x.bin"
.endif @ P_FAMILY_OTAMAMON_RED

.if P_FAMILY_PALMON == TRUE
	.align 2
Cry_Palmon::
	.incbin "sound/direct_sound_samples/cries/palmon.bin"

	.align 2
Cry_Palmon_x::
	.incbin "sound/direct_sound_samples/cries/palmon_x.bin"

.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Mamoswine::
	.incbin "sound/direct_sound_samples/cries/mamoswine.bin"
.endif @ P_GEN_4_CROSS_EVOS
.endif @ P_FAMILY_PALMON

.if P_FAMILY_PATAMON == TRUE
	.align 2
Cry_Patamon::
	.incbin "sound/direct_sound_samples/cries/patamon.bin"

.if P_GALARIAN_FORMS == TRUE
	.align 2
Cry_Cursola::
	.incbin "sound/direct_sound_samples/cries/cursola.bin"

.endif @ P_GALARIAN_FORMS
.endif @ P_FAMILY_PATAMON

.if P_FAMILY_PAWNMON_BLACK == TRUE
	.align 2
Cry_Pawnmon_black::
	.incbin "sound/direct_sound_samples/cries/pawnmon_black.bin"

	.align 2
Cry_Pawnmon_white::
	.incbin "sound/direct_sound_samples/cries/pawnmon_white.bin"
.endif @ P_FAMILY_PAWNMON_BLACK

.if P_FAMILY_PENGUINMON == TRUE
	.align 2
Cry_Penguinmon::
	.incbin "sound/direct_sound_samples/cries/penguinmon.bin"
.endif @ P_FAMILY_PENGUINMON

.if P_FAMILY_PETITMAMON == TRUE
.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Mantyke::
	.incbin "sound/direct_sound_samples/cries/mantyke.bin"
.endif @ P_GEN_4_CROSS_EVOS

	.align 2
Cry_Petitmamon::
	.incbin "sound/direct_sound_samples/cries/petitmamon.bin"
.endif @ P_FAMILY_PETITMAMON

.if P_FAMILY_PHASCOMON == TRUE
	.align 2
Cry_Phascomon::
	.incbin "sound/direct_sound_samples/cries/phascomon.bin"
.endif @ P_FAMILY_PHASCOMON

.if P_FAMILY_PILLOMON == TRUE
	.align 2
Cry_Pillomon::
	.incbin "sound/direct_sound_samples/cries/pillomon.bin"

	.align 2
Cry_Pomumon::
	.incbin "sound/direct_sound_samples/cries/pomumon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_PomumonMega::
	.incbin "sound/direct_sound_samples/cries/pomumon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_PILLOMON

.if P_FAMILY_PULSEMON == TRUE
	.align 2
Cry_Pulsemon::
	.incbin "sound/direct_sound_samples/cries/pulsemon.bin"

	.align 2
Cry_Renamon::
	.incbin "sound/direct_sound_samples/cries/renamon.bin"
.endif @ P_FAMILY_PULSEMON

.if P_FAMILY_ROKUSHO == TRUE
	.align 2
Cry_Rokusho::
	.incbin "sound/direct_sound_samples/cries/rokusho.bin"

.if P_GEN_8_CROSS_EVOS == TRUE
	.align 2
Cry_Wyrdeer::
	.incbin "sound/direct_sound_samples/cries/wyrdeer.bin"
.endif @ P_GEN_8_CROSS_EVOS
.endif @ P_FAMILY_ROKUSHO

.if P_FAMILY_RYUDAMON == TRUE
	.align 2
Cry_Ryudamon::
	.incbin "sound/direct_sound_samples/cries/ryudamon.bin"
.endif @ P_FAMILY_RYUDAMON

.if P_FAMILY_SHAMANMON == TRUE
	.align 2
Cry_Shamanmon::
	.incbin "sound/direct_sound_samples/cries/shamanmon.bin"
.endif @ P_FAMILY_SHAMANMON

.if P_FAMILY_YUKIAGUMON == TRUE
	.align 2
Cry_Yukiagumon::
	.incbin "sound/direct_sound_samples/cries/yukiagumon.bin"
.endif @ P_FAMILY_YUKIAGUMON

.if P_FAMILY_YUKIAGUMON_06 == TRUE
	.align 2
Cry_Yukiagumon_06::
	.incbin "sound/direct_sound_samples/cries/yukiagumon_06.bin"
.endif @ P_FAMILY_YUKIAGUMON_06

.if P_FAMILY_ICEGOBIMON == TRUE
	.align 2
Cry_Icegobimon::
	.incbin "sound/direct_sound_samples/cries/icegobimon.bin"
.endif @ P_FAMILY_ICEGOBIMON

.if P_FAMILY_SOLARMON == TRUE
	.align 2
Cry_Solarmon::
	.incbin "sound/direct_sound_samples/cries/solarmon.bin"

	.align 2
Cry_Sounbrdmon::
	.incbin "sound/direct_sound_samples/cries/sounbrdmon.bin"

	.align 2
Cry_Spadamon::
	.incbin "sound/direct_sound_samples/cries/spadamon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_SpadamonMega::
	.incbin "sound/direct_sound_samples/cries/spadamon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_SOLARMON

.if P_FAMILY_SPARROWMON == TRUE
	.align 2
Cry_Sparrowmon::
	.incbin "sound/direct_sound_samples/cries/sparrowmon.bin"
.endif @ P_FAMILY_SPARROWMON

.if P_FAMILY_STARMON_2010 == TRUE
	.align 2
Cry_Starmon_2010::
	.incbin "sound/direct_sound_samples/cries/starmon_2010.bin"
.endif @ P_FAMILY_STARMON_2010

.if P_FAMILY_STRABIMON == TRUE
	.align 2
Cry_Strabimon::
	.incbin "sound/direct_sound_samples/cries/strabimon.bin"
.endif @ P_FAMILY_STRABIMON

.if P_FAMILY_SUNARZAMON == TRUE
	.align 2
Cry_Sunarzamon::
	.incbin "sound/direct_sound_samples/cries/sunarzamon.bin"

	.align 2
Cry_Swimmon::
	.incbin "sound/direct_sound_samples/cries/swimmon.bin"

	.align 2
Cry_Syakomon::
	.incbin "sound/direct_sound_samples/cries/syakomon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_SyakomonMega::
	.incbin "sound/direct_sound_samples/cries/syakomon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_SUNARZAMON

.if P_FAMILY_SYAKOMON_X == TRUE
	.align 2
Cry_Syakomon_x::
	.incbin "sound/direct_sound_samples/cries/syakomon_x.bin"

	.align 2
Cry_Tapirmon::
	.incbin "sound/direct_sound_samples/cries/tapirmon.bin"

	.align 2
Cry_Tentomon::
	.incbin "sound/direct_sound_samples/cries/tentomon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_TentomonMega::
	.incbin "sound/direct_sound_samples/cries/tentomon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_SYAKOMON_X

.if P_FAMILY_TERRIERMON == TRUE
	.align 2
Cry_Terriermon::
	.incbin "sound/direct_sound_samples/cries/terriermon.bin"

	.align 2
Cry_Terriermon_assistant::
	.incbin "sound/direct_sound_samples/cries/terriermon_assistant.bin"

	.align 2
Cry_Terriermon_x::
	.incbin "sound/direct_sound_samples/cries/terriermon_x.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_Terriermon_xMega::
	.incbin "sound/direct_sound_samples/cries/terriermon_x_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_TERRIERMON

.if P_FAMILY_TINKERMON == TRUE
	.align 2
Cry_Tinkermon::
	.incbin "sound/direct_sound_samples/cries/tinkermon.bin"

	.align 2
Cry_Tinpet::
	.incbin "sound/direct_sound_samples/cries/tinpet.bin"
.endif @ P_FAMILY_TINKERMON

.if P_FAMILY_TOYAGUMON == TRUE
	.align 2
Cry_Toyagumon::
	.incbin "sound/direct_sound_samples/cries/toyagumon.bin"

	.align 2
Cry_Tsukaimon::
	.incbin "sound/direct_sound_samples/cries/tsukaimon.bin"

.if P_GALARIAN_FORMS == TRUE
	.align 2
Cry_Obstagoon::
	.incbin "sound/direct_sound_samples/cries/obstagoon.bin"

.endif @ P_GALARIAN_FORMS
.endif @ P_FAMILY_TOYAGUMON

.if P_FAMILY_VEEMON == TRUE
	.align 2
Cry_Veemon::
	.incbin "sound/direct_sound_samples/cries/veemon.bin"

	.align 2
Cry_Vemmon::
	.incbin "sound/direct_sound_samples/cries/vemmon.bin"

	.align 2
Cry_Vorvomon::
	.incbin "sound/direct_sound_samples/cries/vorvomon.bin"

	.align 2
Cry_Wormmon::
	.incbin "sound/direct_sound_samples/cries/wormmon.bin"

	.align 2
Cry_Zenimon::
	.incbin "sound/direct_sound_samples/cries/zenimon.bin"
.endif @ P_FAMILY_VEEMON

.if P_FAMILY_ZUBAMON == TRUE
	.align 2
Cry_Zubamon::
	.incbin "sound/direct_sound_samples/cries/zubamon.bin"

	.align 2
Cry_Aegiomon::
	.incbin "sound/direct_sound_samples/cries/aegiomon.bin"

	.align 2
Cry_Agunimon::
	.incbin "sound/direct_sound_samples/cries/agunimon.bin"
.endif @ P_FAMILY_ZUBAMON

.if P_FAMILY_AIRDRAMON == TRUE
	.align 2
Cry_Airdramon::
	.incbin "sound/direct_sound_samples/cries/airdramon.bin"

	.align 2
Cry_Akatorimon::
	.incbin "sound/direct_sound_samples/cries/akatorimon.bin"

	.align 2
Cry_Allomon::
	.incbin "sound/direct_sound_samples/cries/allomon.bin"
.endif @ P_FAMILY_AIRDRAMON

.if P_FAMILY_ALLOMON_X == TRUE
	.align 2
Cry_Allomon_x::
	.incbin "sound/direct_sound_samples/cries/allomon_x.bin"

	.align 2
Cry_Angelamon::
	.incbin "sound/direct_sound_samples/cries/angelamon.bin"
.endif @ P_FAMILY_ALLOMON_X

.if P_FAMILY_ANGEMON == TRUE
	.align 2
Cry_Angemon::
	.incbin "sound/direct_sound_samples/cries/angemon.bin"

	.align 2
Cry_Ankylomon::
	.incbin "sound/direct_sound_samples/cries/ankylomon.bin"
.endif @ P_FAMILY_ANGEMON

.if P_FAMILY_APEMON == TRUE
	.align 2
Cry_Apemon::
	.incbin "sound/direct_sound_samples/cries/apemon.bin"

	.align 2
Cry_Aquilamon::
	.incbin "sound/direct_sound_samples/cries/aquilamon.bin"

	.align 2
Cry_Arcadiamon_champion::
	.incbin "sound/direct_sound_samples/cries/arcadiamon_champion.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_Arcadiamon_championMega::
	.incbin "sound/direct_sound_samples/cries/arcadiamon_champion_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Gallade::
	.incbin "sound/direct_sound_samples/cries/gallade.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_GalladeMega::
	.incbin "sound/direct_sound_samples/cries/gallade_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_GEN_4_CROSS_EVOS
.endif @ P_FAMILY_APEMON

.if P_FAMILY_ARCHELOMON == TRUE
	.align 2
Cry_Archelomon::
	.incbin "sound/direct_sound_samples/cries/archelomon.bin"

	.align 2
Cry_Argomon_champion::
	.incbin "sound/direct_sound_samples/cries/argomon_champion.bin"
.endif @ P_FAMILY_ARCHELOMON

.if P_FAMILY_ARESDRAMON == TRUE
	.align 2
Cry_Aresdramon::
	.incbin "sound/direct_sound_samples/cries/aresdramon.bin"

	.align 2
Cry_Atamademon::
	.incbin "sound/direct_sound_samples/cries/atamademon.bin"
.endif @ P_FAMILY_ARESDRAMON

.if P_FAMILY_AURUMON == TRUE
	.align 2
Cry_Aurumon::
	.incbin "sound/direct_sound_samples/cries/aurumon.bin"

	.align 2
Cry_Axemon::
	.incbin "sound/direct_sound_samples/cries/axemon.bin"

	.align 2
Cry_Baboonmon::
	.incbin "sound/direct_sound_samples/cries/baboonmon.bin"
.endif @ P_FAMILY_AURUMON

.if P_FAMILY_BAKEMON == TRUE
	.align 2
Cry_Bakemon::
	.incbin "sound/direct_sound_samples/cries/bakemon.bin"

	.align 2
Cry_Balistamon::
	.incbin "sound/direct_sound_samples/cries/balistamon.bin"

	.align 2
Cry_Baluchimon::
	.incbin "sound/direct_sound_samples/cries/baluchimon.bin"
.endif @ P_FAMILY_BAKEMON

.if P_FAMILY_BAOHUCKMON == TRUE
	.align 2
Cry_Baohuckmon::
	.incbin "sound/direct_sound_samples/cries/baohuckmon.bin"

	.align 2
Cry_Baromon::
	.incbin "sound/direct_sound_samples/cries/baromon.bin"

	.align 2
Cry_Trailmon_battle_armament::
	.incbin "sound/direct_sound_samples/cries/trailmon_battle_armament.bin"
.endif @ P_FAMILY_BAOHUCKMON

.if P_FAMILY_BETGAMAMON == TRUE
	.align 2
Cry_Betgamamon::
	.incbin "sound/direct_sound_samples/cries/betgamamon.bin"

	.align 2
Cry_Bioquetmon::
	.incbin "sound/direct_sound_samples/cries/bioquetmon.bin"
.endif @ P_FAMILY_BETGAMAMON

.if P_FAMILY_BIOTHUNMON == TRUE
	.align 2
Cry_Biothunmon::
	.incbin "sound/direct_sound_samples/cries/biothunmon.bin"

.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Probopass::
	.incbin "sound/direct_sound_samples/cries/probopass.bin"
.endif @ P_GEN_4_CROSS_EVOS
.endif @ P_FAMILY_BIOTHUNMON

.if P_FAMILY_BIRDRAMON == TRUE
	.align 2
Cry_Birdramon::
	.incbin "sound/direct_sound_samples/cries/birdramon.bin"

	.align 2
Cry_Blgaogamon::
	.incbin "sound/direct_sound_samples/cries/blgaogamon.bin"
.endif @ P_FAMILY_BIRDRAMON

.if P_FAMILY_BLGARGOMON == TRUE
	.align 2
Cry_Blgargomon::
	.incbin "sound/direct_sound_samples/cries/blgargomon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_BlgargomonMega::
	.incbin "sound/direct_sound_samples/cries/blgargomon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_BLGARGOMON

.if P_FAMILY_BLGARURMON == TRUE
	.align 2
Cry_Blgarurmon::
	.incbin "sound/direct_sound_samples/cries/blgarurmon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_BlgarurmonMega::
	.incbin "sound/direct_sound_samples/cries/blgarurmon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_BLGARURMON

.if P_FAMILY_BLKGATOMON == TRUE
	.align 2
Cry_Blkgatomon::
	.incbin "sound/direct_sound_samples/cries/blkgatomon.bin"

	.align 2
Cry_Blkgatomon_uver::
	.incbin "sound/direct_sound_samples/cries/blkgatomon_uver.bin"

	.align 2
Cry_Blgrowlmon::
	.incbin "sound/direct_sound_samples/cries/blgrowlmon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_BlgrowlmonMega::
	.incbin "sound/direct_sound_samples/cries/blgrowlmon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_BLKGATOMON

.if P_FAMILY_SAWKUWAMON == TRUE
	.align 2
Cry_Sawkuwamon::
	.incbin "sound/direct_sound_samples/cries/sawkuwamon.bin"

	.align 2
Cry_Blimpmon::
	.incbin "sound/direct_sound_samples/cries/blimpmon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_BlimpmonMega::
	.incbin "sound/direct_sound_samples/cries/blimpmon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_SAWKUWAMON

.if P_FAMILY_BOARMON == TRUE
	.align 2
Cry_Boarmon::
	.incbin "sound/direct_sound_samples/cries/boarmon.bin"

	.align 2
Cry_Bomnanimon::
	.incbin "sound/direct_sound_samples/cries/bomnanimon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_BomnanimonMega::
	.incbin "sound/direct_sound_samples/cries/bomnanimon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_BOARMON

.if P_FAMILY_BOOGIEMON == TRUE
	.align 2
Cry_Boogiemon::
	.incbin "sound/direct_sound_samples/cries/boogiemon.bin"
.endif @ P_FAMILY_BOOGIEMON

.if P_FAMILY_BUCCHIEMON_RED == TRUE
	.align 2
Cry_Bucchiemon_red::
	.incbin "sound/direct_sound_samples/cries/bucchiemon_red.bin"
.endif @ P_FAMILY_BUCCHIEMON_RED

.if P_FAMILY_BUCCHIEMON_GREEN_BULKMON == TRUE
	.align 2
Cry_Bucchiemon_green::
	.incbin "sound/direct_sound_samples/cries/bucchiemon_green.bin"

	.align 2
Cry_Bulkmon::
	.incbin "sound/direct_sound_samples/cries/bulkmon.bin"
.endif @ P_FAMILY_BUCCHIEMON_GREEN_BULKMON

.if P_FAMILY_BULLMON == TRUE
.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Budew::
	.incbin "sound/direct_sound_samples/cries/budew.bin"
.endif @ P_GEN_4_CROSS_EVOS

	.align 2
Cry_Bullmon::
	.incbin "sound/direct_sound_samples/cries/bullmon.bin"

.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Roserade::
	.incbin "sound/direct_sound_samples/cries/roserade.bin"
.endif @ P_GEN_4_CROSS_EVOS
.endif @ P_FAMILY_BULLMON

.if P_FAMILY_BURAIMON == TRUE
	.align 2
Cry_Buraimon::
	.incbin "sound/direct_sound_samples/cries/buraimon.bin"

	.align 2
Cry_Burgermon_champion::
	.incbin "sound/direct_sound_samples/cries/burgermon_champion.bin"
.endif @ P_FAMILY_BURAIMON

.if P_FAMILY_CHOUMON == TRUE
	.align 2
Cry_Choumon::
	.incbin "sound/direct_sound_samples/cries/choumon.bin"

	.align 2
Cry_Centarumon::
	.incbin "sound/direct_sound_samples/cries/centarumon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_CentarumonMega::
	.incbin "sound/direct_sound_samples/cries/centarumon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_CHOUMON

.if P_FAMILY_CHAMBLEMON == TRUE
	.align 2
Cry_Chamblemon::
	.incbin "sound/direct_sound_samples/cries/chamblemon.bin"

	.align 2
Cry_Chamelemon::
	.incbin "sound/direct_sound_samples/cries/chamelemon.bin"
.endif @ P_FAMILY_CHAMBLEMON

.if P_FAMILY_CHRYSALMON == TRUE
	.align 2
Cry_Chrysalmon::
	.incbin "sound/direct_sound_samples/cries/chrysalmon.bin"

	.align 2
Cry_Citramon::
	.incbin "sound/direct_sound_samples/cries/citramon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_CitramonMega::
	.incbin "sound/direct_sound_samples/cries/citramon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_CHRYSALMON

.if P_FAMILY_CLOCKMON == TRUE
	.align 2
Cry_Clockmon::
	.incbin "sound/direct_sound_samples/cries/clockmon.bin"
.endif @ P_FAMILY_CLOCKMON

.if P_FAMILY_CLOCKMON_FUSION == TRUE
	.align 2
Cry_Clockmon_fusion::
	.incbin "sound/direct_sound_samples/cries/clockmon_fusion.bin"

	.align 2
Cry_Coelamon::
	.incbin "sound/direct_sound_samples/cries/coelamon.bin"
.endif @ P_FAMILY_CLOCKMON_FUSION

.if P_FAMILY_COREDRAMON_BLUE == TRUE
	.align 2
Cry_Coredramon_blue::
	.incbin "sound/direct_sound_samples/cries/coredramon_blue.bin"
.endif @ P_FAMILY_COREDRAMON_BLUE

.if P_FAMILY_COREDRAMON_GREEN == TRUE
	.align 2
Cry_Coredramon_green::
	.incbin "sound/direct_sound_samples/cries/coredramon_green.bin"

	.align 2
Cry_Cyclonemon::
	.incbin "sound/direct_sound_samples/cries/cyclonemon.bin"

	.align 2
Cry_Damemon_fusion::
	.incbin "sound/direct_sound_samples/cries/damemon_fusion.bin"
.endif @ P_FAMILY_COREDRAMON_GREEN

.if P_FAMILY_DARCMON == TRUE
	.align 2
Cry_Darcmon::
	.incbin "sound/direct_sound_samples/cries/darcmon.bin"

	.align 2
Cry_Trailmon_dark::
	.incbin "sound/direct_sound_samples/cries/trailmon_dark.bin"
.endif @ P_FAMILY_DARCMON

.if P_FAMILY_DARLIZAMON == TRUE
	.align 2
Cry_Darlizamon::
	.incbin "sound/direct_sound_samples/cries/darlizamon.bin"

	.align 2
Cry_Darmailmon::
	.incbin "sound/direct_sound_samples/cries/darmailmon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_DarmailmonMega::
	.incbin "sound/direct_sound_samples/cries/darmailmon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_DARLIZAMON

.if P_FAMILY_DARKTYRMON == TRUE
	.align 2
Cry_Darktyrmon::
	.incbin "sound/direct_sound_samples/cries/darktyrmon.bin"
.endif @ P_FAMILY_DARKTYRMON

.if P_FAMILY_DARKTYRMON_X == TRUE
	.align 2
Cry_Darktyrmon_x::
	.incbin "sound/direct_sound_samples/cries/darktyrmon_x.bin"
.endif @ P_FAMILY_DARKTYRMON_X

.if P_FAMILY_DECKDRAMON == TRUE
	.align 2
Cry_Deckdramon::
	.incbin "sound/direct_sound_samples/cries/deckdramon.bin"
.endif @ P_FAMILY_DECKDRAMON

.if P_FAMILY_DELTAMON == TRUE
	.align 2
Cry_Deltamon::
	.incbin "sound/direct_sound_samples/cries/deltamon.bin"
.endif @ P_FAMILY_DELTAMON

.if P_FAMILY_DEPTHMON == TRUE
	.align 2
Cry_Depthmon::
	.incbin "sound/direct_sound_samples/cries/depthmon.bin"

	.align 2
Cry_Deputymon::
	.incbin "sound/direct_sound_samples/cries/deputymon.bin"
.endif @ P_FAMILY_DEPTHMON

.if P_FAMILY_DEVIDRAMON == TRUE
	.align 2
Cry_Devidramon::
	.incbin "sound/direct_sound_samples/cries/devidramon.bin"

	.align 2
Cry_Devimon::
	.incbin "sound/direct_sound_samples/cries/devimon.bin"
.endif @ P_FAMILY_DEVIDRAMON

.if P_FAMILY_DEXDORUMON == TRUE
	.align 2
Cry_Dexdorumon::
	.incbin "sound/direct_sound_samples/cries/dexdorumon.bin"

	.align 2
Cry_Diatrymon::
	.incbin "sound/direct_sound_samples/cries/diatrymon.bin"
.endif @ P_FAMILY_DEXDORUMON

.if P_FAMILY_DIGMON == TRUE
	.align 2
Cry_Digmon::
	.incbin "sound/direct_sound_samples/cries/digmon.bin"

	.align 2
Cry_Dinohyumon::
	.incbin "sound/direct_sound_samples/cries/dinohyumon.bin"
.endif @ P_FAMILY_DIGMON

.if P_FAMILY_DOBERMON == TRUE
	.align 2
Cry_Dobermon::
	.incbin "sound/direct_sound_samples/cries/dobermon.bin"

	.align 2
Cry_Dobermon_x::
	.incbin "sound/direct_sound_samples/cries/dobermon_x.bin"
.endif @ P_FAMILY_DOBERMON

.if P_FAMILY_DOGGYMON == TRUE
	.align 2
Cry_Doggymon::
	.incbin "sound/direct_sound_samples/cries/doggymon.bin"

	.align 2
Cry_Dokugumon::
	.incbin "sound/direct_sound_samples/cries/dokugumon.bin"
.endif @ P_FAMILY_DOGGYMON

.if P_FAMILY_DOLPHMON == TRUE
	.align 2
Cry_Dolphmon::
	.incbin "sound/direct_sound_samples/cries/dolphmon.bin"
.endif @ P_FAMILY_DOLPHMON

.if P_FAMILY_DONSHOUMON == TRUE
	.align 2
Cry_Donshoumon::
	.incbin "sound/direct_sound_samples/cries/donshoumon.bin"
.endif @ P_FAMILY_DONSHOUMON

.if P_FAMILY_DORUGAMON == TRUE
	.align 2
Cry_Dorugamon::
	.incbin "sound/direct_sound_samples/cries/dorugamon.bin"

	.align 2
Cry_Dorulumon::
	.incbin "sound/direct_sound_samples/cries/dorulumon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_DorulumonMega::
	.incbin "sound/direct_sound_samples/cries/dorulumon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_DORUGAMON

.if P_FAMILY_DRIMOGEMON == TRUE
	.align 2
Cry_Drimogemon::
	.incbin "sound/direct_sound_samples/cries/drimogemon.bin"

	.align 2
Cry_Ebidramon::
	.incbin "sound/direct_sound_samples/cries/ebidramon.bin"

.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Dusknoir::
	.incbin "sound/direct_sound_samples/cries/dusknoir.bin"
.endif @ P_GEN_4_CROSS_EVOS
.endif @ P_FAMILY_DRIMOGEMON

.if P_FAMILY_ELEPHANMON == TRUE
	.align 2
Cry_Elephanmon::
	.incbin "sound/direct_sound_samples/cries/elephanmon.bin"
.endif @ P_FAMILY_ELEPHANMON

.if P_FAMILY_EOSMON_CHAMPION == TRUE
.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Chingling::
	.incbin "sound/direct_sound_samples/cries/chingling.bin"
.endif @ P_GEN_4_CROSS_EVOS

	.align 2
Cry_Eosmon_champion::
	.incbin "sound/direct_sound_samples/cries/eosmon_champion.bin"
.endif @ P_FAMILY_EOSMON_CHAMPION

.if P_FAMILY_EXERMON == TRUE
	.align 2
Cry_Exermon::
	.incbin "sound/direct_sound_samples/cries/exermon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_ExermonMega::
	.incbin "sound/direct_sound_samples/cries/exermon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_EXERMON

.if P_FAMILY_EXVEEMON_VIRUS == TRUE
	.align 2
Cry_Exveemon_virus::
	.incbin "sound/direct_sound_samples/cries/exveemon_virus.bin"

	.align 2
Cry_Eyesmon::
	.incbin "sound/direct_sound_samples/cries/eyesmon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_EyesmonMega::
	.incbin "sound/direct_sound_samples/cries/eyesmon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.if P_GEN_4_CROSS_EVOS == TRUE
	.align 2
Cry_Froslass::
	.incbin "sound/direct_sound_samples/cries/froslass.bin"
.endif @ P_GEN_4_CROSS_EVOS
.endif @ P_FAMILY_EXVEEMON_VIRUS

.if P_FAMILY_EYESMON_SCATTERMODE == TRUE
	.align 2
Cry_Eyesmon_scattermode::
	.incbin "sound/direct_sound_samples/cries/eyesmon_scattermode.bin"

	.align 2
Cry_Fangmon::
	.incbin "sound/direct_sound_samples/cries/fangmon.bin"

	.align 2
Cry_Filmon::
	.incbin "sound/direct_sound_samples/cries/filmon.bin"
.endif @ P_FAMILY_EYESMON_SCATTERMODE

.if P_FAMILY_FIRAMON == TRUE
	.align 2
Cry_Firamon::
	.incbin "sound/direct_sound_samples/cries/firamon.bin"

	.align 2
Cry_Fladramon::
	.incbin "sound/direct_sound_samples/cries/fladramon.bin"

	.align 2
Cry_Flawizamon::
	.incbin "sound/direct_sound_samples/cries/flawizamon.bin"
.endif @ P_FAMILY_FIRAMON

.if P_FAMILY_FLARIZAMON == TRUE
	.align 2
Cry_Flarizamon::
	.incbin "sound/direct_sound_samples/cries/flarizamon.bin"
.endif @ P_FAMILY_FLARIZAMON

.if P_FAMILY_FLYBEEMON == TRUE
	.align 2
Cry_Flybeemon::
	.incbin "sound/direct_sound_samples/cries/flybeemon.bin"
.endif @ P_FAMILY_FLYBEEMON

.if P_FAMILY_FLYMON == TRUE
	.align 2
Cry_Flymon::
	.incbin "sound/direct_sound_samples/cries/flymon.bin"

	.align 2
Cry_Frigimon::
	.incbin "sound/direct_sound_samples/cries/frigimon.bin"

	.align 2
Cry_Frogmon::
	.incbin "sound/direct_sound_samples/cries/frogmon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_FrogmonMega::
	.incbin "sound/direct_sound_samples/cries/frogmon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_FLYMON

.if P_FAMILY_FUGAMON == TRUE
	.align 2
Cry_Fugamon::
	.incbin "sound/direct_sound_samples/cries/fugamon.bin"

	.align 2
Cry_Ganemon::
	.incbin "sound/direct_sound_samples/cries/ganemon.bin"

	.align 2
Cry_Gaogamon::
	.incbin "sound/direct_sound_samples/cries/gaogamon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_GaogamonMega::
	.incbin "sound/direct_sound_samples/cries/gaogamon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_FUGAMON

.if P_FAMILY_GARGOMON == TRUE
	.align 2
Cry_Gargomon::
	.incbin "sound/direct_sound_samples/cries/gargomon.bin"
.endif @ P_FAMILY_GARGOMON

.if P_FAMILY_GARGOYLMON == TRUE
	.align 2
Cry_Gargoylmon::
	.incbin "sound/direct_sound_samples/cries/gargoylmon.bin"
.endif @ P_FAMILY_GARGOYLMON

.if P_FAMILY_GARURUMON == TRUE
	.align 2
Cry_Garurumon::
	.incbin "sound/direct_sound_samples/cries/garurumon.bin"
.endif @ P_FAMILY_GARURUMON

.if P_FAMILY_GARURUMON_X == TRUE
	.align 2
Cry_Garurumon_x::
	.incbin "sound/direct_sound_samples/cries/garurumon_x.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_Garurumon_xMega::
	.incbin "sound/direct_sound_samples/cries/garurumon_x_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_GARURUMON_X

.if P_FAMILY_GATOMON == TRUE
	.align 2
Cry_Gatomon::
	.incbin "sound/direct_sound_samples/cries/gatomon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_GatomonMega::
	.incbin "sound/direct_sound_samples/cries/gatomon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_GATOMON

.if P_FAMILY_GATOMON_X == TRUE
	.align 2
Cry_Gatomon_x::
	.incbin "sound/direct_sound_samples/cries/gatomon_x.bin"

.if P_PRIMAL_REVERSIONS == TRUE
	.align 2
Cry_Gatomon_xPrimal::
	.incbin "sound/direct_sound_samples/cries/gatomon_x_primal.bin"

.endif @ P_PRIMAL_REVERSIONS
.endif @ P_FAMILY_GATOMON_X

.if P_FAMILY_GEKOMON == TRUE
	.align 2
Cry_Gekomon::
	.incbin "sound/direct_sound_samples/cries/gekomon.bin"

.if P_PRIMAL_REVERSIONS == TRUE
	.align 2
Cry_GekomonPrimal::
	.incbin "sound/direct_sound_samples/cries/gekomon_primal.bin"

.endif @ P_PRIMAL_REVERSIONS
.endif @ P_FAMILY_GEKOMON

.if P_FAMILY_GEOGREYMON == TRUE
	.align 2
Cry_Geogreymon::
	.incbin "sound/direct_sound_samples/cries/geogreymon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_GeogreymonMega::
	.incbin "sound/direct_sound_samples/cries/geogreymon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_GEOGREYMON

.if P_FAMILY_GEREMON == TRUE
	.align 2
Cry_Geremon::
	.incbin "sound/direct_sound_samples/cries/geremon.bin"
.endif @ P_FAMILY_GEREMON

.if P_FAMILY_GESOMON == TRUE
	.align 2
Cry_Gesomon::
	.incbin "sound/direct_sound_samples/cries/gesomon.bin"
.endif @ P_FAMILY_GESOMON

.if P_FAMILY_DEATHMON_CMON_DIGIMON == TRUE
	.align 2
Cry_Deathmon_cmon_digimon::
	.incbin "sound/direct_sound_samples/cries/deathmon_cmon_digimon.bin"

	.align 2
Cry_Greymon::
	.incbin "sound/direct_sound_samples/cries/greymon.bin"

	.align 2
Cry_Kabuterimon::
	.incbin "sound/direct_sound_samples/cries/kabuterimon.bin"
.endif @ P_FAMILY_DEATHMON_CMON_DIGIMON

.if P_FAMILY_MERAMON == TRUE
	.align 2
Cry_Meramon::
	.incbin "sound/direct_sound_samples/cries/meramon.bin"

	.align 2
Cry_Numemon::
	.incbin "sound/direct_sound_samples/cries/numemon.bin"

	.align 2
Cry_Seadramon::
	.incbin "sound/direct_sound_samples/cries/seadramon.bin"
.endif @ P_FAMILY_MERAMON

.if P_FAMILY_TYRANNOMON == TRUE
	.align 2
Cry_Tyrannomon::
	.incbin "sound/direct_sound_samples/cries/tyrannomon.bin"

	.align 2
Cry_Vegiemon::
	.incbin "sound/direct_sound_samples/cries/vegiemon.bin"

	.align 2
Cry_Whamon::
	.incbin "sound/direct_sound_samples/cries/whamon.bin"
.endif @ P_FAMILY_TYRANNOMON

.if P_FAMILY_KOKATORIMON == TRUE
	.align 2
Cry_Kokatorimon::
	.incbin "sound/direct_sound_samples/cries/kokatorimon.bin"

	.align 2
Cry_Vilemon::
	.incbin "sound/direct_sound_samples/cries/vilemon.bin"

	.align 2
Cry_Roachmon::
	.incbin "sound/direct_sound_samples/cries/roachmon.bin"
.endif @ P_FAMILY_KOKATORIMON

.if P_FAMILY_GORILLAMON == TRUE
	.align 2
Cry_Gorillamon::
	.incbin "sound/direct_sound_samples/cries/gorillamon.bin"

	.align 2
Cry_Ikkakumon::
	.incbin "sound/direct_sound_samples/cries/ikkakumon.bin"
.endif @ P_FAMILY_GORILLAMON

.if P_FAMILY_KUWAGAMON == TRUE
	.align 2
Cry_Kuwagamon::
	.incbin "sound/direct_sound_samples/cries/kuwagamon.bin"

	.align 2
Cry_Leomon::
	.incbin "sound/direct_sound_samples/cries/leomon.bin"
.endif @ P_FAMILY_KUWAGAMON

.if P_FAMILY_SHADRAMON == TRUE
	.align 2
Cry_Shadramon::
	.incbin "sound/direct_sound_samples/cries/shadramon.bin"

	.align 2
Cry_Raidramon::
	.incbin "sound/direct_sound_samples/cries/raidramon.bin"

	.align 2
Cry_Togemon::
	.incbin "sound/direct_sound_samples/cries/togemon.bin"
.endif @ P_FAMILY_SHADRAMON

.if P_FAMILY_GROWLMON == TRUE
	.align 2
Cry_Growlmon::
	.incbin "sound/direct_sound_samples/cries/growlmon.bin"

	.align 2
Cry_Stingmon::
	.incbin "sound/direct_sound_samples/cries/stingmon.bin"
.endif @ P_FAMILY_GROWLMON

.if P_FAMILY_TUSKMON == TRUE
	.align 2
Cry_Tuskmon::
	.incbin "sound/direct_sound_samples/cries/tuskmon.bin"

	.align 2
Cry_Monochromon::
	.incbin "sound/direct_sound_samples/cries/monochromon.bin"
.endif @ P_FAMILY_TUSKMON

.if P_FAMILY_MEKANORIMON == TRUE
	.align 2
Cry_Burmy::
	.incbin "sound/direct_sound_samples/cries/burmy.bin"

	.align 2
Cry_Wormadam::
	.incbin "sound/direct_sound_samples/cries/nanimon.bin"

	.align 2
Cry_Mothim::
	.incbin "sound/direct_sound_samples/cries/mothim.bin"
.endif @ P_FAMILY_MEKANORIMON

.if P_FAMILY_TESLAJELLYMON == TRUE
	.align 2
Cry_Teslajellymon::
	.incbin "sound/direct_sound_samples/cries/teslajellymon.bin"

	.align 2
Cry_Raremon::
	.incbin "sound/direct_sound_samples/cries/raremon.bin"
.endif @ P_FAMILY_TESLAJELLYMON

.if P_FAMILY_SUKAMON == TRUE
	.align 2
Cry_Sukamon::
	.incbin "sound/direct_sound_samples/cries/sukamon.bin"
.endif @ P_FAMILY_SUKAMON

.if P_FAMILY_SHELLMON == TRUE
	.align 2
Cry_Shellmon::
	.incbin "sound/direct_sound_samples/cries/shellmon.bin"

	.align 2
Cry_Starmon::
	.incbin "sound/direct_sound_samples/cries/starmon.bin"
.endif @ P_FAMILY_SHELLMON

.if P_FAMILY_TORTOMON == TRUE
	.align 2
Cry_Tortomon::
	.incbin "sound/direct_sound_samples/cries/tortomon.bin"

	.align 2
Cry_Cherrim::
	.incbin "sound/direct_sound_samples/cries/unimon.bin"
.endif @ P_FAMILY_TORTOMON

.if P_FAMILY_SHELLOS == TRUE
	.align 2
Cry_Shellos::
	.incbin "sound/direct_sound_samples/cries/golemon.bin"

	.align 2
Cry_Gastrodon::
	.incbin "sound/direct_sound_samples/cries/gururumon.bin"
.endif @ P_FAMILY_SHELLOS

.if P_FAMILY_GUARDROMON == TRUE
	.align 2
Cry_Guardromon::
	.incbin "sound/direct_sound_samples/cries/guardromon.bin"

	.align 2
Cry_Honeybeemon::
	.incbin "sound/direct_sound_samples/cries/honeybeemon.bin"
.endif @ P_FAMILY_GUARDROMON

.if P_FAMILY_HYOGAMON == TRUE
	.align 2
Cry_Hyogamon::
	.incbin "sound/direct_sound_samples/cries/hyogamon.bin"

	.align 2
Cry_Icedevimon::
	.incbin "sound/direct_sound_samples/cries/icedevimon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_IcedevimonMega::
	.incbin "sound/direct_sound_samples/cries/icedevimon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_HYOGAMON

.if P_FAMILY_ICEMON == TRUE
	.align 2
Cry_Icemon::
	.incbin "sound/direct_sound_samples/cries/icemon.bin"

	.align 2
Cry_Ninjamon::
	.incbin "sound/direct_sound_samples/cries/ninjamon.bin"
.endif @ P_FAMILY_ICEMON

.if P_FAMILY_JUNGLEMOJYAMON == TRUE
	.align 2
Cry_Junglemojyamon::
	.incbin "sound/direct_sound_samples/cries/junglemojyamon.bin"

	.align 2
Cry_Shellnumemon::
	.incbin "sound/direct_sound_samples/cries/shellnumemon.bin"
.endif @ P_FAMILY_JUNGLEMOJYAMON

.if P_FAMILY_KIWIMON == TRUE
	.align 2
Cry_Kiwimon::
	.incbin "sound/direct_sound_samples/cries/kiwimon.bin"

	.align 2
Cry_Morishellmon::
	.incbin "sound/direct_sound_samples/cries/morishellmon.bin"
.endif @ P_FAMILY_KIWIMON

.if P_FAMILY_MUSYAMON == TRUE
	.align 2
Cry_Musyamon::
	.incbin "sound/direct_sound_samples/cries/musyamon.bin"
.endif @ P_FAMILY_MUSYAMON

.if P_FAMILY_NISEDRIMOGEMON == TRUE
	.align 2
Cry_Nisedrimogemon::
	.incbin "sound/direct_sound_samples/cries/nisedrimogemon.bin"
.endif @ P_FAMILY_NISEDRIMOGEMON

.if P_FAMILY_ORCAMON == TRUE
	.align 2
Cry_Orcamon::
	.incbin "sound/direct_sound_samples/cries/orcamon.bin"

	.align 2
Cry_Pidmon::
	.incbin "sound/direct_sound_samples/cries/pidmon.bin"

	.align 2
Cry_Platinumsukamon::
	.incbin "sound/direct_sound_samples/cries/platinumsukamon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_PlatinumsukamonMega::
	.incbin "sound/direct_sound_samples/cries/platinumsukamon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_ORCAMON

.if P_FAMILY_REDVEGIEMON == TRUE
	.align 2
Cry_Redvegiemon::
	.incbin "sound/direct_sound_samples/cries/redvegiemon.bin"

	.align 2
Cry_Saberdramon::
	.incbin "sound/direct_sound_samples/cries/saberdramon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_SaberdramonMega::
	.incbin "sound/direct_sound_samples/cries/saberdramon_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_REDVEGIEMON

.if P_FAMILY_SANDYANMAMON == TRUE
	.align 2
Cry_Sandyanmamon::
	.incbin "sound/direct_sound_samples/cries/sandyanmamon.bin"

	.align 2
Cry_Shimaunimon::
	.incbin "sound/direct_sound_samples/cries/shimaunimon.bin"
.endif @ P_FAMILY_SANDYANMAMON

.if P_FAMILY_SNIMON == TRUE
	.align 2
Cry_Snimon::
	.incbin "sound/direct_sound_samples/cries/snimon.bin"

	.align 2
Cry_Soulmon::
	.incbin "sound/direct_sound_samples/cries/soulmon.bin"
.endif @ P_FAMILY_SNIMON

.if P_FAMILY_TANKMON == TRUE
	.align 2
Cry_Tankmon::
	.incbin "sound/direct_sound_samples/cries/tankmon.bin"

	.align 2
Cry_Thunderballmon::
	.incbin "sound/direct_sound_samples/cries/thunderballmon.bin"
.endif @ P_FAMILY_TANKMON

.if P_FAMILY_MUDFRIGIMON == TRUE
	.align 2
Cry_Mudfrigimon::
	.incbin "sound/direct_sound_samples/cries/mudfrigimon.bin"
.endif @ P_FAMILY_MUDFRIGIMON

.if P_FAMILY_FINNEON == TRUE
	.align 2
Cry_Finneon::
	.incbin "sound/direct_sound_samples/cries/finneon.bin"

	.align 2
Cry_Lumineon::
	.incbin "sound/direct_sound_samples/cries/lumineon.bin"
.endif @ P_FAMILY_FINNEON

.if P_FAMILY_SNOVER == TRUE
	.align 2
Cry_Snover::
	.incbin "sound/direct_sound_samples/cries/snover.bin"

	.align 2
Cry_Abomasnow::
	.incbin "sound/direct_sound_samples/cries/abomasnow.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_AbomasnowMega::
	.incbin "sound/direct_sound_samples/cries/abomasnow_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_SNOVER

.if P_FAMILY_ROTOM == TRUE
	.align 2
Cry_Rotom::
	.incbin "sound/direct_sound_samples/cries/rotom.bin"
.endif @ P_FAMILY_ROTOM

.if P_FAMILY_UXIE == TRUE
	.align 2
Cry_Uxie::
	.incbin "sound/direct_sound_samples/cries/uxie.bin"
.endif @ P_FAMILY_UXIE

.if P_FAMILY_MESPRIT == TRUE
	.align 2
Cry_Mesprit::
	.incbin "sound/direct_sound_samples/cries/mesprit.bin"
.endif @ P_FAMILY_MESPRIT

.if P_FAMILY_AZELF == TRUE
	.align 2
Cry_Azelf::
	.incbin "sound/direct_sound_samples/cries/azelf.bin"
.endif @ P_FAMILY_AZELF

.if P_FAMILY_DIALGA == TRUE
	.align 2
Cry_Dialga::
	.incbin "sound/direct_sound_samples/cries/dialga.bin"
.endif @ P_FAMILY_DIALGA

.if P_FAMILY_PALKIA == TRUE
	.align 2
Cry_Palkia::
	.incbin "sound/direct_sound_samples/cries/palkia.bin"
.endif @ P_FAMILY_PALKIA

.if P_FAMILY_HEATRAN == TRUE
	.align 2
Cry_Heatran::
	.incbin "sound/direct_sound_samples/cries/heatran.bin"
.endif @ P_FAMILY_HEATRAN

.if P_FAMILY_REGIGIGAS == TRUE
	.align 2
Cry_Regigigas::
	.incbin "sound/direct_sound_samples/cries/regigigas.bin"
.endif @ P_FAMILY_REGIGIGAS

.if P_FAMILY_GIRATINA == TRUE
	.align 2
Cry_Giratina::
	.incbin "sound/direct_sound_samples/cries/giratina.bin"
.endif @ P_FAMILY_GIRATINA

.if P_FAMILY_CRESSELIA == TRUE
	.align 2
Cry_Cresselia::
	.incbin "sound/direct_sound_samples/cries/cresselia.bin"
.endif @ P_FAMILY_CRESSELIA

.if P_FAMILY_MANAPHY == TRUE
	.align 2
Cry_Phione::
	.incbin "sound/direct_sound_samples/cries/phione.bin"

	.align 2
Cry_Manaphy::
	.incbin "sound/direct_sound_samples/cries/manaphy.bin"
.endif @ P_FAMILY_MANAPHY

.if P_FAMILY_DARKRAI == TRUE
	.align 2
Cry_Darkrai::
	.incbin "sound/direct_sound_samples/cries/darkrai.bin"
.endif @ P_FAMILY_DARKRAI

.if P_FAMILY_SHAYMIN == TRUE
	.align 2
Cry_ShayminLand::
	.incbin "sound/direct_sound_samples/cries/shaymin_land.bin"

	.align 2
Cry_ShayminSky::
	.incbin "sound/direct_sound_samples/cries/shaymin_sky.bin"
.endif @ P_FAMILY_SHAYMIN

.if P_FAMILY_ARCEUS == TRUE
	.align 2
Cry_Arceus::
	.incbin "sound/direct_sound_samples/cries/arceus.bin"
.endif @ P_FAMILY_ARCEUS

.if P_FAMILY_D_AIRDRAMON == TRUE
	.align 2
Cry_D_airdramon::
	.incbin "sound/direct_sound_samples/cries/d_airdramon.bin"
.endif @ P_FAMILY_D_AIRDRAMON

.if P_FAMILY_D_DEVIMON == TRUE
	.align 2
Cry_D_devimon::
	.incbin "sound/direct_sound_samples/cries/d_devimon.bin"

	.align 2
Cry_D_meramon_cmon_digimon::
	.incbin "sound/direct_sound_samples/cries/d_meramon_cmon_digimon.bin"

	.align 2
Cry_D_metalgreymon::
	.incbin "sound/direct_sound_samples/cries/d_metalgreymon.bin"
.endif @ P_FAMILY_D_DEVIMON

.if P_FAMILY_D_TYRANNOMON == TRUE
	.align 2
Cry_D_tyrannomon::
	.incbin "sound/direct_sound_samples/cries/d_tyrannomon.bin"

	.align 2
Cry_Mamemon::
	.incbin "sound/direct_sound_samples/cries/mamemon.bin"

	.align 2
Cry_Metalgreymon_virus::
	.incbin "sound/direct_sound_samples/cries/metalgreymon_virus.bin"
.endif @ P_FAMILY_D_TYRANNOMON

.if P_FAMILY_METALMAMEMON == TRUE
	.align 2
Cry_Metalmamemon::
	.incbin "sound/direct_sound_samples/cries/metalmamemon.bin"

	.align 2
Cry_Monzaemon::
	.incbin "sound/direct_sound_samples/cries/monzaemon.bin"

	.align 2
Cry_Skullgreymon::
	.incbin "sound/direct_sound_samples/cries/skullgreymon.bin"
.endif @ P_FAMILY_METALMAMEMON

.if P_FAMILY_ANDROMON == TRUE
	.align 2
Cry_Andromon::
	.incbin "sound/direct_sound_samples/cries/andromon.bin"

	.align 2
Cry_Angewomon::
	.incbin "sound/direct_sound_samples/cries/angewomon.bin"
.endif @ P_FAMILY_ANDROMON

.if P_FAMILY_SCORPIOMON == TRUE
	.align 2
Cry_Scorpiomon::
	.incbin "sound/direct_sound_samples/cries/scorpiomon.bin"

	.align 2
Cry_Megakabuterimon_blue::
	.incbin "sound/direct_sound_samples/cries/megakabuterimon_blue.bin"

	.align 2
Cry_Dragomon::
	.incbin "sound/direct_sound_samples/cries/dragomon.bin"
.endif @ P_FAMILY_SCORPIOMON

.if P_FAMILY_DIGITAMAMON == TRUE
	.align 2
Cry_Digitamamon::
	.incbin "sound/direct_sound_samples/cries/digitamamon.bin"

	.align 2
Cry_Etemon::
	.incbin "sound/direct_sound_samples/cries/etemon.bin"
.endif @ P_FAMILY_DIGITAMAMON

.if P_FAMILY_EXTYRANNOMON == TRUE
	.align 2
Cry_Extyrannomon::
	.incbin "sound/direct_sound_samples/cries/extyrannomon.bin"

	.align 2
Cry_Giromon::
	.incbin "sound/direct_sound_samples/cries/giromon.bin"
.endif @ P_FAMILY_EXTYRANNOMON

.if P_FAMILY_MAGNAANGEMON == TRUE
	.align 2
Cry_Magnaangemon::
	.incbin "sound/direct_sound_samples/cries/magnaangemon.bin"

	.align 2
Cry_Magnaangemon_priestmode::
	.incbin "sound/direct_sound_samples/cries/magnaangemon_priestmode.bin"
.endif @ P_FAMILY_MAGNAANGEMON

.if P_FAMILY_JAGAMON == TRUE
	.align 2
Cry_Jagamon::
	.incbin "sound/direct_sound_samples/cries/jagamon.bin"

	.align 2
Cry_Ladydevimon::
	.incbin "sound/direct_sound_samples/cries/ladydevimon.bin"
.endif @ P_FAMILY_JAGAMON

.if P_FAMILY_MAMMOTHMON == TRUE
	.align 2
Cry_Mammothmon::
	.incbin "sound/direct_sound_samples/cries/mammothmon.bin"

	.align 2
Cry_Metalgreymon::
	.incbin "sound/direct_sound_samples/cries/metalgreymon.bin"
.endif @ P_FAMILY_MAMMOTHMON

.if P_FAMILY_WEREGARURUMON == TRUE
	.align 2
Cry_Weregarurumon::
	.incbin "sound/direct_sound_samples/cries/weregarurumon.bin"

	.align 2
Cry_Dinobeemon::
	.incbin "sound/direct_sound_samples/cries/dinobeemon.bin"

	.align 2
Cry_Paildramon::
	.incbin "sound/direct_sound_samples/cries/paildramon.bin"
.endif @ P_FAMILY_WEREGARURUMON

.if P_FAMILY_WARGROWLMON == TRUE
	.align 2
Cry_Wargrowlmon::
	.incbin "sound/direct_sound_samples/cries/wargrowlmon.bin"

	.align 2
Cry_Lillymon::
	.incbin "sound/direct_sound_samples/cries/lillymon.bin"
.endif @ P_FAMILY_WARGROWLMON

.if P_FAMILY_MASTERTYRANNOMON == TRUE
	.align 2
Cry_Mastertyrannomon::
	.incbin "sound/direct_sound_samples/cries/mastertyrannomon.bin"

	.align 2
Cry_Triceramon::
	.incbin "sound/direct_sound_samples/cries/triceramon.bin"

	.align 2
Cry_Arukenimon::
	.incbin "sound/direct_sound_samples/cries/arukenimon.bin"
.endif @ P_FAMILY_MASTERTYRANNOMON

.if P_FAMILY_MARINEDEVIMON == TRUE
	.align 2
Cry_Marinedevimon::
	.incbin "sound/direct_sound_samples/cries/marinedevimon.bin"

	.align 2
Cry_Megaseadramon::
	.incbin "sound/direct_sound_samples/cries/megaseadramon.bin"
.endif @ P_FAMILY_MARINEDEVIMON

.if P_FAMILY_MEGADRAMON == TRUE
	.align 2
Cry_Megadramon::
	.incbin "sound/direct_sound_samples/cries/megadramon.bin"

	.align 2
Cry_Metaltyrannomon::
	.incbin "sound/direct_sound_samples/cries/metaltyrannomon.bin"
.endif @ P_FAMILY_MEGADRAMON

.if P_FAMILY_DATAMON == TRUE
	.align 2
Cry_Datamon::
	.incbin "sound/direct_sound_samples/cries/datamon.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_Okuwamon::
	.incbin "sound/direct_sound_samples/cries/okuwamon.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_DATAMON

.if P_FAMILY_PUMPKINMON == TRUE
	.align 2
Cry_Pumpkinmon::
	.incbin "sound/direct_sound_samples/cries/pumpkinmon.bin"

	.align 2
Cry_Piximon::
	.incbin "sound/direct_sound_samples/cries/piximon.bin"

	.align 2
Cry_Shogungekomon::
	.incbin "sound/direct_sound_samples/cries/shogungekomon.bin"
.endif @ P_FAMILY_PUMPKINMON

.if P_FAMILY_ZUDOMON == TRUE
	.align 2
Cry_Zudomon::
	.incbin "sound/direct_sound_samples/cries/zudomon.bin"

	.align 2
Cry_Aeroveedramon::
	.incbin "sound/direct_sound_samples/cries/aeroveedramon.bin"

	.align 2
Cry_Asuramon::
	.incbin "sound/direct_sound_samples/cries/asuramon.bin"
.endif @ P_FAMILY_ZUDOMON

.if P_FAMILY_MEGAKABUTERIMON_RED == TRUE
	.align 2
Cry_Megakabuterimon_red::
	.incbin "sound/direct_sound_samples/cries/megakabuterimon_red.bin"
.endif @ P_FAMILY_MEGAKABUTERIMON_RED

.if P_FAMILY_BIGMAMEMON == TRUE
	.align 2
Cry_Bigmamemon::
	.incbin "sound/direct_sound_samples/cries/bigmamemon.bin"
.endif @ P_FAMILY_BIGMAMEMON

.if P_FAMILY_TINMON == TRUE
	.align 2
Cry_Tinmon::
	.incbin "sound/direct_sound_samples/cries/tinmon.bin"

	.align 2
Cry_Blossomon::
	.incbin "sound/direct_sound_samples/cries/blossomon.bin"

	.align 2
Cry_Bluemeramon::
	.incbin "sound/direct_sound_samples/cries/bluemeramon.bin"
.endif @ P_FAMILY_TINMON

.if P_FAMILY_BRACHIOMON == TRUE
	.align 2
Cry_Brachiomon::
	.incbin "sound/direct_sound_samples/cries/brachiomon.bin"

	.align 2
Cry_Kimeramon::
	.incbin "sound/direct_sound_samples/cries/kimeramon.bin"

	.align 2
Cry_Cyberdramon::
	.incbin "sound/direct_sound_samples/cries/cyberdramon.bin"
.endif @ P_FAMILY_BRACHIOMON

.if P_FAMILY_SKULLMERAMON == TRUE
	.align 2
Cry_Skullmeramon::
	.incbin "sound/direct_sound_samples/cries/skullmeramon.bin"

	.align 2
Cry_Deramon::
	.incbin "sound/direct_sound_samples/cries/deramon.bin"
.endif @ P_FAMILY_SKULLMERAMON

.if P_FAMILY_PHANTOMON == TRUE
	.align 2
Cry_Phantomon::
	.incbin "sound/direct_sound_samples/cries/phantomon.bin"

	.align 2
Cry_Garudamon::
	.incbin "sound/direct_sound_samples/cries/garudamon.bin"
.endif @ P_FAMILY_PHANTOMON

.if P_FAMILY_GIGADRAMON == TRUE
	.align 2
Cry_Gigadramon::
	.incbin "sound/direct_sound_samples/cries/gigadramon.bin"

.if P_HISUIAN_FORMS == TRUE
	.align 2
Cry_Basculegion::
	.incbin "sound/direct_sound_samples/cries/basculegion.bin"

.endif @ P_HISUIAN_FORMS
.endif @ P_FAMILY_GIGADRAMON

.if P_FAMILY_KINGSUKAMON == TRUE
	.align 2
Cry_Kingsukamon::
	.incbin "sound/direct_sound_samples/cries/kingsukamon.bin"

	.align 2
Cry_Divermon::
	.incbin "sound/direct_sound_samples/cries/divermon.bin"

	.align 2
Cry_Meteormon::
	.incbin "sound/direct_sound_samples/cries/meteormon.bin"
.endif @ P_FAMILY_KINGSUKAMON

.if P_FAMILY_CHERRYMON == TRUE
	.align 2
Cry_Cherrymon::
	.incbin "sound/direct_sound_samples/cries/cherrymon.bin"

	.align 2
Cry_Darmanitan::
	.incbin "sound/direct_sound_samples/cries/darmanitan.bin"
.endif @ P_FAMILY_CHERRYMON

.if P_FAMILY_KNIGHTMON == TRUE
	.align 2
Cry_Knightmon::
	.incbin "sound/direct_sound_samples/cries/knightmon.bin"
.endif @ P_FAMILY_KNIGHTMON

.if P_FAMILY_MUMMYMON == TRUE
	.align 2
Cry_Mummymon::
	.incbin "sound/direct_sound_samples/cries/mummymon.bin"

	.align 2
Cry_Orochimon::
	.incbin "sound/direct_sound_samples/cries/orochimon.bin"
.endif @ P_FAMILY_MUMMYMON

.if P_FAMILY_ICELEOMON == TRUE
	.align 2
Cry_Iceleomon::
	.incbin "sound/direct_sound_samples/cries/iceleomon.bin"

	.align 2
Cry_Parrotmon::
	.incbin "sound/direct_sound_samples/cries/parrotmon.bin"
.endif @ P_FAMILY_ICELEOMON

.if P_FAMILY_SKULLSATAMON == TRUE
	.align 2
Cry_Skullsatamon::
	.incbin "sound/direct_sound_samples/cries/skullsatamon.bin"
.endif @ P_FAMILY_SKULLSATAMON

.if P_FAMILY_TEKKAMON == TRUE
	.align 2
Cry_Tekkamon::
	.incbin "sound/direct_sound_samples/cries/tekkamon.bin"

	.align 2
Cry_Myotismon::
	.incbin "sound/direct_sound_samples/cries/myotismon.bin"

.if P_GALARIAN_FORMS == TRUE
	.align 2
Cry_Vermilimon::
	.incbin "sound/direct_sound_samples/cries/vermilimon.bin"

.endif @ P_GALARIAN_FORMS
.endif @ P_FAMILY_TEKKAMON

.if P_FAMILY_WARUMONZAEMON == TRUE
	.align 2
Cry_Warumonzaemon::
	.incbin "sound/direct_sound_samples/cries/warumonzaemon.bin"

	.align 2
Cry_Waruseadramon::
	.incbin "sound/direct_sound_samples/cries/waruseadramon.bin"
.endif @ P_FAMILY_WARUMONZAEMON

.if P_FAMILY_ARCHEN == TRUE
	.align 2
Cry_Archen::
	.incbin "sound/direct_sound_samples/cries/archen.bin"

	.align 2
Cry_Archeops::
	.incbin "sound/direct_sound_samples/cries/archeops.bin"
.endif @ P_FAMILY_ARCHEN

.if P_FAMILY_TRUBBISH == TRUE
	.align 2
Cry_Trubbish::
	.incbin "sound/direct_sound_samples/cries/trubbish.bin"

	.align 2
Cry_Garbodor::
	.incbin "sound/direct_sound_samples/cries/garbodor.bin"
.endif @ P_FAMILY_TRUBBISH

.if P_FAMILY_ZORUA == TRUE
	.align 2
Cry_Zorua::
	.incbin "sound/direct_sound_samples/cries/zorua.bin"

	.align 2
Cry_Zoroark::
	.incbin "sound/direct_sound_samples/cries/zoroark.bin"
.endif @ P_FAMILY_ZORUA

.if P_FAMILY_MINCCINO == TRUE
	.align 2
Cry_Minccino::
	.incbin "sound/direct_sound_samples/cries/minccino.bin"

	.align 2
Cry_Cinccino::
	.incbin "sound/direct_sound_samples/cries/cinccino.bin"
.endif @ P_FAMILY_MINCCINO

.if P_FAMILY_GOTHITA == TRUE
	.align 2
Cry_Gothita::
	.incbin "sound/direct_sound_samples/cries/gothita.bin"

	.align 2
Cry_Gothorita::
	.incbin "sound/direct_sound_samples/cries/gothorita.bin"

	.align 2
Cry_Gothitelle::
	.incbin "sound/direct_sound_samples/cries/gothitelle.bin"
.endif @ P_FAMILY_GOTHITA

.if P_FAMILY_SOLOSIS == TRUE
	.align 2
Cry_Solosis::
	.incbin "sound/direct_sound_samples/cries/solosis.bin"

	.align 2
Cry_Duosion::
	.incbin "sound/direct_sound_samples/cries/duosion.bin"

	.align 2
Cry_Reuniclus::
	.incbin "sound/direct_sound_samples/cries/reuniclus.bin"
.endif @ P_FAMILY_SOLOSIS

.if P_FAMILY_DUCKLETT == TRUE
	.align 2
Cry_Ducklett::
	.incbin "sound/direct_sound_samples/cries/ducklett.bin"

	.align 2
Cry_Swanna::
	.incbin "sound/direct_sound_samples/cries/swanna.bin"
.endif @ P_FAMILY_DUCKLETT

.if P_FAMILY_VANILLITE == TRUE
	.align 2
Cry_Vanillite::
	.incbin "sound/direct_sound_samples/cries/vanillite.bin"

	.align 2
Cry_Vanillish::
	.incbin "sound/direct_sound_samples/cries/vanillish.bin"

	.align 2
Cry_Vanilluxe::
	.incbin "sound/direct_sound_samples/cries/vanilluxe.bin"
.endif @ P_FAMILY_VANILLITE

.if P_FAMILY_DEERLING == TRUE
	.align 2
Cry_Deerling::
	.incbin "sound/direct_sound_samples/cries/deerling.bin"

	.align 2
Cry_Sawsbuck::
	.incbin "sound/direct_sound_samples/cries/sawsbuck.bin"
.endif @ P_FAMILY_DEERLING

.if P_FAMILY_EMOLGA == TRUE
	.align 2
Cry_Emolga::
	.incbin "sound/direct_sound_samples/cries/emolga.bin"
.endif @ P_FAMILY_EMOLGA

.if P_FAMILY_KARRABLAST == TRUE
	.align 2
Cry_Karrablast::
	.incbin "sound/direct_sound_samples/cries/karrablast.bin"

	.align 2
Cry_Escavalier::
	.incbin "sound/direct_sound_samples/cries/escavalier.bin"
.endif @ P_FAMILY_KARRABLAST

.if P_FAMILY_FOONGUS == TRUE
	.align 2
Cry_Foongus::
	.incbin "sound/direct_sound_samples/cries/foongus.bin"

	.align 2
Cry_Amoonguss::
	.incbin "sound/direct_sound_samples/cries/amoonguss.bin"
.endif @ P_FAMILY_FOONGUS

.if P_FAMILY_FRILLISH == TRUE
	.align 2
Cry_Frillish::
	.incbin "sound/direct_sound_samples/cries/frillish.bin"

	.align 2
Cry_Jellicent::
	.incbin "sound/direct_sound_samples/cries/jellicent.bin"
.endif @ P_FAMILY_FRILLISH

.if P_FAMILY_ALOMOMOLA == TRUE
	.align 2
Cry_Alomomola::
	.incbin "sound/direct_sound_samples/cries/alomomola.bin"
.endif @ P_FAMILY_ALOMOMOLA

.if P_FAMILY_JOLTIK == TRUE
	.align 2
Cry_Joltik::
	.incbin "sound/direct_sound_samples/cries/joltik.bin"

	.align 2
Cry_Galvantula::
	.incbin "sound/direct_sound_samples/cries/galvantula.bin"
.endif @ P_FAMILY_JOLTIK

.if P_FAMILY_FERROSEED == TRUE
	.align 2
Cry_Ferroseed::
	.incbin "sound/direct_sound_samples/cries/ferroseed.bin"

	.align 2
Cry_Ferrothorn::
	.incbin "sound/direct_sound_samples/cries/ferrothorn.bin"
.endif @ P_FAMILY_FERROSEED

.if P_FAMILY_KLINK == TRUE
	.align 2
Cry_Klink::
	.incbin "sound/direct_sound_samples/cries/klink.bin"

	.align 2
Cry_Klang::
	.incbin "sound/direct_sound_samples/cries/klang.bin"

	.align 2
Cry_Klinklang::
	.incbin "sound/direct_sound_samples/cries/klinklang.bin"
.endif @ P_FAMILY_KLINK

.if P_FAMILY_TYNAMO == TRUE
	.align 2
Cry_Tynamo::
	.incbin "sound/direct_sound_samples/cries/tynamo.bin"

	.align 2
Cry_Eelektrik::
	.incbin "sound/direct_sound_samples/cries/eelektrik.bin"

	.align 2
Cry_Eelektross::
	.incbin "sound/direct_sound_samples/cries/eelektross.bin"
.endif @ P_FAMILY_TYNAMO

.if P_FAMILY_ELGYEM == TRUE
	.align 2
Cry_Elgyem::
	.incbin "sound/direct_sound_samples/cries/elgyem.bin"

	.align 2
Cry_Beheeyem::
	.incbin "sound/direct_sound_samples/cries/beheeyem.bin"
.endif @ P_FAMILY_ELGYEM

.if P_FAMILY_LITWICK == TRUE
	.align 2
Cry_Litwick::
	.incbin "sound/direct_sound_samples/cries/litwick.bin"

	.align 2
Cry_Lampent::
	.incbin "sound/direct_sound_samples/cries/lampent.bin"

	.align 2
Cry_Chandelure::
	.incbin "sound/direct_sound_samples/cries/chandelure.bin"
.endif @ P_FAMILY_LITWICK

.if P_FAMILY_AXEW == TRUE
	.align 2
Cry_Axew::
	.incbin "sound/direct_sound_samples/cries/axew.bin"

	.align 2
Cry_Fraxure::
	.incbin "sound/direct_sound_samples/cries/fraxure.bin"

	.align 2
Cry_Haxorus::
	.incbin "sound/direct_sound_samples/cries/haxorus.bin"
.endif @ P_FAMILY_AXEW

.if P_FAMILY_CUBCHOO == TRUE
	.align 2
Cry_Cubchoo::
	.incbin "sound/direct_sound_samples/cries/cubchoo.bin"

	.align 2
Cry_Beartic::
	.incbin "sound/direct_sound_samples/cries/beartic.bin"
.endif @ P_FAMILY_CUBCHOO

.if P_FAMILY_CRYOGONAL == TRUE
	.align 2
Cry_Cryogonal::
	.incbin "sound/direct_sound_samples/cries/cryogonal.bin"
.endif @ P_FAMILY_CRYOGONAL

.if P_FAMILY_SHELMET == TRUE
	.align 2
Cry_Shelmet::
	.incbin "sound/direct_sound_samples/cries/shelmet.bin"

	.align 2
Cry_Accelgor::
	.incbin "sound/direct_sound_samples/cries/accelgor.bin"
.endif @ P_FAMILY_SHELMET

.if P_FAMILY_STUNFISK == TRUE
	.align 2
Cry_Stunfisk::
	.incbin "sound/direct_sound_samples/cries/stunfisk.bin"
.endif @ P_FAMILY_STUNFISK

.if P_FAMILY_MIENFOO == TRUE
	.align 2
Cry_Mienfoo::
	.incbin "sound/direct_sound_samples/cries/mienfoo.bin"

	.align 2
Cry_Mienshao::
	.incbin "sound/direct_sound_samples/cries/mienshao.bin"
.endif @ P_FAMILY_MIENFOO

.if P_FAMILY_DRUDDIGON == TRUE
	.align 2
Cry_Druddigon::
	.incbin "sound/direct_sound_samples/cries/druddigon.bin"
.endif @ P_FAMILY_DRUDDIGON

.if P_FAMILY_GOLETT == TRUE
	.align 2
Cry_Golett::
	.incbin "sound/direct_sound_samples/cries/golett.bin"

	.align 2
Cry_Golurk::
	.incbin "sound/direct_sound_samples/cries/golurk.bin"
.endif @ P_FAMILY_GOLETT

.if P_FAMILY_PAWNIARD == TRUE
	.align 2
Cry_Pawniard::
	.incbin "sound/direct_sound_samples/cries/pawniard.bin"

	.align 2
Cry_Bisharp::
	.incbin "sound/direct_sound_samples/cries/bisharp.bin"

.if P_GEN_9_CROSS_EVOS == TRUE
	.align 2
Cry_Kingambit::
	.incbin "sound/direct_sound_samples/cries/kingambit.bin"
.endif @ P_GEN_9_CROSS_EVOS
.endif @ P_FAMILY_PAWNIARD

.if P_FAMILY_BOUFFALANT == TRUE
	.align 2
Cry_Bouffalant::
	.incbin "sound/direct_sound_samples/cries/bouffalant.bin"
.endif @ P_FAMILY_BOUFFALANT

.if P_FAMILY_RUFFLET == TRUE
	.align 2
Cry_Rufflet::
	.incbin "sound/direct_sound_samples/cries/rufflet.bin"

	.align 2
Cry_Braviary::
	.incbin "sound/direct_sound_samples/cries/braviary.bin"
.endif @ P_FAMILY_RUFFLET

.if P_FAMILY_VULLABY == TRUE
	.align 2
Cry_Vullaby::
	.incbin "sound/direct_sound_samples/cries/vullaby.bin"

	.align 2
Cry_Mandibuzz::
	.incbin "sound/direct_sound_samples/cries/mandibuzz.bin"
.endif @ P_FAMILY_VULLABY

.if P_FAMILY_HEATMOR == TRUE
	.align 2
Cry_Heatmor::
	.incbin "sound/direct_sound_samples/cries/heatmor.bin"
.endif @ P_FAMILY_HEATMOR

.if P_FAMILY_DURANT == TRUE
	.align 2
Cry_Durant::
	.incbin "sound/direct_sound_samples/cries/durant.bin"
.endif @ P_FAMILY_DURANT

.if P_FAMILY_DEINO == TRUE
	.align 2
Cry_Deino::
	.incbin "sound/direct_sound_samples/cries/deino.bin"

	.align 2
Cry_Zweilous::
	.incbin "sound/direct_sound_samples/cries/zweilous.bin"

	.align 2
Cry_Hydreigon::
	.incbin "sound/direct_sound_samples/cries/hydreigon.bin"
.endif @ P_FAMILY_DEINO

.if P_FAMILY_LARVESTA == TRUE
	.align 2
Cry_Larvesta::
	.incbin "sound/direct_sound_samples/cries/larvesta.bin"

	.align 2
Cry_Volcarona::
	.incbin "sound/direct_sound_samples/cries/volcarona.bin"
.endif @ P_FAMILY_LARVESTA

.if P_FAMILY_COBALION == TRUE
	.align 2
Cry_Cobalion::
	.incbin "sound/direct_sound_samples/cries/cobalion.bin"
.endif @ P_FAMILY_COBALION

.if P_FAMILY_TERRAKION == TRUE
	.align 2
Cry_Terrakion::
	.incbin "sound/direct_sound_samples/cries/terrakion.bin"
.endif @ P_FAMILY_TERRAKION

.if P_FAMILY_VIRIZION == TRUE
	.align 2
Cry_Virizion::
	.incbin "sound/direct_sound_samples/cries/virizion.bin"
.endif @ P_FAMILY_VIRIZION

.if P_FAMILY_TORNADUS == TRUE
	.align 2
Cry_TornadusIncarnate::
	.incbin "sound/direct_sound_samples/cries/tornadus_incarnate.bin"

	.align 2
Cry_TornadusTherian::
	.incbin "sound/direct_sound_samples/cries/tornadus_therian.bin"
.endif @ P_FAMILY_TORNADUS

.if P_FAMILY_THUNDURUS == TRUE
	.align 2
Cry_ThundurusIncarnate::
	.incbin "sound/direct_sound_samples/cries/thundurus_incarnate.bin"

	.align 2
Cry_ThundurusTherian::
	.incbin "sound/direct_sound_samples/cries/thundurus_therian.bin"
.endif @ P_FAMILY_THUNDURUS

.if P_FAMILY_RESHIRAM == TRUE
	.align 2
Cry_Reshiram::
	.incbin "sound/direct_sound_samples/cries/reshiram.bin"
.endif @ P_FAMILY_RESHIRAM

.if P_FAMILY_ZEKROM == TRUE
	.align 2
Cry_Zekrom::
	.incbin "sound/direct_sound_samples/cries/zekrom.bin"
.endif @ P_FAMILY_ZEKROM

.if P_FAMILY_LANDORUS == TRUE
	.align 2
Cry_LandorusIncarnate::
	.incbin "sound/direct_sound_samples/cries/landorus_incarnate.bin"

	.align 2
Cry_LandorusTherian::
	.incbin "sound/direct_sound_samples/cries/landorus_therian.bin"
.endif @ P_FAMILY_LANDORUS

.if P_FAMILY_KYUREM == TRUE
	.align 2
Cry_Kyurem::
	.incbin "sound/direct_sound_samples/cries/kyurem.bin"

.if P_FUSION_FORMS == TRUE
	.align 2
Cry_KyuremWhite::
	.incbin "sound/direct_sound_samples/cries/kyurem_white.bin"

	.align 2
Cry_KyuremBlack::
	.incbin "sound/direct_sound_samples/cries/kyurem_black.bin"

.endif @ P_FUSION_FORMS
.endif @ P_FAMILY_KYUREM

.if P_FAMILY_KELDEO == TRUE
	.align 2
Cry_Keldeo::
	.incbin "sound/direct_sound_samples/cries/keldeo.bin"
.endif @ P_FAMILY_KELDEO

.if P_FAMILY_MELOETTA == TRUE
	.align 2
Cry_Meloetta::
	.incbin "sound/direct_sound_samples/cries/meloetta.bin"
.endif @ P_FAMILY_MELOETTA

.if P_FAMILY_GENESECT == TRUE
	.align 2
Cry_Genesect::
	.incbin "sound/direct_sound_samples/cries/genesect.bin"
.endif @ P_FAMILY_GENESECT

.if P_FAMILY_HERCULESKABUTERIMON == TRUE
	.align 2
Cry_Herculeskabuterimon::
	.incbin "sound/direct_sound_samples/cries/herculeskabuterimon.bin"

	.align 2
Cry_Magnadramon::
	.incbin "sound/direct_sound_samples/cries/magnadramon.bin"

	.align 2
Cry_Magnamon::
	.incbin "sound/direct_sound_samples/cries/magnamon.bin"
.endif @ P_FAMILY_HERCULESKABUTERIMON

.if P_FAMILY_WARGREYMON == TRUE
	.align 2
Cry_Wargreymon::
	.incbin "sound/direct_sound_samples/cries/wargreymon.bin"

	.align 2
Cry_Metalgarurumon::
	.incbin "sound/direct_sound_samples/cries/metalgarurumon.bin"

	.align 2
Cry_Omnimon::
	.incbin "sound/direct_sound_samples/cries/omnimon.bin"
.endif @ P_FAMILY_WARGREYMON

.if P_FAMILY_CRESGARURUMON == TRUE
	.align 2
Cry_Cresgarurumon::
	.incbin "sound/direct_sound_samples/cries/cresgarurumon.bin"

	.align 2
Cry_Blitzgreymon::
	.incbin "sound/direct_sound_samples/cries/blitzgreymon.bin"

	.align 2
Cry_Biosupinomon::
	.incbin "sound/direct_sound_samples/cries/biosupinomon.bin"
.endif @ P_FAMILY_CRESGARURUMON

.if P_FAMILY_ROSEMON == TRUE
	.align 2
Cry_Rosemon::
	.incbin "sound/direct_sound_samples/cries/rosemon.bin"

	.align 2
Cry_Dinorexmon::
	.incbin "sound/direct_sound_samples/cries/dinorexmon.bin"
.endif @ P_FAMILY_ROSEMON

.if P_FAMILY_DINOMON == TRUE
	.align 2
Cry_Dinomon::
	.incbin "sound/direct_sound_samples/cries/dinomon.bin"

	.align 2
Cry_Marineangemon::
	.incbin "sound/direct_sound_samples/cries/marineangemon.bin"

	.align 2
Cry_Metaletemon::
	.incbin "sound/direct_sound_samples/cries/metaletemon.bin"
.endif @ P_FAMILY_DINOMON

.if P_FAMILY_METALSEADRAMON == TRUE
	.align 2
Cry_Metalseadramon::
	.incbin "sound/direct_sound_samples/cries/metalseadramon.bin"

	.align 2
Cry_Pukumon::
	.incbin "sound/direct_sound_samples/cries/pukumon.bin"

	.align 2
Cry_Saberleomon::
	.incbin "sound/direct_sound_samples/cries/saberleomon.bin"
.endif @ P_FAMILY_METALSEADRAMON

.if P_FAMILY_APOCALYMON == TRUE
	.align 2
Cry_Apocalymon::
	.incbin "sound/direct_sound_samples/cries/apocalymon.bin"

	.align 2
Cry_Babamon::
	.incbin "sound/direct_sound_samples/cries/babamon.bin"
.endif @ P_FAMILY_APOCALYMON

.if P_FAMILY_FLABEBE == TRUE
	.align 2
Cry_Flabebe::
	.incbin "sound/direct_sound_samples/cries/flabebe.bin"

	.align 2
Cry_Floette::
	.incbin "sound/direct_sound_samples/cries/floette.bin"

	.align 2
Cry_FloetteEternal::
	.incbin "sound/direct_sound_samples/cries/floette_eternal.bin"

	.align 2
Cry_Florges::
	.incbin "sound/direct_sound_samples/cries/florges.bin"
.endif @ P_FAMILY_FLABEBE

.if P_FAMILY_BOLTMON == TRUE
	.align 2
Cry_Boltmon::
	.incbin "sound/direct_sound_samples/cries/boltmon.bin"

	.align 2
Cry_Creepymon::
	.incbin "sound/direct_sound_samples/cries/creepymon.bin"
.endif @ P_FAMILY_BOLTMON

.if P_FAMILY_DEVITAMAMON == TRUE
	.align 2
Cry_Devitamamon::
	.incbin "sound/direct_sound_samples/cries/devitamamon.bin"

	.align 2
Cry_Diaboromon::
	.incbin "sound/direct_sound_samples/cries/diaboromon.bin"
.endif @ P_FAMILY_DEVITAMAMON

.if P_FAMILY_FURFROU == TRUE
	.align 2
Cry_Furfrou::
	.incbin "sound/direct_sound_samples/cries/furfrou.bin"
.endif @ P_FAMILY_FURFROU

.if P_FAMILY_GOLDRAMON == TRUE
	.align 2
Cry_Goldramon::
	.incbin "sound/direct_sound_samples/cries/goldramon.bin"

	.align 2
.endif @ P_FAMILY_GOLDRAMON

.if P_FAMILY_PHOENIXMON == TRUE
	.align 2
Cry_Phoenixmon::
	.incbin "sound/direct_sound_samples/cries/phoenixmon.bin"

	.align 2
Cry_Jijimon::
	.incbin "sound/direct_sound_samples/cries/jijimon.bin"

	.align 2
Cry_Aegislash::
	.incbin "sound/direct_sound_samples/cries/aegislash.bin"
.endif @ P_FAMILY_PHOENIXMON

.if P_FAMILY_KINGETEMON == TRUE
	.align 2
Cry_Kingetemon::
	.incbin "sound/direct_sound_samples/cries/kingetemon.bin"

	.align 2
Cry_Millenniummon::
	.incbin "sound/direct_sound_samples/cries/millenniummon.bin"
.endif @ P_FAMILY_KINGETEMON

.if P_FAMILY_MACHINEDRAMON == TRUE
	.align 2
Cry_Machinedramon::
	.incbin "sound/direct_sound_samples/cries/machinedramon.bin"

	.align 2
Cry_Piedmon::
	.incbin "sound/direct_sound_samples/cries/piedmon.bin"
.endif @ P_FAMILY_MACHINEDRAMON

.if P_FAMILY_PUPPETMON == TRUE
	.align 2
Cry_Puppetmon::
	.incbin "sound/direct_sound_samples/cries/puppetmon.bin"

	.align 2
Cry_Plesiomon::
	.incbin "sound/direct_sound_samples/cries/plesiomon.bin"
.endif @ P_FAMILY_PUPPETMON

.if P_FAMILY_SKULLMAMMOTHMON == TRUE
	.align 2
Cry_Skullmammothmon::
	.incbin "sound/direct_sound_samples/cries/skullmammothmon.bin"

	.align 2
Cry_Venommyotismon::
	.incbin "sound/direct_sound_samples/cries/venommyotismon.bin"
.endif @ P_FAMILY_SKULLMAMMOTHMON

.if P_FAMILY_SKRELP == TRUE
	.align 2
Cry_Skrelp::
	.incbin "sound/direct_sound_samples/cries/skrelp.bin"

	.align 2
Cry_Dragalge::
	.incbin "sound/direct_sound_samples/cries/dragalge.bin"
.endif @ P_FAMILY_SKRELP

.if P_FAMILY_CLAUNCHER == TRUE
	.align 2
Cry_Clauncher::
	.incbin "sound/direct_sound_samples/cries/clauncher.bin"

	.align 2
Cry_Clawitzer::
	.incbin "sound/direct_sound_samples/cries/clawitzer.bin"
.endif @ P_FAMILY_CLAUNCHER

.if P_FAMILY_HELIOPTILE == TRUE
	.align 2
Cry_Helioptile::
	.incbin "sound/direct_sound_samples/cries/helioptile.bin"

	.align 2
Cry_Heliolisk::
	.incbin "sound/direct_sound_samples/cries/heliolisk.bin"
.endif @ P_FAMILY_HELIOPTILE

.if P_FAMILY_TYRUNT == TRUE
	.align 2
Cry_Tyrunt::
	.incbin "sound/direct_sound_samples/cries/tyrunt.bin"

	.align 2
Cry_Tyrantrum::
	.incbin "sound/direct_sound_samples/cries/tyrantrum.bin"
.endif @ P_FAMILY_TYRUNT

.if P_FAMILY_AMAURA == TRUE
	.align 2
Cry_Amaura::
	.incbin "sound/direct_sound_samples/cries/amaura.bin"

	.align 2
Cry_Aurorus::
	.incbin "sound/direct_sound_samples/cries/aurorus.bin"
.endif @ P_FAMILY_AMAURA

.if P_FAMILY_HAWLUCHA == TRUE
	.align 2
Cry_Hawlucha::
	.incbin "sound/direct_sound_samples/cries/hawlucha.bin"
.endif @ P_FAMILY_HAWLUCHA

.if P_FAMILY_DEDENNE == TRUE
	.align 2
Cry_Dedenne::
	.incbin "sound/direct_sound_samples/cries/dedenne.bin"
.endif @ P_FAMILY_DEDENNE

.if P_FAMILY_CARBINK == TRUE
	.align 2
Cry_Carbink::
	.incbin "sound/direct_sound_samples/cries/carbink.bin"
.endif @ P_FAMILY_CARBINK

.if P_FAMILY_GOOMY == TRUE
	.align 2
Cry_Goomy::
	.incbin "sound/direct_sound_samples/cries/goomy.bin"

	.align 2
Cry_Sliggoo::
	.incbin "sound/direct_sound_samples/cries/sliggoo.bin"

	.align 2
Cry_Goodra::
	.incbin "sound/direct_sound_samples/cries/goodra.bin"
.endif @ P_FAMILY_GOOMY

.if P_FAMILY_KLEFKI == TRUE
	.align 2
Cry_Klefki::
	.incbin "sound/direct_sound_samples/cries/uncomp_klefki.bin"
.endif @ P_FAMILY_KLEFKI

.if P_FAMILY_PHANTUMP == TRUE
	.align 2
Cry_Phantump::
	.incbin "sound/direct_sound_samples/cries/phantump.bin"

	.align 2
Cry_Trevenant::
	.incbin "sound/direct_sound_samples/cries/trevenant.bin"
.endif @ P_FAMILY_PHANTUMP

.if P_FAMILY_PUMPKABOO == TRUE
	.align 2
Cry_Pumpkaboo::
	.incbin "sound/direct_sound_samples/cries/pumpkaboo.bin"

	.align 2
Cry_PumpkabooSuper::
	.incbin "sound/direct_sound_samples/cries/pumpkaboo_super.bin"

	.align 2
Cry_Gourgeist::
	.incbin "sound/direct_sound_samples/cries/gourgeist.bin"

	.align 2
Cry_GourgeistSuper::
	.incbin "sound/direct_sound_samples/cries/gourgeist_super.bin"
.endif @ P_FAMILY_PUMPKABOO

.if P_FAMILY_BERGMITE == TRUE
	.align 2
Cry_Bergmite::
	.incbin "sound/direct_sound_samples/cries/bergmite.bin"

	.align 2
Cry_Avalugg::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"
.endif @ P_FAMILY_BERGMITE

.if P_FAMILY_NOIBAT == TRUE
	.align 2
Cry_Noibat::
	.incbin "sound/direct_sound_samples/cries/noibat.bin"

	.align 2
Cry_Noivern::
	.incbin "sound/direct_sound_samples/cries/noivern.bin"
.endif @ P_FAMILY_NOIBAT

.if P_FAMILY_XERNEAS == TRUE
	.align 2
Cry_Xerneas::
	.incbin "sound/direct_sound_samples/cries/xerneas.bin"
.endif @ P_FAMILY_XERNEAS

.if P_FAMILY_YVELTAL == TRUE
	.align 2
Cry_Yveltal::
	.incbin "sound/direct_sound_samples/cries/yveltal.bin"
.endif @ P_FAMILY_YVELTAL

.if P_FAMILY_ZYGARDE == TRUE
	.align 2
Cry_Zygarde50::
	.incbin "sound/direct_sound_samples/cries/zygarde_50.bin"

	.align 2
Cry_Zygarde10::
	.incbin "sound/direct_sound_samples/cries/zygarde_10.bin"

	.align 2
Cry_ZygardeComplete::
	.incbin "sound/direct_sound_samples/cries/zygarde_complete.bin"
.endif @ P_FAMILY_ZYGARDE

.if P_FAMILY_DIANCIE == TRUE
	.align 2
Cry_Diancie::
	.incbin "sound/direct_sound_samples/cries/diancie.bin"

.if P_MEGA_EVOLUTIONS == TRUE
	.align 2
Cry_DiancieMega::
	.incbin "sound/direct_sound_samples/cries/diancie_mega.bin"
.endif @ P_MEGA_EVOLUTIONS
.endif @ P_FAMILY_DIANCIE

.if P_FAMILY_HOOPA == TRUE
	.align 2
Cry_HoopaConfined::
	.incbin "sound/direct_sound_samples/cries/hoopa_confined.bin"

	.align 2
Cry_HoopaUnbound::
	.incbin "sound/direct_sound_samples/cries/hoopa_unbound.bin"
.endif @ P_FAMILY_HOOPA

.if P_FAMILY_VOLCANION == TRUE
	.align 2
Cry_Volcanion::
	.incbin "sound/direct_sound_samples/cries/volcanion.bin"
.endif @ P_FAMILY_VOLCANION

.if P_FAMILY_ROWLET == TRUE
	.align 2
Cry_Rowlet::
	.incbin "sound/direct_sound_samples/cries/rowlet.bin"

	.align 2
Cry_Dartrix::
	.incbin "sound/direct_sound_samples/cries/dartrix.bin"

	.align 2
Cry_Decidueye::
	.incbin "sound/direct_sound_samples/cries/decidueye.bin"
.endif @ P_FAMILY_ROWLET

.if P_FAMILY_LITTEN == TRUE
	.align 2
Cry_Litten::
	.incbin "sound/direct_sound_samples/cries/litten.bin"

	.align 2
Cry_Torracat::
	.incbin "sound/direct_sound_samples/cries/torracat.bin"

	.align 2
Cry_Incineroar::
	.incbin "sound/direct_sound_samples/cries/incineroar.bin"
.endif @ P_FAMILY_LITTEN

.if P_FAMILY_POPPLIO == TRUE
	.align 2
Cry_Popplio::
	.incbin "sound/direct_sound_samples/cries/popplio.bin"

	.align 2
Cry_Brionne::
	.incbin "sound/direct_sound_samples/cries/brionne.bin"

	.align 2
Cry_Primarina::
	.incbin "sound/direct_sound_samples/cries/primarina.bin"
.endif @ P_FAMILY_POPPLIO

.if P_FAMILY_PIKIPEK == TRUE
	.align 2
Cry_Pikipek::
	.incbin "sound/direct_sound_samples/cries/pikipek.bin"

	.align 2
Cry_Trumbeak::
	.incbin "sound/direct_sound_samples/cries/trumbeak.bin"

	.align 2
Cry_Toucannon::
	.incbin "sound/direct_sound_samples/cries/toucannon.bin"
.endif @ P_FAMILY_PIKIPEK

.if P_FAMILY_YUNGOOS == TRUE
	.align 2
Cry_Yungoos::
	.incbin "sound/direct_sound_samples/cries/yungoos.bin"

	.align 2
Cry_Gumshoos::
	.incbin "sound/direct_sound_samples/cries/gumshoos.bin"
.endif @ P_FAMILY_YUNGOOS

.if P_FAMILY_GRUBBIN == TRUE
	.align 2
Cry_Grubbin::
	.incbin "sound/direct_sound_samples/cries/grubbin.bin"

	.align 2
Cry_Charjabug::
	.incbin "sound/direct_sound_samples/cries/charjabug.bin"

	.align 2
Cry_Vikavolt::
	.incbin "sound/direct_sound_samples/cries/vikavolt.bin"
.endif @ P_FAMILY_GRUBBIN

.if P_FAMILY_CRABRAWLER == TRUE
	.align 2
Cry_Crabrawler::
	.incbin "sound/direct_sound_samples/cries/crabrawler.bin"

	.align 2
Cry_Crabominable::
	.incbin "sound/direct_sound_samples/cries/crabominable.bin"
.endif @ P_FAMILY_CRABRAWLER

.if P_FAMILY_ORICORIO == TRUE
	.align 2
Cry_OricorioBaile::
	.incbin "sound/direct_sound_samples/cries/oricorio_baile.bin"

	.align 2
Cry_OricorioPomPom::
	.incbin "sound/direct_sound_samples/cries/uncomp_oricorio_pom_pom.bin"

	.align 2
Cry_OricorioPau::
	.incbin "sound/direct_sound_samples/cries/oricorio_pau.bin"

	.align 2
Cry_OricorioSensu::
	.incbin "sound/direct_sound_samples/cries/oricorio_sensu.bin"
.endif @ P_FAMILY_ORICORIO

.if P_FAMILY_CUTIEFLY == TRUE
	.align 2
Cry_Cutiefly::
	.incbin "sound/direct_sound_samples/cries/cutiefly.bin"

	.align 2
Cry_Ribombee::
	.incbin "sound/direct_sound_samples/cries/ribombee.bin"
.endif @ P_FAMILY_CUTIEFLY

.if P_FAMILY_ROCKRUFF == TRUE
	.align 2
Cry_Rockruff::
	.incbin "sound/direct_sound_samples/cries/rockruff.bin"

	.align 2
Cry_LycanrocMidday::
	.incbin "sound/direct_sound_samples/cries/lycanroc_midday.bin"

	.align 2
Cry_LycanrocMidnight::
	.incbin "sound/direct_sound_samples/cries/lycanroc_midnight.bin"

	.align 2
Cry_LycanrocDusk::
	.incbin "sound/direct_sound_samples/cries/lycanroc_dusk.bin"
.endif @ P_FAMILY_ROCKRUFF

.if P_FAMILY_WISHIWASHI == TRUE
	.align 2
Cry_WishiwashiSolo::
	.incbin "sound/direct_sound_samples/cries/wishiwashi_solo.bin"

	.align 2
Cry_WishiwashiSchool::
	.incbin "sound/direct_sound_samples/cries/wishiwashi_school.bin"
.endif @ P_FAMILY_WISHIWASHI

.if P_FAMILY_MAREANIE == TRUE
	.align 2
Cry_Mareanie::
	.incbin "sound/direct_sound_samples/cries/mareanie.bin"

	.align 2
Cry_Toxapex::
	.incbin "sound/direct_sound_samples/cries/toxapex.bin"
.endif @ P_FAMILY_MAREANIE

.if P_FAMILY_MUDBRAY == TRUE
	.align 2
Cry_Mudbray::
	.incbin "sound/direct_sound_samples/cries/mudbray.bin"

	.align 2
Cry_Mudsdale::
	.incbin "sound/direct_sound_samples/cries/mudsdale.bin"
.endif @ P_FAMILY_MUDBRAY

.if P_FAMILY_DEWPIDER == TRUE
	.align 2
Cry_Dewpider::
	.incbin "sound/direct_sound_samples/cries/dewpider.bin"

	.align 2
Cry_Araquanid::
	.incbin "sound/direct_sound_samples/cries/araquanid.bin"
.endif @ P_FAMILY_DEWPIDER

.if P_FAMILY_FOMANTIS == TRUE
	.align 2
Cry_Fomantis::
	.incbin "sound/direct_sound_samples/cries/fomantis.bin"

	.align 2
Cry_Lurantis::
	.incbin "sound/direct_sound_samples/cries/lurantis.bin"
.endif @ P_FAMILY_FOMANTIS

.if P_FAMILY_MORELULL == TRUE
	.align 2
Cry_Morelull::
	.incbin "sound/direct_sound_samples/cries/morelull.bin"

	.align 2
Cry_Shiinotic::
	.incbin "sound/direct_sound_samples/cries/shiinotic.bin"
.endif @ P_FAMILY_MORELULL

.if P_FAMILY_SALANDIT == TRUE
	.align 2
Cry_Salandit::
	.incbin "sound/direct_sound_samples/cries/salandit.bin"

	.align 2
Cry_Salazzle::
	.incbin "sound/direct_sound_samples/cries/salazzle.bin"
.endif @ P_FAMILY_SALANDIT

.if P_FAMILY_STUFFUL == TRUE
	.align 2
Cry_Stufful::
	.incbin "sound/direct_sound_samples/cries/stufful.bin"

	.align 2
Cry_Bewear::
	.incbin "sound/direct_sound_samples/cries/bewear.bin"
.endif @ P_FAMILY_STUFFUL

.if P_FAMILY_BOUNSWEET == TRUE
	.align 2
Cry_Bounsweet::
	.incbin "sound/direct_sound_samples/cries/bounsweet.bin"

	.align 2
Cry_Steenee::
	.incbin "sound/direct_sound_samples/cries/steenee.bin"

	.align 2
Cry_Tsareena::
	.incbin "sound/direct_sound_samples/cries/tsareena.bin"
.endif @ P_FAMILY_BOUNSWEET

.if P_FAMILY_COMFEY == TRUE
	.align 2
Cry_Comfey::
	.incbin "sound/direct_sound_samples/cries/comfey.bin"
.endif @ P_FAMILY_COMFEY

.if P_FAMILY_ORANGURU == TRUE
	.align 2
Cry_Oranguru::
	.incbin "sound/direct_sound_samples/cries/oranguru.bin"
.endif @ P_FAMILY_ORANGURU

.if P_FAMILY_PASSIMIAN == TRUE
	.align 2
Cry_Passimian::
	.incbin "sound/direct_sound_samples/cries/passimian.bin"
.endif @ P_FAMILY_PASSIMIAN

.if P_FAMILY_WIMPOD == TRUE
	.align 2
Cry_Wimpod::
	.incbin "sound/direct_sound_samples/cries/wimpod.bin"

	.align 2
Cry_Golisopod::
	.incbin "sound/direct_sound_samples/cries/golisopod.bin"
.endif @ P_FAMILY_WIMPOD

.if P_FAMILY_SANDYGAST == TRUE
	.align 2
Cry_Sandygast::
	.incbin "sound/direct_sound_samples/cries/sandygast.bin"

	.align 2
Cry_Palossand::
	.incbin "sound/direct_sound_samples/cries/palossand.bin"
.endif @ P_FAMILY_SANDYGAST

.if P_FAMILY_PYUKUMUKU == TRUE
	.align 2
Cry_Pyukumuku::
	.incbin "sound/direct_sound_samples/cries/pyukumuku.bin"
.endif @ P_FAMILY_PYUKUMUKU

.if P_FAMILY_TYPE_NULL == TRUE
	.align 2
Cry_TypeNull::
	.incbin "sound/direct_sound_samples/cries/type_null.bin"

	.align 2
Cry_Silvally::
	.incbin "sound/direct_sound_samples/cries/silvally.bin"
.endif @ P_FAMILY_TYPE_NULL

.if P_FAMILY_MINIOR == TRUE
	.align 2
Cry_Minior::
	.incbin "sound/direct_sound_samples/cries/minior.bin"
.endif @ P_FAMILY_MINIOR

.if P_FAMILY_KOMALA == TRUE
	.align 2
Cry_Komala::
	.incbin "sound/direct_sound_samples/cries/komala.bin"
.endif @ P_FAMILY_KOMALA

.if P_FAMILY_TURTONATOR == TRUE
	.align 2
Cry_Turtonator::
	.incbin "sound/direct_sound_samples/cries/turtonator.bin"
.endif @ P_FAMILY_TURTONATOR

.if P_FAMILY_TOGEDEMARU == TRUE
	.align 2
Cry_Togedemaru::
	.incbin "sound/direct_sound_samples/cries/togedemaru.bin"
.endif @ P_FAMILY_TOGEDEMARU

.if P_FAMILY_MIMIKYU == TRUE
	.align 2
Cry_Mimikyu::
	.incbin "sound/direct_sound_samples/cries/mimikyu.bin"
.endif @ P_FAMILY_MIMIKYU

.if P_FAMILY_BRUXISH == TRUE
	.align 2
Cry_Bruxish::
	.incbin "sound/direct_sound_samples/cries/bruxish.bin"
.endif @ P_FAMILY_BRUXISH

.if P_FAMILY_DRAMPA == TRUE
	.align 2
Cry_Drampa::
	.incbin "sound/direct_sound_samples/cries/drampa.bin"
.endif @ P_FAMILY_DRAMPA

.if P_FAMILY_DHELMISE == TRUE
	.align 2
Cry_Dhelmise::
	.incbin "sound/direct_sound_samples/cries/dhelmise.bin"
.endif @ P_FAMILY_DHELMISE

.if P_FAMILY_JANGMO_O == TRUE
	.align 2
Cry_JangmoO::
	.incbin "sound/direct_sound_samples/cries/jangmo_o.bin"

	.align 2
Cry_HakamoO::
	.incbin "sound/direct_sound_samples/cries/hakamo_o.bin"

	.align 2
Cry_KommoO::
	.incbin "sound/direct_sound_samples/cries/kommo_o.bin"
.endif @ P_FAMILY_JANGMO_O

.if P_FAMILY_TAPU_KOKO == TRUE
	.align 2
Cry_TapuKoko::
	.incbin "sound/direct_sound_samples/cries/tapu_koko.bin"
.endif @ P_FAMILY_TAPU_KOKO

.if P_FAMILY_TAPU_LELE == TRUE
	.align 2
Cry_TapuLele::
	.incbin "sound/direct_sound_samples/cries/tapu_lele.bin"
.endif @ P_FAMILY_TAPU_LELE

.if P_FAMILY_TAPU_BULU == TRUE
	.align 2
Cry_TapuBulu::
	.incbin "sound/direct_sound_samples/cries/tapu_bulu.bin"
.endif @ P_FAMILY_TAPU_BULU

.if P_FAMILY_TAPU_FINI == TRUE
	.align 2
Cry_TapuFini::
	.incbin "sound/direct_sound_samples/cries/tapu_fini.bin"
.endif @ P_FAMILY_TAPU_FINI

.if P_FAMILY_COSMOG == TRUE
	.align 2
Cry_Cosmog::
	.incbin "sound/direct_sound_samples/cries/cosmog.bin"

	.align 2
Cry_Cosmoem::
	.incbin "sound/direct_sound_samples/cries/cosmoem.bin"

	.align 2
Cry_Solgaleo::
	.incbin "sound/direct_sound_samples/cries/solgaleo.bin"

	.align 2
Cry_Lunala::
	.incbin "sound/direct_sound_samples/cries/lunala.bin"
.endif @ P_FAMILY_COSMOG

.if P_FAMILY_NIHILEGO == TRUE
	.align 2
Cry_Nihilego::
	.incbin "sound/direct_sound_samples/cries/nihilego.bin"
.endif @ P_FAMILY_NIHILEGO

.if P_FAMILY_BUZZWOLE == TRUE
	.align 2
Cry_Buzzwole::
	.incbin "sound/direct_sound_samples/cries/buzzwole.bin"
.endif @ P_FAMILY_BUZZWOLE

.if P_FAMILY_PHEROMOSA == TRUE
	.align 2
Cry_Pheromosa::
	.incbin "sound/direct_sound_samples/cries/pheromosa.bin"
.endif @ P_FAMILY_PHEROMOSA

.if P_FAMILY_XURKITREE == TRUE
	.align 2
Cry_Xurkitree::
	.incbin "sound/direct_sound_samples/cries/xurkitree.bin"
.endif @ P_FAMILY_XURKITREE

.if P_FAMILY_CELESTEELA == TRUE
	.align 2
Cry_Celesteela::
	.incbin "sound/direct_sound_samples/cries/celesteela.bin"
.endif @ P_FAMILY_CELESTEELA

.if P_FAMILY_KARTANA == TRUE
	.align 2
Cry_Kartana::
	.incbin "sound/direct_sound_samples/cries/kartana.bin"
.endif @ P_FAMILY_KARTANA

.if P_FAMILY_GUZZLORD == TRUE
	.align 2
Cry_Guzzlord::
	.incbin "sound/direct_sound_samples/cries/guzzlord.bin"
.endif @ P_FAMILY_GUZZLORD

.if P_FAMILY_NECROZMA == TRUE
	.align 2
Cry_Necrozma::
	.incbin "sound/direct_sound_samples/cries/necrozma.bin"

.if P_FUSION_FORMS == TRUE
	.align 2
Cry_NecrozmaDuskMane::
	.incbin "sound/direct_sound_samples/cries/necrozma_dusk_mane.bin"

	.align 2
Cry_NecrozmaDawnWings::
	.incbin "sound/direct_sound_samples/cries/necrozma_dawn_wings.bin"

.if P_ULTRA_BURST_FORMS == TRUE
	.align 2
Cry_NecrozmaUltra::
	.incbin "sound/direct_sound_samples/cries/necrozma_ultra.bin"

.endif @ P_ULTRA_BURST_FORMS
.endif @ P_FUSION_FORMS
.endif @ P_FAMILY_NECROZMA

.if P_FAMILY_MAGEARNA == TRUE
	.align 2
Cry_Magearna::
	.incbin "sound/direct_sound_samples/cries/magearna.bin"
.endif @ P_FAMILY_MAGEARNA

.if P_FAMILY_MARSHADOW == TRUE
	.align 2
Cry_Marshadow::
	.incbin "sound/direct_sound_samples/cries/marshadow.bin"
.endif @ P_FAMILY_MARSHADOW

.if P_FAMILY_POIPOLE == TRUE
	.align 2
Cry_Poipole::
	.incbin "sound/direct_sound_samples/cries/poipole.bin"

	.align 2
Cry_Naganadel::
	.incbin "sound/direct_sound_samples/cries/naganadel.bin"
.endif @ P_FAMILY_POIPOLE

.if P_FAMILY_STAKATAKA == TRUE
	.align 2
Cry_Stakataka::
	.incbin "sound/direct_sound_samples/cries/stakataka.bin"
.endif @ P_FAMILY_STAKATAKA

.if P_FAMILY_BLACEPHALON == TRUE
	.align 2
Cry_Blacephalon::
	.incbin "sound/direct_sound_samples/cries/blacephalon.bin"
.endif @ P_FAMILY_BLACEPHALON

.if P_FAMILY_ZERAORA == TRUE
	.align 2
Cry_Zeraora::
	.incbin "sound/direct_sound_samples/cries/zeraora.bin"
.endif @ P_FAMILY_ZERAORA

.if P_FAMILY_MELTAN == TRUE
	.align 2
Cry_Meltan::
	.incbin "sound/direct_sound_samples/cries/meltan.bin"

	.align 2
Cry_Melmetal::
	.incbin "sound/direct_sound_samples/cries/melmetal.bin"
.endif @ P_FAMILY_MELTAN

.if P_FAMILY_TOMORIMON == TRUE
	.align 2
Cry_Tomorimon::
	.incbin "sound/direct_sound_samples/cries/tomorimon.bin"

	.align 2
Cry_Onibimon::
	.incbin "sound/direct_sound_samples/cries/onibimon.bin"

	.align 2
Cry_Rillaboom::
	.incbin "sound/direct_sound_samples/cries/rillaboom.bin"
.endif @ P_FAMILY_TOMORIMON

.if P_FAMILY_SCORBUNNY == TRUE
	.align 2
Cry_Scorbunny::
	.incbin "sound/direct_sound_samples/cries/scorbunny.bin"

	.align 2
Cry_Raboot::
	.incbin "sound/direct_sound_samples/cries/raboot.bin"

	.align 2
Cry_Cinderace::
	.incbin "sound/direct_sound_samples/cries/cinderace.bin"
.endif @ P_FAMILY_SCORBUNNY

.if P_FAMILY_SOBBLE == TRUE
	.align 2
Cry_Sobble::
	.incbin "sound/direct_sound_samples/cries/sobble.bin"

	.align 2
Cry_Drizzile::
	.incbin "sound/direct_sound_samples/cries/drizzile.bin"

	.align 2
Cry_Inteleon::
	.incbin "sound/direct_sound_samples/cries/inteleon.bin"
.endif @ P_FAMILY_SOBBLE

.if P_FAMILY_SKWOVET == TRUE
	.align 2
Cry_Skwovet::
	.incbin "sound/direct_sound_samples/cries/skwovet.bin"

	.align 2
Cry_Greedent::
	.incbin "sound/direct_sound_samples/cries/greedent.bin"
.endif @ P_FAMILY_SKWOVET

.if P_FAMILY_ROOKIDEE == TRUE
	.align 2
Cry_Rookidee::
	.incbin "sound/direct_sound_samples/cries/rookidee.bin"

	.align 2
Cry_Corvisquire::
	.incbin "sound/direct_sound_samples/cries/corvisquire.bin"

	.align 2
Cry_Corviknight::
	.incbin "sound/direct_sound_samples/cries/corviknight.bin"
.endif @ P_FAMILY_ROOKIDEE

.if P_FAMILY_BLIPBUG == TRUE
	.align 2
Cry_Blipbug::
	.incbin "sound/direct_sound_samples/cries/blipbug.bin"

	.align 2
Cry_Dottler::
	.incbin "sound/direct_sound_samples/cries/dottler.bin"

	.align 2
Cry_Orbeetle::
	.incbin "sound/direct_sound_samples/cries/orbeetle.bin"
.endif @ P_FAMILY_BLIPBUG

.if P_FAMILY_NICKIT == TRUE
	.align 2
Cry_Nickit::
	.incbin "sound/direct_sound_samples/cries/nickit.bin"

	.align 2
Cry_Thievul::
	.incbin "sound/direct_sound_samples/cries/thievul.bin"
.endif @ P_FAMILY_NICKIT

.if P_FAMILY_GOSSIFLEUR == TRUE
	.align 2
Cry_Gossifleur::
	.incbin "sound/direct_sound_samples/cries/gossifleur.bin"

	.align 2
Cry_Eldegoss::
	.incbin "sound/direct_sound_samples/cries/eldegoss.bin"
.endif @ P_FAMILY_GOSSIFLEUR

.if P_FAMILY_WOOLOO == TRUE
	.align 2
Cry_Wooloo::
	.incbin "sound/direct_sound_samples/cries/wooloo.bin"

	.align 2
Cry_Dubwool::
	.incbin "sound/direct_sound_samples/cries/dubwool.bin"
.endif @ P_FAMILY_WOOLOO

.if P_FAMILY_CHEWTLE == TRUE
	.align 2
Cry_Chewtle::
	.incbin "sound/direct_sound_samples/cries/chewtle.bin"

	.align 2
Cry_Drednaw::
	.incbin "sound/direct_sound_samples/cries/drednaw.bin"
.endif @ P_FAMILY_CHEWTLE

.if P_FAMILY_YAMPER == TRUE
	.align 2
Cry_Yamper::
	.incbin "sound/direct_sound_samples/cries/yamper.bin"

	.align 2
Cry_Boltund::
	.incbin "sound/direct_sound_samples/cries/boltund.bin"
.endif @ P_FAMILY_YAMPER

.if P_FAMILY_ROLYCOLY == TRUE
	.align 2
Cry_Rolycoly::
	.incbin "sound/direct_sound_samples/cries/rolycoly.bin"

	.align 2
Cry_Carkol::
	.incbin "sound/direct_sound_samples/cries/carkol.bin"

	.align 2
Cry_Coalossal::
	.incbin "sound/direct_sound_samples/cries/coalossal.bin"
.endif @ P_FAMILY_ROLYCOLY

.if P_FAMILY_APPLIN == TRUE
	.align 2
Cry_Applin::
	.incbin "sound/direct_sound_samples/cries/applin.bin"

	.align 2
Cry_Flapple::
	.incbin "sound/direct_sound_samples/cries/flapple.bin"

	.align 2
Cry_Appletun::
	.incbin "sound/direct_sound_samples/cries/appletun.bin"

.if P_GEN_9_CROSS_EVOS == TRUE
	.align 2
Cry_Dipplin::
	.incbin "sound/direct_sound_samples/cries/dipplin.bin"

	.align 2
Cry_Hydrapple::
	.incbin "sound/direct_sound_samples/cries/hydrapple.bin"
.endif @ P_GEN_9_CROSS_EVOS
.endif @ P_FAMILY_APPLIN

.if P_FAMILY_SILICOBRA == TRUE
	.align 2
Cry_Silicobra::
	.incbin "sound/direct_sound_samples/cries/silicobra.bin"

	.align 2
Cry_Sandaconda::
	.incbin "sound/direct_sound_samples/cries/sandaconda.bin"
.endif @ P_FAMILY_SILICOBRA

.if P_FAMILY_CRAMORANT == TRUE
	.align 2
Cry_Cramorant::
	.incbin "sound/direct_sound_samples/cries/cramorant.bin"
.endif @ P_FAMILY_CRAMORANT

.if P_FAMILY_ARROKUDA == TRUE
	.align 2
Cry_Arrokuda::
	.incbin "sound/direct_sound_samples/cries/arrokuda.bin"

	.align 2
Cry_Barraskewda::
	.incbin "sound/direct_sound_samples/cries/barraskewda.bin"
.endif @ P_FAMILY_ARROKUDA

.if P_FAMILY_TOXEL == TRUE
	.align 2
Cry_Toxel::
	.incbin "sound/direct_sound_samples/cries/toxel.bin"

	.align 2
Cry_ToxtricityAmped::
	.incbin "sound/direct_sound_samples/cries/toxtricity_amped.bin"

	.align 2
Cry_ToxtricityLowKey::
	.incbin "sound/direct_sound_samples/cries/toxtricity_low_key.bin"
.endif @ P_FAMILY_TOXEL

.if P_FAMILY_SIZZLIPEDE == TRUE
	.align 2
Cry_Sizzlipede::
	.incbin "sound/direct_sound_samples/cries/sizzlipede.bin"

	.align 2
Cry_Centiskorch::
	.incbin "sound/direct_sound_samples/cries/centiskorch.bin"
.endif @ P_FAMILY_SIZZLIPEDE

.if P_FAMILY_CLOBBOPUS == TRUE
	.align 2
Cry_Clobbopus::
	.incbin "sound/direct_sound_samples/cries/clobbopus.bin"

	.align 2
Cry_Grapploct::
	.incbin "sound/direct_sound_samples/cries/grapploct.bin"
.endif @ P_FAMILY_CLOBBOPUS

.if P_FAMILY_SINISTEA == TRUE
	.align 2
Cry_Sinistea::
	.incbin "sound/direct_sound_samples/cries/sinistea.bin"

	.align 2
Cry_Polteageist::
	.incbin "sound/direct_sound_samples/cries/polteageist.bin"
.endif @ P_FAMILY_SINISTEA

.if P_FAMILY_HATENNA == TRUE
	.align 2
Cry_Hatenna::
	.incbin "sound/direct_sound_samples/cries/hatenna.bin"

	.align 2
Cry_Hattrem::
	.incbin "sound/direct_sound_samples/cries/hattrem.bin"

	.align 2
Cry_Hatterene::
	.incbin "sound/direct_sound_samples/cries/hatterene.bin"
.endif @ P_FAMILY_HATENNA

.if P_FAMILY_IMPIDIMP == TRUE
	.align 2
Cry_Impidimp::
	.incbin "sound/direct_sound_samples/cries/impidimp.bin"

	.align 2
Cry_Morgrem::
	.incbin "sound/direct_sound_samples/cries/morgrem.bin"

	.align 2
Cry_Grimmsnarl::
	.incbin "sound/direct_sound_samples/cries/grimmsnarl.bin"
.endif @ P_FAMILY_IMPIDIMP

.if P_FAMILY_MILCERY == TRUE
	.align 2
Cry_Milcery::
	.incbin "sound/direct_sound_samples/cries/milcery.bin"

	.align 2
Cry_Alcremie::
	.incbin "sound/direct_sound_samples/cries/alcremie.bin"
.endif @ P_FAMILY_MILCERY

.if P_FAMILY_FALINKS == TRUE
	.align 2
Cry_Falinks::
	.incbin "sound/direct_sound_samples/cries/falinks.bin"
.endif @ P_FAMILY_FALINKS

.if P_FAMILY_PINCURCHIN == TRUE
	.align 2
Cry_Pincurchin::
	.incbin "sound/direct_sound_samples/cries/pincurchin.bin"
.endif @ P_FAMILY_PINCURCHIN

.if P_FAMILY_SNOM == TRUE
	.align 2
Cry_Snom::
	.incbin "sound/direct_sound_samples/cries/snom.bin"

	.align 2
Cry_Frosmoth::
	.incbin "sound/direct_sound_samples/cries/frosmoth.bin"
.endif @ P_FAMILY_SNOM

.if P_FAMILY_STONJOURNER == TRUE
	.align 2
Cry_Stonjourner::
	.incbin "sound/direct_sound_samples/cries/stonjourner.bin"
.endif @ P_FAMILY_STONJOURNER

.if P_FAMILY_EISCUE == TRUE
	.align 2
Cry_EiscueIce::
	.incbin "sound/direct_sound_samples/cries/eiscue_ice_face.bin"

	.align 2
Cry_EiscueNoice::
	.incbin "sound/direct_sound_samples/cries/eiscue_noice_face.bin"
.endif @ P_FAMILY_EISCUE

.if P_FAMILY_INDEEDEE == TRUE
	.align 2
Cry_IndeedeeM::
	.incbin "sound/direct_sound_samples/cries/indeedee_male.bin"

	.align 2
Cry_IndeedeeF::
	.incbin "sound/direct_sound_samples/cries/indeedee_female.bin"
.endif @ P_FAMILY_INDEEDEE

.if P_FAMILY_MORPEKO == TRUE
	.align 2
Cry_MorpekoFullBelly::
	.incbin "sound/direct_sound_samples/cries/morpeko_full_belly.bin"

	.align 2
Cry_MorpekoHangry::
	.incbin "sound/direct_sound_samples/cries/morpeko_hangry.bin"
.endif @ P_FAMILY_MORPEKO

.if P_FAMILY_CUFANT == TRUE
	.align 2
Cry_Cufant::
	.incbin "sound/direct_sound_samples/cries/cufant.bin"

	.align 2
Cry_Copperajah::
	.incbin "sound/direct_sound_samples/cries/copperajah.bin"
.endif @ P_FAMILY_CUFANT

.if P_FAMILY_DRACOZOLT == TRUE
	.align 2
Cry_Dracozolt::
	.incbin "sound/direct_sound_samples/cries/dracozolt.bin"
.endif @ P_FAMILY_DRACOZOLT

.if P_FAMILY_ARCTOZOLT == TRUE
	.align 2
Cry_Arctozolt::
	.incbin "sound/direct_sound_samples/cries/arctozolt.bin"
.endif @ P_FAMILY_ARCTOZOLT

.if P_FAMILY_DRACOVISH == TRUE
	.align 2
Cry_Dracovish::
	.incbin "sound/direct_sound_samples/cries/dracovish.bin"
.endif @ P_FAMILY_DRACOVISH

.if P_FAMILY_ARCTOVISH == TRUE
	.align 2
Cry_Arctovish::
	.incbin "sound/direct_sound_samples/cries/arctovish.bin"
.endif @ P_FAMILY_ARCTOVISH

.if P_FAMILY_DURALUDON == TRUE
	.align 2
Cry_Duraludon::
	.incbin "sound/direct_sound_samples/cries/duraludon.bin"

	.align 2
Cry_Archaludon::
	.incbin "sound/direct_sound_samples/cries/archaludon.bin"
.endif @ P_FAMILY_DURALUDON

.if P_FAMILY_DREEPY == TRUE
	.align 2
Cry_Dreepy::
	.incbin "sound/direct_sound_samples/cries/dreepy.bin"

	.align 2
Cry_Drakloak::
	.incbin "sound/direct_sound_samples/cries/drakloak.bin"

	.align 2
Cry_Dragapult::
	.incbin "sound/direct_sound_samples/cries/dragapult.bin"
.endif @ P_FAMILY_DREEPY

.if P_FAMILY_ZACIAN == TRUE
	.align 2
Cry_ZacianHero::
	.incbin "sound/direct_sound_samples/cries/zacian_hero_of_many_battles.bin"

	.align 2
Cry_ZacianCrowned::
	.incbin "sound/direct_sound_samples/cries/zacian_crowned_sword.bin"
.endif @ P_FAMILY_ZACIAN

.if P_FAMILY_ZAMAZENTA == TRUE
	.align 2
Cry_ZamazentaHero::
	.incbin "sound/direct_sound_samples/cries/zamazenta_hero_of_many_battles.bin"

	.align 2
Cry_ZamazentaCrowned::
	.incbin "sound/direct_sound_samples/cries/zamazenta_crowned_shield.bin"
.endif @ P_FAMILY_ZAMAZENTA

.if P_FAMILY_ETERNATUS == TRUE
	.align 2
Cry_Eternatus::
	.incbin "sound/direct_sound_samples/cries/eternatus.bin"

	.align 2
Cry_EternatusEternamax::
	.incbin "sound/direct_sound_samples/cries/eternatus_eternamax.bin"
.endif @ P_FAMILY_ETERNATUS

.if P_FAMILY_KUBFU == TRUE
	.align 2
Cry_Kubfu::
	.incbin "sound/direct_sound_samples/cries/kubfu.bin"

	.align 2
Cry_UrshifuSingleStrike::
	.incbin "sound/direct_sound_samples/cries/urshifu_single_strike.bin"

	.align 2
Cry_UrshifuRapidStrike::
	.incbin "sound/direct_sound_samples/cries/urshifu_rapid_strike.bin"
.endif @ P_FAMILY_KUBFU

.if P_FAMILY_ZARUDE == TRUE
	.align 2
Cry_Zarude::
	.incbin "sound/direct_sound_samples/cries/zarude.bin"
.endif @ P_FAMILY_ZARUDE

.if P_FAMILY_REGIELEKI == TRUE
	.align 2
Cry_Regieleki::
	.incbin "sound/direct_sound_samples/cries/regieleki.bin"
.endif @ P_FAMILY_REGIELEKI

.if P_FAMILY_REGIDRAGO == TRUE
	.align 2
Cry_Regidrago::
	.incbin "sound/direct_sound_samples/cries/regidrago.bin"
.endif @ P_FAMILY_REGIDRAGO

.if P_FAMILY_GLASTRIER == TRUE
	.align 2
Cry_Glastrier::
	.incbin "sound/direct_sound_samples/cries/glastrier.bin"
.endif @ P_FAMILY_GLASTRIER

.if P_FAMILY_SPECTRIER == TRUE
	.align 2
Cry_Spectrier::
	.incbin "sound/direct_sound_samples/cries/spectrier.bin"
.endif @ P_FAMILY_SPECTRIER

.if P_FAMILY_CALYREX == TRUE
	.align 2
Cry_Calyrex::
	.incbin "sound/direct_sound_samples/cries/calyrex.bin"

.if P_FUSION_FORMS == TRUE
	.align 2
Cry_CalyrexIce::
	.incbin "sound/direct_sound_samples/cries/calyrex_ice.bin"

	.align 2
Cry_CalyrexShadow::
	.incbin "sound/direct_sound_samples/cries/calyrex_shadow.bin"

.endif @ P_FUSION_FORMS
.endif @ P_FAMILY_CALYREX

.if P_FAMILY_ENAMORUS == TRUE
	.align 2
Cry_EnamorusIncarnate::
	.incbin "sound/direct_sound_samples/cries/enamorus_incarnate.bin"

	.align 2
Cry_EnamorusTherian::
	.incbin "sound/direct_sound_samples/cries/enamorus_therian.bin"
.endif @ P_FAMILY_ENAMORUS

.if P_FAMILY_SPRIGATITO == TRUE
	.align 2
Cry_Sprigatito::
	.incbin "sound/direct_sound_samples/cries/sprigatito.bin"

	.align 2
Cry_Floragato::
	.incbin "sound/direct_sound_samples/cries/floragato.bin"

	.align 2
Cry_Meowscarada::
	.incbin "sound/direct_sound_samples/cries/meowscarada.bin"
.endif @ P_FAMILY_SPRIGATITO

.if P_FAMILY_FUECOCO == TRUE
	.align 2
Cry_Fuecoco::
	.incbin "sound/direct_sound_samples/cries/fuecoco.bin"

	.align 2
Cry_Crocalor::
	.incbin "sound/direct_sound_samples/cries/crocalor.bin"

	.align 2
Cry_Skeledirge::
	.incbin "sound/direct_sound_samples/cries/skeledirge.bin"
.endif @ P_FAMILY_FUECOCO

.if P_FAMILY_QUAXLY == TRUE
	.align 2
Cry_Quaxly::
	.incbin "sound/direct_sound_samples/cries/quaxly.bin"

	.align 2
Cry_Quaxwell::
	.incbin "sound/direct_sound_samples/cries/quaxwell.bin"

	.align 2
Cry_Quaquaval::
	.incbin "sound/direct_sound_samples/cries/quaquaval.bin"
.endif @ P_FAMILY_QUAXLY

.if P_FAMILY_LECHONK == TRUE
	.align 2
Cry_Lechonk::
	.incbin "sound/direct_sound_samples/cries/lechonk.bin"

	.align 2
Cry_OinkologneM::
	.incbin "sound/direct_sound_samples/cries/oinkologne_m.bin"

	.align 2
Cry_OinkologneF::
	.incbin "sound/direct_sound_samples/cries/oinkologne_f.bin"
.endif @ P_FAMILY_LECHONK

.if P_FAMILY_TAROUNTULA == TRUE
	.align 2
Cry_Tarountula::
	.incbin "sound/direct_sound_samples/cries/tarountula.bin"

	.align 2
Cry_Spidops::
	.incbin "sound/direct_sound_samples/cries/spidops.bin"
.endif @ P_FAMILY_TAROUNTULA

.if P_FAMILY_NYMBLE == TRUE
	.align 2
Cry_Nymble::
	.incbin "sound/direct_sound_samples/cries/nymble.bin"

	.align 2
Cry_Lokix::
	.incbin "sound/direct_sound_samples/cries/lokix.bin"
.endif @ P_FAMILY_NYMBLE

.if P_FAMILY_PAWMI == TRUE
	.align 2
Cry_Pawmi::
	.incbin "sound/direct_sound_samples/cries/pawmi.bin"

	.align 2
Cry_Pawmo::
	.incbin "sound/direct_sound_samples/cries/pawmo.bin"

	.align 2
Cry_Pawmot::
	.incbin "sound/direct_sound_samples/cries/pawmot.bin"
.endif @ P_FAMILY_PAWMI

.if P_FAMILY_TANDEMAUS == TRUE
	.align 2
Cry_Tandemaus::
	.incbin "sound/direct_sound_samples/cries/tandemaus.bin"

	.align 2
Cry_MausholdThree::
	.incbin "sound/direct_sound_samples/cries/maushold_three.bin"

	.align 2
Cry_MausholdFour::
	.incbin "sound/direct_sound_samples/cries/maushold_four.bin"
.endif @ P_FAMILY_TANDEMAUS

.if P_FAMILY_FIDOUGH == TRUE
	.align 2
Cry_Fidough::
	.incbin "sound/direct_sound_samples/cries/fidough.bin"

	.align 2
Cry_Dachsbun::
	.incbin "sound/direct_sound_samples/cries/dachsbun.bin"
.endif @ P_FAMILY_FIDOUGH

.if P_FAMILY_SMOLIV == TRUE
	.align 2
Cry_Smoliv::
	.incbin "sound/direct_sound_samples/cries/smoliv.bin"

	.align 2
Cry_Dolliv::
	.incbin "sound/direct_sound_samples/cries/dolliv.bin"

	.align 2
Cry_Arboliva::
	.incbin "sound/direct_sound_samples/cries/arboliva.bin"
.endif @ P_FAMILY_SMOLIV

.if P_FAMILY_SQUAWKABILLY == TRUE
	.align 2
Cry_Squawkabilly::
	.incbin "sound/direct_sound_samples/cries/squawkabilly.bin"
.endif @ P_FAMILY_SQUAWKABILLY

.if P_FAMILY_NACLI == TRUE
	.align 2
Cry_Nacli::
	.incbin "sound/direct_sound_samples/cries/nacli.bin"

	.align 2
Cry_Naclstack::
	.incbin "sound/direct_sound_samples/cries/naclstack.bin"

	.align 2
Cry_Garganacl::
	.incbin "sound/direct_sound_samples/cries/garganacl.bin"
.endif @ P_FAMILY_NACLI

.if P_FAMILY_CHARCADET == TRUE
	.align 2
Cry_Charcadet::
	.incbin "sound/direct_sound_samples/cries/charcadet.bin"

	.align 2
Cry_Armarouge::
	.incbin "sound/direct_sound_samples/cries/armarouge.bin"

	.align 2
Cry_Ceruledge::
	.incbin "sound/direct_sound_samples/cries/ceruledge.bin"
.endif @ P_FAMILY_CHARCADET

.if P_FAMILY_TADBULB == TRUE
	.align 2
Cry_Tadbulb::
	.incbin "sound/direct_sound_samples/cries/tadbulb.bin"

	.align 2
Cry_Bellibolt::
	.incbin "sound/direct_sound_samples/cries/bellibolt.bin"
.endif @ P_FAMILY_TADBULB

.if P_FAMILY_WATTREL == TRUE
	.align 2
Cry_Wattrel::
	.incbin "sound/direct_sound_samples/cries/wattrel.bin"

	.align 2
Cry_Kilowattrel::
	.incbin "sound/direct_sound_samples/cries/kilowattrel.bin"
.endif @ P_FAMILY_WATTREL

.if P_FAMILY_MASCHIFF == TRUE
	.align 2
Cry_Maschiff::
	.incbin "sound/direct_sound_samples/cries/maschiff.bin"

	.align 2
Cry_Mabosstiff::
	.incbin "sound/direct_sound_samples/cries/mabosstiff.bin"
.endif @ P_FAMILY_MASCHIFF

.if P_FAMILY_SHROODLE == TRUE
	.align 2
Cry_Shroodle::
	.incbin "sound/direct_sound_samples/cries/shroodle.bin"

	.align 2
Cry_Grafaiai::
	.incbin "sound/direct_sound_samples/cries/grafaiai.bin"
.endif @ P_FAMILY_SHROODLE

.if P_FAMILY_BRAMBLIN == TRUE
	.align 2
Cry_Bramblin::
	.incbin "sound/direct_sound_samples/cries/bramblin.bin"

	.align 2
Cry_Brambleghast::
	.incbin "sound/direct_sound_samples/cries/brambleghast.bin"
.endif @ P_FAMILY_BRAMBLIN

.if P_FAMILY_TOEDSCOOL == TRUE
	.align 2
Cry_Toedscool::
	.incbin "sound/direct_sound_samples/cries/toedscool.bin"

	.align 2
Cry_Toedscruel::
	.incbin "sound/direct_sound_samples/cries/toedscruel.bin"
.endif @ P_FAMILY_TOEDSCOOL

.if P_FAMILY_KLAWF == TRUE
	.align 2
Cry_Klawf::
	.incbin "sound/direct_sound_samples/cries/klawf.bin"
.endif @ P_FAMILY_KLAWF

.if P_FAMILY_CAPSAKID == TRUE
	.align 2
Cry_Capsakid::
	.incbin "sound/direct_sound_samples/cries/capsakid.bin"

	.align 2
Cry_Scovillain::
	.incbin "sound/direct_sound_samples/cries/scovillain.bin"
.endif @ P_FAMILY_CAPSAKID

.if P_FAMILY_RELLOR == TRUE
	.align 2
Cry_Rellor::
	.incbin "sound/direct_sound_samples/cries/rellor.bin"

	.align 2
Cry_Rabsca::
	.incbin "sound/direct_sound_samples/cries/rabsca.bin"
.endif @ P_FAMILY_RELLOR

.if P_FAMILY_FLITTLE == TRUE
	.align 2
Cry_Flittle::
	.incbin "sound/direct_sound_samples/cries/flittle.bin"

	.align 2
Cry_Espathra::
	.incbin "sound/direct_sound_samples/cries/espathra.bin"
.endif @ P_FAMILY_FLITTLE

.if P_FAMILY_TINKATINK == TRUE
	.align 2
Cry_Tinkatink::
	.incbin "sound/direct_sound_samples/cries/tinkatink.bin"

	.align 2
Cry_Tinkatuff::
	.incbin "sound/direct_sound_samples/cries/tinkatuff.bin"

	.align 2
Cry_Tinkaton::
	.incbin "sound/direct_sound_samples/cries/tinkaton.bin"
.endif @ P_FAMILY_TINKATINK

.if P_FAMILY_WIGLETT == TRUE
	.align 2
Cry_Wiglett::
	.incbin "sound/direct_sound_samples/cries/wiglett.bin"

	.align 2
Cry_Wugtrio::
	.incbin "sound/direct_sound_samples/cries/wugtrio.bin"
.endif @ P_FAMILY_WIGLETT

.if P_FAMILY_BOMBIRDIER == TRUE
	.align 2
Cry_Bombirdier::
	.incbin "sound/direct_sound_samples/cries/bombirdier.bin"
.endif @ P_FAMILY_BOMBIRDIER

.if P_FAMILY_FINIZEN == TRUE
	.align 2
Cry_Finizen::
	.incbin "sound/direct_sound_samples/cries/finizen.bin"

	.align 2
Cry_PalafinZero::
	.incbin "sound/direct_sound_samples/cries/palafin_zero.bin"

	.align 2
Cry_PalafinHero::
	.incbin "sound/direct_sound_samples/cries/palafin_hero.bin"
.endif @ P_FAMILY_FINIZEN

.if P_FAMILY_VAROOM == TRUE
	.align 2
Cry_Varoom::
	.incbin "sound/direct_sound_samples/cries/varoom.bin"

	.align 2
Cry_Revavroom::
	.incbin "sound/direct_sound_samples/cries/revavroom.bin"
.endif @ P_FAMILY_VAROOM

.if P_FAMILY_CYCLIZAR == TRUE
	.align 2
Cry_Cyclizar::
	.incbin "sound/direct_sound_samples/cries/cyclizar.bin"
.endif @ P_FAMILY_CYCLIZAR

.if P_FAMILY_ORTHWORM == TRUE
	.align 2
Cry_Orthworm::
	.incbin "sound/direct_sound_samples/cries/orthworm.bin"
.endif @ P_FAMILY_ORTHWORM

.if P_FAMILY_GLIMMET == TRUE
	.align 2
Cry_Glimmet::
	.incbin "sound/direct_sound_samples/cries/glimmet.bin"

	.align 2
Cry_Glimmora::
	.incbin "sound/direct_sound_samples/cries/glimmora.bin"
.endif @ P_FAMILY_GLIMMET

.if P_FAMILY_GREAVARD == TRUE
	.align 2
Cry_Greavard::
	.incbin "sound/direct_sound_samples/cries/greavard.bin"

	.align 2
Cry_Houndstone::
	.incbin "sound/direct_sound_samples/cries/houndstone.bin"
.endif @ P_FAMILY_GREAVARD

.if P_FAMILY_FLAMIGO == TRUE
	.align 2
Cry_Flamigo::
	.incbin "sound/direct_sound_samples/cries/flamigo.bin"
.endif @ P_FAMILY_FLAMIGO

.if P_FAMILY_CETODDLE == TRUE
	.align 2
Cry_Cetoddle::
	.incbin "sound/direct_sound_samples/cries/cetoddle.bin"

	.align 2
Cry_Cetitan::
	.incbin "sound/direct_sound_samples/cries/cetitan.bin"
.endif @ P_FAMILY_CETODDLE

.if P_FAMILY_VELUZA == TRUE
	.align 2
Cry_Veluza::
	.incbin "sound/direct_sound_samples/cries/veluza.bin"
.endif @ P_FAMILY_VELUZA

.if P_FAMILY_DONDOZO == TRUE
	.align 2
Cry_Dondozo::
	.incbin "sound/direct_sound_samples/cries/dondozo.bin"
.endif @ P_FAMILY_DONDOZO

.if P_FAMILY_TATSUGIRI == TRUE
	.align 2
Cry_TatsugiriCurly::
	.incbin "sound/direct_sound_samples/cries/tatsugiri_curly.bin"

	.align 2
Cry_TatsugiriDroopy::
	.incbin "sound/direct_sound_samples/cries/tatsugiri_droopy.bin"

	.align 2
Cry_TatsugiriStretchy::
	.incbin "sound/direct_sound_samples/cries/tatsugiri_stretchy.bin"
.endif @ P_FAMILY_TATSUGIRI

.if P_FAMILY_GREAT_TUSK == TRUE
	.align 2
Cry_GreatTusk::
	.incbin "sound/direct_sound_samples/cries/great_tusk.bin"
.endif @ P_FAMILY_GREAT_TUSK

.if P_FAMILY_SCREAM_TAIL == TRUE
	.align 2
Cry_ScreamTail::
	.incbin "sound/direct_sound_samples/cries/scream_tail.bin"
.endif @ P_FAMILY_SCREAM_TAIL

.if P_FAMILY_BRUTE_BONNET == TRUE
	.align 2
Cry_BruteBonnet::
	.incbin "sound/direct_sound_samples/cries/brute_bonnet.bin"
.endif @ P_FAMILY_BRUTE_BONNET

.if P_FAMILY_FLUTTER_MANE == TRUE
	.align 2
Cry_FlutterMane::
	.incbin "sound/direct_sound_samples/cries/flutter_mane.bin"
.endif @ P_FAMILY_FLUTTER_MANE

.if P_FAMILY_SLITHER_WING == TRUE
	.align 2
Cry_SlitherWing::
	.incbin "sound/direct_sound_samples/cries/slither_wing.bin"
.endif @ P_FAMILY_SLITHER_WING

.if P_FAMILY_SANDY_SHOCKS == TRUE
	.align 2
Cry_SandyShocks::
	.incbin "sound/direct_sound_samples/cries/sandy_shocks.bin"
.endif @ P_FAMILY_SANDY_SHOCKS

.if P_FAMILY_IRON_TREADS == TRUE
	.align 2
Cry_IronTreads::
	.incbin "sound/direct_sound_samples/cries/iron_treads.bin"
.endif @ P_FAMILY_IRON_TREADS

.if P_FAMILY_IRON_BUNDLE == TRUE
	.align 2
Cry_IronBundle::
	.incbin "sound/direct_sound_samples/cries/iron_bundle.bin"
.endif @ P_FAMILY_IRON_BUNDLE

.if P_FAMILY_IRON_HANDS == TRUE
	.align 2
Cry_IronHands::
	.incbin "sound/direct_sound_samples/cries/iron_hands.bin"
.endif @ P_FAMILY_IRON_HANDS

.if P_FAMILY_IRON_JUGULIS == TRUE
	.align 2
Cry_IronJugulis::
	.incbin "sound/direct_sound_samples/cries/iron_jugulis.bin"
.endif @ P_FAMILY_IRON_JUGULIS

.if P_FAMILY_IRON_MOTH == TRUE
	.align 2
Cry_IronMoth::
	.incbin "sound/direct_sound_samples/cries/iron_moth.bin"
.endif @ P_FAMILY_IRON_MOTH

.if P_FAMILY_IRON_THORNS == TRUE
	.align 2
Cry_IronThorns::
	.incbin "sound/direct_sound_samples/cries/iron_thorns.bin"
.endif @ P_FAMILY_IRON_THORNS

.if P_FAMILY_FRIGIBAX == TRUE
	.align 2
Cry_Frigibax::
	.incbin "sound/direct_sound_samples/cries/frigibax.bin"

	.align 2
Cry_Arctibax::
	.incbin "sound/direct_sound_samples/cries/arctibax.bin"

	.align 2
Cry_Baxcalibur::
	.incbin "sound/direct_sound_samples/cries/baxcalibur.bin"
.endif @ P_FAMILY_FRIGIBAX

.if P_FAMILY_GIMMIGHOUL == TRUE
	.align 2
Cry_Gimmighoul::
	.incbin "sound/direct_sound_samples/cries/gimmighoul.bin"

	.align 2
Cry_Gholdengo::
	.incbin "sound/direct_sound_samples/cries/gholdengo.bin"
.endif @ P_FAMILY_GIMMIGHOUL

.if P_FAMILY_WO_CHIEN == TRUE
	.align 2
Cry_WoChien::
	.incbin "sound/direct_sound_samples/cries/wo_chien.bin"
.endif @ P_FAMILY_WO_CHIEN

.if P_FAMILY_CHIEN_PAO == TRUE
	.align 2
Cry_ChienPao::
	.incbin "sound/direct_sound_samples/cries/chien_pao.bin"
.endif @ P_FAMILY_CHIEN_PAO

.if P_FAMILY_TING_LU == TRUE
	.align 2
Cry_TingLu::
	.incbin "sound/direct_sound_samples/cries/ting_lu.bin"
.endif @ P_FAMILY_TING_LU

.if P_FAMILY_CHI_YU == TRUE
	.align 2
Cry_ChiYu::
	.incbin "sound/direct_sound_samples/cries/chi_yu.bin"
.endif @ P_FAMILY_CHI_YU

.if P_FAMILY_ROARING_MOON == TRUE
	.align 2
Cry_RoaringMoon::
	.incbin "sound/direct_sound_samples/cries/roaring_moon.bin"
.endif @ P_FAMILY_ROARING_MOON

.if P_FAMILY_IRON_VALIANT == TRUE
	.align 2
Cry_IronValiant::
	.incbin "sound/direct_sound_samples/cries/iron_valiant.bin"
.endif @ P_FAMILY_IRON_VALIANT

.if P_FAMILY_KORAIDON == TRUE
	.align 2
Cry_Koraidon::
	.incbin "sound/direct_sound_samples/cries/koraidon.bin"
.endif @ P_FAMILY_KORAIDON

.if P_FAMILY_MIRAIDON == TRUE
	.align 2
Cry_Miraidon::
	.incbin "sound/direct_sound_samples/cries/miraidon.bin"
.endif @ P_FAMILY_MIRAIDON

.if P_FAMILY_WALKING_WAKE == TRUE
	.align 2
Cry_WalkingWake::
	.incbin "sound/direct_sound_samples/cries/walking_wake.bin"
.endif @ P_FAMILY_WALKING_WAKE

.if P_FAMILY_IRON_LEAVES == TRUE
	.align 2
Cry_IronLeaves::
	.incbin "sound/direct_sound_samples/cries/iron_leaves.bin"
.endif @ P_FAMILY_IRON_LEAVES

.if P_FAMILY_POLTCHAGEIST == TRUE
	.align 2
Cry_Poltchageist::
	.incbin "sound/direct_sound_samples/cries/poltchageist.bin"

	.align 2
Cry_Sinistcha::
	.incbin "sound/direct_sound_samples/cries/sinistcha.bin"
.endif @ P_FAMILY_POLTCHAGEIST

.if P_FAMILY_OKIDOGI == TRUE
	.align 2
Cry_Okidogi::
	.incbin "sound/direct_sound_samples/cries/okidogi.bin"
.endif @ P_FAMILY_OKIDOGI

.if P_FAMILY_MUNKIDORI == TRUE
	.align 2
Cry_Munkidori::
	.incbin "sound/direct_sound_samples/cries/munkidori.bin"
.endif @ P_FAMILY_MUNKIDORI

.if P_FAMILY_FEZANDIPITI == TRUE
	.align 2
Cry_Fezandipiti::
	.incbin "sound/direct_sound_samples/cries/fezandipiti.bin"
.endif @ P_FAMILY_FEZANDIPITI

.if P_FAMILY_OGERPON == TRUE
	.align 2
Cry_Ogerpon::
	.incbin "sound/direct_sound_samples/cries/ogerpon.bin"
.endif @ P_FAMILY_OGERPON

.if P_FAMILY_GOUGING_FIRE == TRUE
	.align 2
Cry_GougingFire::
	.incbin "sound/direct_sound_samples/cries/gouging_fire.bin"
.endif @ P_FAMILY_GOUGING_FIRE

.if P_FAMILY_RAGING_BOLT == TRUE
	.align 2
Cry_RagingBolt::
	.incbin "sound/direct_sound_samples/cries/raging_bolt.bin"
.endif @ P_FAMILY_RAGING_BOLT

.if P_FAMILY_IRON_BOULDER == TRUE
	.align 2
Cry_IronBoulder::
	.incbin "sound/direct_sound_samples/cries/iron_boulder.bin"
.endif @ P_FAMILY_IRON_BOULDER

.if P_FAMILY_IRON_CROWN == TRUE
	.align 2
Cry_IronCrown::
	.incbin "sound/direct_sound_samples/cries/iron_crown.bin"
.endif @ P_FAMILY_IRON_CROWN

.if P_FAMILY_TERAPAGOS == TRUE
	.align 2
Cry_Terapagos::
	.incbin "sound/direct_sound_samples/cries/terapagos.bin"
.endif @ P_FAMILY_TERAPAGOS

.if P_FAMILY_PECHARUNT == TRUE
	.align 2
Cry_Pecharunt::
	.incbin "sound/direct_sound_samples/cries/pecharunt.bin"
.endif @ P_FAMILY_PECHARUNT
.endif @ P_CRIES_ENABLED

	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_unknown_18::
	.incbin "sound/direct_sound_samples/unknown_18.bin"

	.align 2
DirectSoundWaveData_sc88pro_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88pro_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"


.if PHONEMES_SHARED == TRUE
	.align 2
DirectSoundWaveData_Phoneme_1::
DirectSoundWaveData_Phoneme_2::
DirectSoundWaveData_Phoneme_3::
DirectSoundWaveData_Phoneme_4::
DirectSoundWaveData_Phoneme_5::
DirectSoundWaveData_Phoneme_6::
DirectSoundWaveData_Phoneme_7::
DirectSoundWaveData_Phoneme_8::
DirectSoundWaveData_Phoneme_9::
DirectSoundWaveData_Phoneme_10::
DirectSoundWaveData_Phoneme_11::
DirectSoundWaveData_Phoneme_12::
DirectSoundWaveData_Phoneme_13::
DirectSoundWaveData_Phoneme_14::
DirectSoundWaveData_Phoneme_15::
DirectSoundWaveData_Phoneme_16::
DirectSoundWaveData_Phoneme_17::
DirectSoundWaveData_Phoneme_18::
DirectSoundWaveData_Phoneme_19::
DirectSoundWaveData_Phoneme_20::
DirectSoundWaveData_Phoneme_21::
DirectSoundWaveData_Phoneme_22::
DirectSoundWaveData_Phoneme_23::
DirectSoundWaveData_Phoneme_24::
DirectSoundWaveData_Phoneme_25::
DirectSoundWaveData_Phoneme_26::
DirectSoundWaveData_Phoneme_27::
DirectSoundWaveData_Phoneme_28::
DirectSoundWaveData_Phoneme_29::
DirectSoundWaveData_Phoneme_30::
DirectSoundWaveData_Phoneme_31::
DirectSoundWaveData_Phoneme_32::
DirectSoundWaveData_Phoneme_33::
DirectSoundWaveData_Phoneme_34::
DirectSoundWaveData_Phoneme_35::
DirectSoundWaveData_Phoneme_36::
DirectSoundWaveData_Phoneme_37::
DirectSoundWaveData_Phoneme_38::
DirectSoundWaveData_Phoneme_39::
DirectSoundWaveData_Phoneme_40::
DirectSoundWaveData_Phoneme_41::
DirectSoundWaveData_Phoneme_42::
DirectSoundWaveData_Phoneme_43::
DirectSoundWaveData_Phoneme_44::
DirectSoundWaveData_Phoneme_45::
DirectSoundWaveData_Phoneme_46::
DirectSoundWaveData_Phoneme_47::
DirectSoundWaveData_Phoneme_48::
DirectSoundWaveData_Phoneme_49::
DirectSoundWaveData_Phoneme_50::
DirectSoundWaveData_Phoneme_51::
	.incbin "sound/direct_sound_samples/phonemes/shared.bin"

.else @ PHONEMES_SHARED

	.align 2
DirectSoundWaveData_Phoneme_1::
	.incbin "sound/direct_sound_samples/phonemes/01.bin"

	.align 2
DirectSoundWaveData_Phoneme_2::
	.incbin "sound/direct_sound_samples/phonemes/02.bin"

	.align 2
DirectSoundWaveData_Phoneme_3::
	.incbin "sound/direct_sound_samples/phonemes/03.bin"

	.align 2
DirectSoundWaveData_Phoneme_4::
	.incbin "sound/direct_sound_samples/phonemes/04.bin"

	.align 2
DirectSoundWaveData_Phoneme_5::
	.incbin "sound/direct_sound_samples/phonemes/05.bin"

	.align 2
DirectSoundWaveData_Phoneme_6::
	.incbin "sound/direct_sound_samples/phonemes/06.bin"

	.align 2
DirectSoundWaveData_Phoneme_7::
	.incbin "sound/direct_sound_samples/phonemes/07.bin"

	.align 2
DirectSoundWaveData_Phoneme_8::
	.incbin "sound/direct_sound_samples/phonemes/08.bin"

	.align 2
DirectSoundWaveData_Phoneme_9::
	.incbin "sound/direct_sound_samples/phonemes/09.bin"

	.align 2
DirectSoundWaveData_Phoneme_10::
	.incbin "sound/direct_sound_samples/phonemes/10.bin"

	.align 2
DirectSoundWaveData_Phoneme_11::
	.incbin "sound/direct_sound_samples/phonemes/11.bin"

	.align 2
DirectSoundWaveData_Phoneme_12::
	.incbin "sound/direct_sound_samples/phonemes/12.bin"

	.align 2
DirectSoundWaveData_Phoneme_13::
	.incbin "sound/direct_sound_samples/phonemes/13.bin"

	.align 2
DirectSoundWaveData_Phoneme_14::
	.incbin "sound/direct_sound_samples/phonemes/14.bin"

	.align 2
DirectSoundWaveData_Phoneme_15::
	.incbin "sound/direct_sound_samples/phonemes/15.bin"

	.align 2
DirectSoundWaveData_Phoneme_16::
	.incbin "sound/direct_sound_samples/phonemes/16.bin"

	.align 2
DirectSoundWaveData_Phoneme_17::
	.incbin "sound/direct_sound_samples/phonemes/17.bin"

	.align 2
DirectSoundWaveData_Phoneme_18::
	.incbin "sound/direct_sound_samples/phonemes/18.bin"

	.align 2
DirectSoundWaveData_Phoneme_19::
	.incbin "sound/direct_sound_samples/phonemes/19.bin"

	.align 2
DirectSoundWaveData_Phoneme_20::
	.incbin "sound/direct_sound_samples/phonemes/20.bin"

	.align 2
DirectSoundWaveData_Phoneme_21::
	.incbin "sound/direct_sound_samples/phonemes/21.bin"

	.align 2
DirectSoundWaveData_Phoneme_22::
	.incbin "sound/direct_sound_samples/phonemes/22.bin"

	.align 2
DirectSoundWaveData_Phoneme_23::
	.incbin "sound/direct_sound_samples/phonemes/23.bin"

	.align 2
DirectSoundWaveData_Phoneme_24::
	.incbin "sound/direct_sound_samples/phonemes/24.bin"

	.align 2
DirectSoundWaveData_Phoneme_25::
	.incbin "sound/direct_sound_samples/phonemes/25.bin"

	.align 2
DirectSoundWaveData_Phoneme_26::
	.incbin "sound/direct_sound_samples/phonemes/26.bin"

	.align 2
DirectSoundWaveData_Phoneme_27::
	.incbin "sound/direct_sound_samples/phonemes/27.bin"

	.align 2
DirectSoundWaveData_Phoneme_28::
	.incbin "sound/direct_sound_samples/phonemes/28.bin"

	.align 2
DirectSoundWaveData_Phoneme_29::
	.incbin "sound/direct_sound_samples/phonemes/29.bin"

	.align 2
DirectSoundWaveData_Phoneme_30::
	.incbin "sound/direct_sound_samples/phonemes/30.bin"

	.align 2
DirectSoundWaveData_Phoneme_31::
	.incbin "sound/direct_sound_samples/phonemes/31.bin"

	.align 2
DirectSoundWaveData_Phoneme_32::
	.incbin "sound/direct_sound_samples/phonemes/32.bin"

	.align 2
DirectSoundWaveData_Phoneme_33::
	.incbin "sound/direct_sound_samples/phonemes/33.bin"

	.align 2
DirectSoundWaveData_Phoneme_34::
	.incbin "sound/direct_sound_samples/phonemes/34.bin"

	.align 2
DirectSoundWaveData_Phoneme_35::
	.incbin "sound/direct_sound_samples/phonemes/35.bin"

	.align 2
DirectSoundWaveData_Phoneme_36::
	.incbin "sound/direct_sound_samples/phonemes/36.bin"

	.align 2
DirectSoundWaveData_Phoneme_37::
	.incbin "sound/direct_sound_samples/phonemes/37.bin"

	.align 2
DirectSoundWaveData_Phoneme_38::
	.incbin "sound/direct_sound_samples/phonemes/38.bin"

	.align 2
DirectSoundWaveData_Phoneme_39::
	.incbin "sound/direct_sound_samples/phonemes/39.bin"

	.align 2
DirectSoundWaveData_Phoneme_40::
	.incbin "sound/direct_sound_samples/phonemes/40.bin"

	.align 2
DirectSoundWaveData_Phoneme_41::
	.incbin "sound/direct_sound_samples/phonemes/41.bin"

	.align 2
DirectSoundWaveData_Phoneme_42::
	.incbin "sound/direct_sound_samples/phonemes/42.bin"

	.align 2
DirectSoundWaveData_Phoneme_43::
	.incbin "sound/direct_sound_samples/phonemes/43.bin"

	.align 2
DirectSoundWaveData_Phoneme_44::
	.incbin "sound/direct_sound_samples/phonemes/44.bin"

	.align 2
DirectSoundWaveData_Phoneme_45::
	.incbin "sound/direct_sound_samples/phonemes/45.bin"

	.align 2
DirectSoundWaveData_Phoneme_46::
	.incbin "sound/direct_sound_samples/phonemes/46.bin"

	.align 2
DirectSoundWaveData_Phoneme_47::
	.incbin "sound/direct_sound_samples/phonemes/47.bin"

	.align 2
DirectSoundWaveData_Phoneme_48::
	.incbin "sound/direct_sound_samples/phonemes/48.bin"

	.align 2
DirectSoundWaveData_Phoneme_49::
	.incbin "sound/direct_sound_samples/phonemes/49.bin"

	.align 2
DirectSoundWaveData_Phoneme_50::
	.incbin "sound/direct_sound_samples/phonemes/50.bin"

	.align 2
DirectSoundWaveData_Phoneme_51::
	.incbin "sound/direct_sound_samples/phonemes/51.bin"

.endif @ PHONEMES_SHARED

	.align 2
DirectSoundWaveData_sc88pro_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88pro_accordion_duplicate.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"
