#ifndef GUARD_CONSTANTS_CRIES_H
#define GUARD_CONSTANTS_CRIES_H

enum PokemonCry
{
    CRY_NONE,
#if P_FAMILY_ARGOMON_F
    CRY_ARGOMON_F,
    CRY_BOMBMON,
    CRY_BOMMON,
#if P_MEGA_EVOLUTIONS
    CRY_BOMMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_ARGOMON_F
#if P_FAMILY_BOTAMON
    CRY_BOTAMON,
    CRY_CHIBICKMON,
    CRY_CHIBOMON,
#if P_MEGA_EVOLUTIONS
    CRY_CHIBOMON_MEGA_X,
    CRY_CHIBOMON_MEGA_Y,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_BOTAMON
#if P_FAMILY_CONOMON
    CRY_CONOMON,
    CRY_COTSUCOMON,
    CRY_CURIMON,
#if P_MEGA_EVOLUTIONS
    CRY_CURIMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_CONOMON
#if P_FAMILY_DATIRIMON
    CRY_DATIRIMON,
    CRY_DODOMON,
    CRY_DOKIMON,
#endif //P_FAMILY_DATIRIMON
#if P_FAMILY_FUFUMON
    CRY_FUFUMON,
    CRY_JYARIMON,
    CRY_KEEMON,
#if P_MEGA_EVOLUTIONS
    CRY_KEEMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_FUFUMON
#if P_FAMILY_KETOMON
    CRY_KETOMON,
    CRY_KURAMON,
    CRY_LEAFMON,
#if P_MEGA_EVOLUTIONS
    CRY_LEAFMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_KETOMON
#if P_FAMILY_CHOROMON
    CRY_CHOROMON,
    CRY_MOKUMON,
#endif //P_FAMILY_CHOROMON
#if P_FAMILY_NYOKIMON
    CRY_NYOKIMON,
    CRY_PABUMON,
#endif //P_FAMILY_NYOKIMON
#if P_FAMILY_PAFUMON
    CRY_PAFUMON,
    CRY_PAOMON,
#endif //P_FAMILY_PAFUMON
#if P_FAMILY_PETITMON
#if P_GEN_2_CROSS_EVOS
    CRY_GUILMON_X,
#endif //P_GEN_2_CROSS_EVOS
    CRY_PETITMON,
    CRY_PICHIMON,
#endif //P_FAMILY_PETITMON
#if P_FAMILY_POPOMON
    CRY_POPOMON,
    CRY_POYOMON,
#endif //P_FAMILY_POPOMON
#if P_FAMILY_PUNIMON
    CRY_PUNIMON,
    CRY_PUPUMON,
    CRY_PURURUMON,
    CRY_PUSUMON,
    CRY_PUTTIMON,
    CRY_PUWAMON,
#endif //P_FAMILY_PUNIMON
#if P_FAMILY_PUYOMON
#if P_GEN_2_CROSS_EVOS
    CRY_GUMDRAMON,
#endif //P_GEN_2_CROSS_EVOS
    CRY_PUYOMON,
    CRY_PYONMON,
#endif //P_FAMILY_PUYOMON
#if P_FAMILY_RELEMON
    CRY_RELEMON,
    CRY_SAKUMON,
#endif //P_FAMILY_RELEMON
#if P_FAMILY_SANDMON
#if P_GEN_2_CROSS_EVOS
    CRY_HACKMON,
#endif //P_GEN_2_CROSS_EVOS
    CRY_SANDMON,
    CRY_TSUBUMON,
#endif //P_FAMILY_SANDMON
#if P_FAMILY_ICEBOTAMON
    CRY_ICEBOTAMON,
    CRY_YURAMON,
#if P_GEN_2_CROSS_EVOS
    CRY_GOTSUMON,
#endif //P_GEN_2_CROSS_EVOS
#endif //P_FAMILY_ICEBOTAMON
#if P_FAMILY_ZERIMON
    CRY_ZERIMON,
    CRY_ZURUMON,
    CRY_ARCADIAMON_IT,
#if P_GEN_2_CROSS_EVOS
    CRY_IMPMON_X,
#endif //P_GEN_2_CROSS_EVOS
#endif //P_FAMILY_ZERIMON
#if P_FAMILY_ARGOMON_IT
    CRY_ARGOMON_IT,
    CRY_BABYDMON,
#endif //P_FAMILY_ARGOMON_IT
#if P_FAMILY_BIBIMON
    CRY_BIBIMON,
    CRY_BOSAMON,
#endif //P_FAMILY_BIBIMON
#if P_FAMILY_BUDMON
    CRY_BUDMON,
    CRY_BUKAMON,
#endif //P_FAMILY_BUDMON
#if P_FAMILY_CALUMON
    CRY_CALUMON,
    CRY_CHAPMON,
#if P_GALARIAN_FORMS
    CRY_PERRSERKER,
#endif //P_GALARIAN_FORMS
#endif //P_FAMILY_CALUMON
#if P_FAMILY_CHICCHIMON
    CRY_CHICCHIMON,
    CRY_DEMMERAMON,
#endif //P_FAMILY_CHICCHIMON
#if P_FAMILY_DEMIVEEMON
    CRY_DEMIVEEMON,
    CRY_DORIMON,
#if P_GEN_9_CROSS_EVOS
    CRY_ANNIHILAPE,
#endif //P_GEN_9_CROSS_EVOS
#endif //P_FAMILY_DEMIVEEMON
#if P_FAMILY_FRIMON
    CRY_FRIMON,
    CRY_GIGIMON,
#endif //P_FAMILY_FRIMON
#if P_FAMILY_GUMMYMON
    CRY_GUMMYMON,
    CRY_GURIMON,
    CRY_HIYARIMON,
#if P_GEN_2_CROSS_EVOS
    CRY_KAMEMON,
#endif //P_GEN_2_CROSS_EVOS
#endif //P_FAMILY_GUMMYMON
#if P_FAMILY_HOPMON
    CRY_HOPMON,
    CRY_KAKKINMON,
    CRY_KAPURIMON,
#if P_MEGA_EVOLUTIONS
    CRY_KAPURIMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_HOPMON
#if P_FAMILY_KOKOMON
    CRY_KOKOMON,
    CRY_KOROMON,
    CRY_KOZENIMON,
#endif //P_FAMILY_KOKOMON
#if P_FAMILY_KYAROMON
    CRY_KYAROMON,
    CRY_KYOKYOMON,
    CRY_KYUPIMON,
#endif //P_FAMILY_KYAROMON
#if P_FAMILY_MINOMON
    CRY_MINOMON,
    CRY_MISSIMON,
#endif //P_FAMILY_MINOMON
#if P_FAMILY_MONIMON
    CRY_MONIMON,
    CRY_MOONMON,
    CRY_MOTIMON,
#endif //P_FAMILY_MONIMON
#if P_FAMILY_NEGAMON
    CRY_NEGAMON,
    CRY_NYAROMON,
#endif //P_FAMILY_NEGAMON
#if P_FAMILY_PAGUMON
    CRY_PAGUMON,
    CRY_PICKMON_SILVER,
#if P_GEN_2_CROSS_EVOS
    CRY_LIOLLMON,
#endif //P_GEN_2_CROSS_EVOS
#if P_MEGA_EVOLUTIONS
    CRY_PICKMON_SILVER_MEGA,
#endif //P_MEGA_EVOLUTIONS
#if P_GALARIAN_FORMS
    CRY_PAGUMON_GALAR,
#endif //P_GALARIAN_FORMS
#endif //P_FAMILY_PAGUMON
#if P_FAMILY_PICKMON_WHITE
    CRY_PICKMON_WHITE,
    CRY_PICKMON_RED,
#if P_GEN_4_CROSS_EVOS
    CRY_MAGNEZONE,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_PICKMON_WHITE
#if P_FAMILY_PINAMON
    CRY_PINAMON,
#if P_GALARIAN_FORMS
    CRY_SIRFETCHD,
#endif //P_GALARIAN_FORMS
#endif //P_FAMILY_PINAMON
#if P_FAMILY_POROMON
    CRY_POROMON,
    CRY_PUROROMON,
#endif //P_FAMILY_POROMON
#if P_FAMILY_PUSURIMON
    CRY_PUSURIMON,
    CRY_PUYOYOMON,
#endif //P_FAMILY_PUSURIMON
#if P_FAMILY_SAKUTTOMON
    CRY_SAKUTTOMON,
    CRY_SUNMON,
#endif //P_FAMILY_SAKUTTOMON
#if P_FAMILY_TANEMON
    CRY_TANEMON,
    CRY_TOKOMON,
#endif //P_FAMILY_TANEMON
#if P_FAMILY_TOKOMON_X
    CRY_TOKOMON_X,
    CRY_TORBALLMON,
    CRY_TSUMEMON,
#if P_MEGA_EVOLUTIONS
    CRY_TSUMEMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_TOKOMON_X
#if P_FAMILY_TSUNOMON
    CRY_TSUNOMON,
#if P_GEN_2_CROSS_EVOS
    CRY_KODEKACMON,
#if P_MEGA_EVOLUTIONS
    CRY_KODEKACMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_GEN_2_CROSS_EVOS
#endif //P_FAMILY_TSUNOMON
#if P_FAMILY_TUMBLEMON
    CRY_TUMBLEMON,
    CRY_UPAMON,
#endif //P_FAMILY_TUMBLEMON
#if P_FAMILY_VIXIMON
    CRY_VIXIMON,
    CRY_WANYAMON,
#endif //P_FAMILY_VIXIMON
#if P_FAMILY_XIAOMON
    CRY_XIAOMON,
    CRY_YAAMON,
#endif //P_FAMILY_XIAOMON
#if P_FAMILY_YOKOMON
    CRY_YOKOMON,
    CRY_AGUMON,
#endif //P_FAMILY_YOKOMON
#if P_FAMILY_AGUMON_06
    CRY_AGUMON_06,
    CRY_AGUMON_EXPERT,
#endif //P_FAMILY_AGUMON_06
#if P_FAMILY_HITMONS
#if P_GEN_2_CROSS_EVOS
    CRY_SALAMON,
#endif //P_GEN_2_CROSS_EVOS
    CRY_AGUMON_X,
    CRY_ANGORAMON,
#if P_GEN_2_CROSS_EVOS
    CRY_SALAMON_X,
#endif //P_GEN_2_CROSS_EVOS
#endif //P_FAMILY_HITMONS
#if P_FAMILY_ARCADIAMON_ROOKIE
    CRY_ARCADIAMON_ROOKIE,
#if P_GEN_4_CROSS_EVOS
    CRY_LICKILICKY,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_ARCADIAMON_ROOKIE
#if P_FAMILY_ARGOMON_ROOKIE
    CRY_ARGOMON_ROOKIE,
    CRY_ARMADILMON,
#endif //P_FAMILY_ARGOMON_ROOKIE
#if P_FAMILY_ARURAUMON
    CRY_ARURAUMON,
    CRY_BAKOMON,
#if P_GEN_4_CROSS_EVOS
    CRY_RHYPERIOR,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_ARURAUMON
#if P_FAMILY_BEARMON
#if P_GEN_4_CROSS_EVOS
    CRY_HAPPINY,
#endif //P_GEN_4_CROSS_EVOS
    CRY_BEARMON,
#if P_GEN_2_CROSS_EVOS
    CRY_SHOUTMON,
#endif //P_GEN_2_CROSS_EVOS
#endif //P_FAMILY_BEARMON
#if P_FAMILY_BETAMON
    CRY_BETAMON,
#if P_GEN_4_CROSS_EVOS
    CRY_TANGROWTH,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_BETAMON
#if P_FAMILY_BETAMON_X
    CRY_BETAMON_X,
#if P_MEGA_EVOLUTIONS
    CRY_BETAMON_X_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_BETAMON_X
#if P_FAMILY_BIYOMON
    CRY_BIYOMON,
    CRY_BLKAGUMON,
#if P_GEN_2_CROSS_EVOS
    CRY_PSYCHEMON,
#endif //P_GEN_2_CROSS_EVOS
#endif //P_FAMILY_BIYOMON
#if P_FAMILY_BLKAGUMON_X
    CRY_BLKAGUMON_X,
    CRY_BLKGABUMON,
#endif //P_FAMILY_BLKAGUMON_X
#if P_FAMILY_BLKGUILMON
    CRY_BLKGUILMON,
    CRY_BOKOMON,
#endif //P_FAMILY_BLKGUILMON
#if P_FAMILY_BULUCOMON
#if P_GEN_4_CROSS_EVOS
    CRY_MIME_JR,
#endif //P_GEN_4_CROSS_EVOS
    CRY_BULUCOMON,
#if P_GALARIAN_FORMS
    CRY_MR_RIME,
#endif //P_GALARIAN_FORMS
#endif //P_FAMILY_BULUCOMON
#if P_FAMILY_BURGERMON
    CRY_BURGERMON,
#if P_GEN_2_CROSS_EVOS
    CRY_MONODRAMON,
#if P_MEGA_EVOLUTIONS
    CRY_MONODRAMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_GEN_2_CROSS_EVOS
#if P_GEN_8_CROSS_EVOS
    CRY_KLEAVOR,
#endif //P_GEN_8_CROSS_EVOS
#endif //P_FAMILY_BURGERMON
#if P_FAMILY_SAMUAGUMON
#if P_GEN_2_CROSS_EVOS
    CRY_SANGOMON,
#endif //P_GEN_2_CROSS_EVOS
    CRY_SAMUAGUMON,
#endif //P_FAMILY_SAMUAGUMON
#if P_FAMILY_CANDLEMON
#if P_GEN_2_CROSS_EVOS
    CRY_SANTAAGUMON,
#endif //P_GEN_2_CROSS_EVOS
    CRY_CANDLEMON,
#if P_GEN_4_CROSS_EVOS
    CRY_ELECTIVIRE,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_CANDLEMON
#if P_FAMILY_CHIKURIMON
#if P_GEN_2_CROSS_EVOS
    CRY_BLKTOYAMON,
#endif //P_GEN_2_CROSS_EVOS
    CRY_CHIKURIMON,
#if P_GEN_4_CROSS_EVOS
    CRY_MAGMORTAR,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_CHIKURIMON
#if P_FAMILY_TYUTYUMON
    CRY_TYUTYUMON,
#if P_MEGA_EVOLUTIONS
    CRY_TYUTYUMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_TYUTYUMON
#if P_FAMILY_CHUUMON
    CRY_CHUUMON,
#endif //P_FAMILY_CHUUMON
#if P_FAMILY_HAZYAGUMON
    CRY_HAZYAGUMON,
    CRY_COMMDRAMON,
#if P_MEGA_EVOLUTIONS
    CRY_COMMDRAMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_HAZYAGUMON
#if P_FAMILY_CORONAMON
    CRY_CORONAMON,
#endif //P_FAMILY_CORONAMON
#if P_FAMILY_CRABMON
    CRY_CRABMON,
#endif //P_FAMILY_CRABMON
#if P_FAMILY_CRABMON_X
    CRY_CRABMON_X,
    CRY_CUTEMON,
    CRY_DAMEMON,
    CRY_DEMIDEVMON,
#if P_GEN_2_CROSS_EVOS
    CRY_KUNEMON,
    CRY_LABRAMON,
#endif //P_GEN_2_CROSS_EVOS
#if P_GEN_4_CROSS_EVOS
    CRY_LEAFEON,
    CRY_GLACEON,
#endif //P_GEN_4_CROSS_EVOS
#if P_GEN_6_CROSS_EVOS
    CRY_SYLVEON,
#endif //P_GEN_6_CROSS_EVOS
#endif //P_FAMILY_CRABMON_X
#if P_FAMILY_DOKUNEMON
    CRY_DOKUNEMON,
#if P_GEN_2_CROSS_EVOS
    CRY_RENAMON_X,
#if P_GEN_4_CROSS_EVOS
    CRY_PORYGON_Z,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_GEN_2_CROSS_EVOS
#endif //P_FAMILY_DOKUNEMON
#if P_FAMILY_DONDOKOMON
    CRY_DONDOKOMON,
    CRY_DORUMON,
#endif //P_FAMILY_DONDOKOMON
#if P_FAMILY_DOTAGUMON
    CRY_DOTAGUMON,
    CRY_DOTFALCMON,
#endif //P_FAMILY_DOTAGUMON
#if P_FAMILY_DRACMON
    CRY_DRACMON,
#if P_MEGA_EVOLUTIONS
    CRY_DRACMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_DRACMON
#if P_FAMILY_DRACOMON
#if P_GEN_4_CROSS_EVOS
    CRY_MUNCHLAX,
#endif //P_GEN_4_CROSS_EVOS
    CRY_DRACOMON,
#endif //P_FAMILY_DRACOMON
#if P_FAMILY_DRACOMON_X
    CRY_DRACOMON_X,
#endif //P_FAMILY_DRACOMON_X
#if P_FAMILY_EBIBURGMON
    CRY_EBIBURGMON,
#endif //P_FAMILY_EBIBURGMON
#if P_FAMILY_EKAKIMON
    CRY_EKAKIMON,
#endif //P_FAMILY_EKAKIMON
#if P_FAMILY_ELECMON
    CRY_ELECMON,
    CRY_ELECMON_VIOLET,
    CRY_ESPIMON,
#endif //P_FAMILY_ELECMON
#if P_FAMILY_AGUMON_FAKE_EXPERT
    CRY_AGUMON_FAKE_EXPERT,
#if P_MEGA_EVOLUTIONS
    CRY_AGUMON_FAKE_EXPERT_MEGA_X,
    CRY_AGUMON_FAKE_EXPERT_MEGA_Y,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_AGUMON_FAKE_EXPERT
#if P_FAMILY_FALCOMON
    CRY_FALCOMON,
#endif //P_FAMILY_FALCOMON
#if P_FAMILY_FALCOMON_06
    CRY_FALCOMON_06,
    CRY_FANBEEMON,
    CRY_FLAMEMON,
#endif //P_FAMILY_FALCOMON_06
#if P_FAMILY_FLORAMON
    CRY_FLORAMON,
    CRY_GABUMON,
    CRY_GABUMON_X,
#endif //P_FAMILY_FLORAMON
#if P_FAMILY_GAMMAMON
    CRY_GAMMAMON,
    CRY_GAOMON,
    CRY_GAOSSMON,
#endif //P_FAMILY_GAMMAMON
#if P_FAMILY_GAZIMON
    CRY_GAZIMON,
    CRY_GAZIMON_X,
#endif //P_FAMILY_GAZIMON
#if P_FAMILY_GHOSTMON
    CRY_GHOSTMON,
    CRY_GIZAMON,
#endif //P_FAMILY_GHOSTMON
#if P_FAMILY_GIZUMON
    CRY_GIZUMON,
    CRY_GOBLIMON,
#endif //P_FAMILY_GIZUMON
#if P_FAMILY_GOMAMON
    CRY_GOMAMON,
    CRY_GOMAMON_X,
#endif //P_FAMILY_GOMAMON
#if P_FAMILY_GOTSUMON_X
    CRY_GOTSUMON_X,
    CRY_GUILMON,
#endif //P_FAMILY_GOTSUMON_X
#if P_FAMILY_HAGURUMON
    CRY_HAGURUMON,
    CRY_HAGURUMON_X,
#if P_GEN_4_CROSS_EVOS
    CRY_TOGEKISS,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_HAGURUMON
#if P_FAMILY_HAWKMON
    CRY_HAWKMON,
    CRY_HERISSMON,
#endif //P_FAMILY_HAWKMON
#if P_FAMILY_HYOKOMON
    CRY_HYOKOMON,
    CRY_IGNITEMON,
    CRY_IMPMON,
#if P_MEGA_EVOLUTIONS
    CRY_IMPMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_HYOKOMON
#if P_FAMILY_JAZAMON
#if P_GEN_3_CROSS_EVOS
    CRY_BIOSTEGMON,
#endif //P_GEN_3_CROSS_EVOS
    CRY_JAZAMON,
    CRY_JELLYMON,
#endif //P_FAMILY_JAZAMON
#if P_FAMILY_JUNKMON
    CRY_BONSLY,
    CRY_JUNKMON,
#endif //P_FAMILY_JUNKMON
#if P_FAMILY_KERAMON
    CRY_KERAMON,
    CRY_KERAMON_X,
    CRY_KODOKGUMON,
#endif //P_FAMILY_KERAMON
#if P_FAMILY_KOKABUIMON
    CRY_KOKABUIMON,
    CRY_AMBIPOM,
#endif //P_FAMILY_KOKABUIMON
#if P_FAMILY_KOKUWAMON
    CRY_KOKUWAMON,
    CRY_KOKUWAMON_X,
#endif //P_FAMILY_KOKUWAMON
#if P_FAMILY_KOTEMON
    CRY_KOTEMON,
#if P_GEN_4_CROSS_EVOS
    CRY_YANMEGA,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_KOTEMON
#if P_FAMILY_KUDAMON
    CRY_KUDAMON,
    CRY_KUDAMON_06,
#if P_PALDEAN_FORMS
    CRY_CLODSIRE,
#endif //P_PALDEAN_FORMS
#endif //P_FAMILY_KUDAMON
#if P_FAMILY_LALAMON
    CRY_LALAMON,
    CRY_HONCHKROW,
#endif //P_FAMILY_LALAMON
#if P_FAMILY_LOOGAMON
    CRY_LOOGAMON,
    CRY_MISMAGIUS,
#endif //P_FAMILY_LOOGAMON
#if P_FAMILY_LOPMON
    CRY_LOPMON,
#endif //P_FAMILY_LOPMON
#if P_FAMILY_LOPMONX
#if P_GEN_3_CROSS_EVOS
    CRY_EXVEEMON,
#endif //P_GEN_3_CROSS_EVOS
    CRY_LOPMONX,
#endif //P_FAMILY_LOPMONX
#if P_FAMILY_LUCEMON
    CRY_LUCEMON,
#if P_GEN_9_CROSS_EVOS
    CRY_FARIGIRAF,
#endif //P_GEN_9_CROSS_EVOS
#endif //P_FAMILY_LUCEMON
#if P_FAMILY_LUDOMON
    CRY_LUDOMON,
    CRY_LUNAMON,
#endif //P_FAMILY_LUDOMON
#if P_FAMILY_LUXMON
    CRY_LUXMON,
#if P_GEN_9_CROSS_EVOS
    CRY_DUDUNSPARCE,
#endif //P_GEN_9_CROSS_EVOS
#endif //P_FAMILY_LUXMON
#if P_FAMILY_METABEE
    CRY_METABEE,
#if P_GEN_4_CROSS_EVOS
    CRY_GLISCOR,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_METABEE
#if P_FAMILY_MODBETAMON
    CRY_MODBETAMON,
    CRY_MONITAMON,
#endif //P_FAMILY_MODBETAMON
#if P_FAMILY_MONMON
    CRY_MONMON,
#if P_HISUIAN_FORMS
    CRY_OVERQWIL,
#endif //P_HISUIAN_FORMS
#endif //P_FAMILY_MONMON
#if P_FAMILY_MORPHOMON
    CRY_MORPHOMON,
#endif //P_FAMILY_MORPHOMON
#if P_FAMILY_MUCHOMON
    CRY_MUCHOMON,
#if P_MEGA_EVOLUTIONS
    CRY_MUCHOMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_MUCHOMON
#if P_FAMILY_MUSHROOMON
    CRY_MUSHROOMON,
#if P_GEN_4_CROSS_EVOS
    CRY_WEAVILE,
#endif //P_GEN_4_CROSS_EVOS
#if P_HISUIAN_FORMS
    CRY_SNEASLER,
#endif //P_HISUIAN_FORMS
#endif //P_FAMILY_MUSHROOMON
#if P_FAMILY_NEEMON
    CRY_NEEMON,
    CRY_OTAMAMON,
#if P_GEN_8_CROSS_EVOS
    CRY_URSALUNA,
#endif //P_GEN_8_CROSS_EVOS
#endif //P_FAMILY_NEEMON
#if P_FAMILY_OTAMAMON_RED
    CRY_OTAMAMON_RED,
    CRY_OTAMAMON_X,
#endif //P_FAMILY_OTAMAMON_RED
#if P_FAMILY_PALMON
    CRY_PALMON,
    CRY_PALMON_X,
#if P_GEN_4_CROSS_EVOS
    CRY_MAMOSWINE,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_PALMON
#if P_FAMILY_PATAMON
    CRY_PATAMON,
#if P_GALARIAN_FORMS
    CRY_CURSOLA,
#endif //P_GALARIAN_FORMS
#endif //P_FAMILY_PATAMON
#if P_FAMILY_PAWNMON_BLACK
    CRY_PAWNMON_BLACK,
    CRY_PAWNMON_WHITE,
#endif //P_FAMILY_PAWNMON_BLACK
#if P_FAMILY_PENGUINMON
    CRY_PENGUINMON,
#endif //P_FAMILY_PENGUINMON
#if P_FAMILY_PETITMAMON
#if P_GEN_4_CROSS_EVOS
    CRY_MANTYKE,
#endif //P_GEN_4_CROSS_EVOS
    CRY_PETITMAMON,
#endif //P_FAMILY_PETITMAMON
#if P_FAMILY_PHASCOMON
    CRY_PHASCOMON,
#endif //P_FAMILY_PHASCOMON
#if P_FAMILY_PILLOMON
    CRY_PILLOMON,
    CRY_POMUMON,
#if P_MEGA_EVOLUTIONS
    CRY_POMUMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_PILLOMON
#if P_FAMILY_PULSEMON
    CRY_PULSEMON,
    CRY_RENAMON,
#endif //P_FAMILY_PULSEMON
#if P_FAMILY_ROKUSHO
    CRY_ROKUSHO,
#if P_GEN_8_CROSS_EVOS
    CRY_WYRDEER,
#endif //P_GEN_8_CROSS_EVOS
#endif //P_FAMILY_ROKUSHO
#if P_FAMILY_RYUDAMON
    CRY_RYUDAMON,
#endif //P_FAMILY_RYUDAMON
#if P_FAMILY_SHAMANMON
    CRY_SHAMANMON,
#endif //P_FAMILY_SHAMANMON
#if P_FAMILY_YUKIAGUMON
    CRY_YUKIAGUMON,
#endif //P_FAMILY_YUKIAGUMON
#if P_FAMILY_YUKIAGUMON_06
    CRY_YUKIAGUMON_06,
#endif //P_FAMILY_YUKIAGUMON_06
#if P_FAMILY_ICEGOBIMON
    CRY_ICEGOBIMON,
#endif //P_FAMILY_ICEGOBIMON
#if P_FAMILY_SOLARMON
    CRY_SOLARMON,
    CRY_SOUNBRDMON,
    CRY_SPADAMON,
#if P_MEGA_EVOLUTIONS
    CRY_SPADAMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_SOLARMON
#if P_FAMILY_SPARROWMON
    CRY_SPARROWMON,
#endif //P_FAMILY_SPARROWMON
#if P_FAMILY_STARMON_2010
    CRY_STARMON_2010,
#endif //P_FAMILY_STARMON_2010
#if P_FAMILY_STRABIMON
    CRY_STRABIMON,
#endif //P_FAMILY_STRABIMON
#if P_FAMILY_SUNARZAMON
    CRY_SUNARZAMON,
    CRY_SWIMMON,
    CRY_SYAKOMON,
#if P_MEGA_EVOLUTIONS
    CRY_SYAKOMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_SUNARZAMON
#if P_FAMILY_SYAKOMON_X
    CRY_SYAKOMON_X,
    CRY_TAPIRMON,
    CRY_TENTOMON,
#if P_MEGA_EVOLUTIONS
    CRY_TENTOMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_SYAKOMON_X
#if P_FAMILY_TERRIERMON
    CRY_TERRIERMON,
    CRY_TERRIERMON_ASSISTANT,
    CRY_TERRIERMON_X,
#if P_MEGA_EVOLUTIONS
    CRY_TERRIERMON_X_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_TERRIERMON
#if P_FAMILY_TINKERMON
    CRY_TINKERMON,
    CRY_TINPET,
#endif //P_FAMILY_TINKERMON
#if P_FAMILY_TOYAGUMON
    CRY_TOYAGUMON,
    CRY_TSUKAIMON,
#if P_GALARIAN_FORMS
    CRY_OBSTAGOON,
#endif //P_GALARIAN_FORMS
#endif //P_FAMILY_TOYAGUMON
#if P_FAMILY_VEEMON
    CRY_VEEMON,
    CRY_VEMMON,
    CRY_VORVOMON,
    CRY_WORMMON,
    CRY_ZENIMON,
#endif //P_FAMILY_VEEMON
#if P_FAMILY_ZUBAMON
    CRY_ZUBAMON,
    CRY_AEGIOMON,
    CRY_AGUNIMON,
#endif //P_FAMILY_ZUBAMON
#if P_FAMILY_AIRDRAMON
    CRY_AIRDRAMON,
    CRY_AKATORIMON,
    CRY_ALLOMON,
#endif //P_FAMILY_AIRDRAMON
#if P_FAMILY_ALLOMON_X
    CRY_ALLOMON_X,
    CRY_ANGELAMON,
#endif //P_FAMILY_ALLOMON_X
#if P_FAMILY_ANGEMON
    CRY_ANGEMON,
    CRY_ANKYLOMON,
#endif //P_FAMILY_ANGEMON
#if P_FAMILY_APEMON
    CRY_APEMON,
    CRY_AQUILAMON,
    CRY_ARCADIAMON_CHAMPION,
#if P_MEGA_EVOLUTIONS
    CRY_ARCADIAMON_CHAMPION_MEGA,
#endif //P_MEGA_EVOLUTIONS
#if P_GEN_4_CROSS_EVOS
    CRY_GALLADE,
#if P_MEGA_EVOLUTIONS
    CRY_GALLADE_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_APEMON
#if P_FAMILY_ARCHELOMON
    CRY_ARCHELOMON,
    CRY_ARGOMON_CHAMPION,
#endif //P_FAMILY_ARCHELOMON
#if P_FAMILY_ARESDRAMON
    CRY_ARESDRAMON,
    CRY_ATAMADEMON,
#endif //P_FAMILY_ARESDRAMON
#if P_FAMILY_AURUMON
    CRY_AURUMON,
    CRY_AXEMON,
    CRY_BABOONMON,
#endif //P_FAMILY_AURUMON
#if P_FAMILY_BAKEMON
    CRY_BAKEMON,
    CRY_BALISTAMON,
    CRY_BALUCHIMON,
#endif //P_FAMILY_BAKEMON
#if P_FAMILY_BAOHUCKMON
    CRY_BAOHUCKMON,
    CRY_BAROMON,
    CRY_TRAILMON_BATTLE_ARMAMENT,
#endif //P_FAMILY_BAOHUCKMON
#if P_FAMILY_BETGAMAMON
    CRY_BETGAMAMON,
    CRY_BIOQUETMON,
#endif //P_FAMILY_BETGAMAMON
#if P_FAMILY_BIOTHUNMON
    CRY_BIOTHUNMON,
#if P_GEN_4_CROSS_EVOS
    CRY_PROBOPASS,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_BIOTHUNMON
#if P_FAMILY_BIRDRAMON
    CRY_BIRDRAMON,
    CRY_BLGAOGAMON,
#endif //P_FAMILY_BIRDRAMON
#if P_FAMILY_BLGARGOMON
    CRY_BLGARGOMON,
#if P_MEGA_EVOLUTIONS
    CRY_BLGARGOMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_BLGARGOMON
#if P_FAMILY_BLGARURMON
    CRY_BLGARURMON,
#if P_MEGA_EVOLUTIONS
    CRY_BLGARURMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_BLGARURMON
#if P_FAMILY_BLKGATOMON
    CRY_BLKGATOMON,
    CRY_BLKGATOMON_UVER,
    CRY_BLGROWLMON,
#if P_MEGA_EVOLUTIONS
    CRY_BLGROWLMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_BLKGATOMON
#if P_FAMILY_SAWKUWAMON
    CRY_SAWKUWAMON,
    CRY_BLIMPMON,
#if P_MEGA_EVOLUTIONS
    CRY_BLIMPMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_SAWKUWAMON
#if P_FAMILY_BOARMON
    CRY_BOARMON,
    CRY_BOMNANIMON,
#if P_MEGA_EVOLUTIONS
    CRY_BOMNANIMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_BOARMON
#if P_FAMILY_BOOGIEMON
    CRY_BOOGIEMON,
#endif //P_FAMILY_BOOGIEMON
#if P_FAMILY_BUCCHIEMON_RED
    CRY_BUCCHIEMON_RED,
#endif //P_FAMILY_BUCCHIEMON_RED
#if P_FAMILY_BUCCHIEMON_GREEN_BULKMON
    CRY_BUCCHIEMON_GREEN,
    CRY_BULKMON,
#endif //P_FAMILY_BUCCHIEMON_GREEN_BULKMON
#if P_FAMILY_BULLMON
#if P_GEN_4_CROSS_EVOS
    CRY_BUDEW,
#endif //P_GEN_4_CROSS_EVOS
    CRY_BULLMON,
#if P_GEN_4_CROSS_EVOS
    CRY_ROSERADE,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_BULLMON
#if P_FAMILY_BURAIMON
    CRY_BURAIMON,
    CRY_BURGERMON_CHAMPION,
#endif //P_FAMILY_BURAIMON
#if P_FAMILY_CHOUMON
    CRY_CHOUMON,
    CRY_CENTARUMON,
#if P_MEGA_EVOLUTIONS
    CRY_CENTARUMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_CHOUMON
#if P_FAMILY_CHAMBLEMON
    CRY_CHAMBLEMON,
    CRY_CHAMELEMON,
#endif //P_FAMILY_CHAMBLEMON
#if P_FAMILY_CHRYSALMON
    CRY_CHRYSALMON,
    CRY_CITRAMON,
#if P_MEGA_EVOLUTIONS
    CRY_CITRAMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_CHRYSALMON
#if P_FAMILY_CLOCKMON
    CRY_CLOCKMON,
#endif //P_FAMILY_CLOCKMON
#if P_FAMILY_CLOCKMON_FUSION
    CRY_CLOCKMON_FUSION,
    CRY_COELAMON,
#endif //P_FAMILY_CLOCKMON_FUSION
#if P_FAMILY_COREDRAMON_BLUE
    CRY_COREDRAMON_BLUE,
#endif //P_FAMILY_COREDRAMON_BLUE
#if P_FAMILY_COREDRAMON_GREEN
    CRY_COREDRAMON_GREEN,
    CRY_CYCLONEMON,
    CRY_DAMEMON_FUSION,
#endif //P_FAMILY_COREDRAMON_GREEN
#if P_FAMILY_DARCMON
    CRY_DARCMON,
    CRY_TRAILMON_DARK,
#endif //P_FAMILY_DARCMON
#if P_FAMILY_DARLIZAMON
    CRY_DARLIZAMON,
    CRY_DARMAILMON,
#if P_MEGA_EVOLUTIONS
    CRY_DARMAILMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_DARLIZAMON
#if P_FAMILY_DARKTYRMON
    CRY_DARKTYRMON,
#endif //P_FAMILY_DARKTYRMON
#if P_FAMILY_DARKTYRMON_X
    CRY_DARKTYRMON_X,
#endif //P_FAMILY_DARKTYRMON_X
#if P_FAMILY_DECKDRAMON
    CRY_DECKDRAMON,
#endif //P_FAMILY_DECKDRAMON
#if P_FAMILY_DELTAMON
    CRY_DELTAMON,
#endif //P_FAMILY_DELTAMON
#if P_FAMILY_DEPTHMON
    CRY_DEPTHMON,
    CRY_DEPUTYMON,
#endif //P_FAMILY_DEPTHMON
#if P_FAMILY_DEVIDRAMON
    CRY_DEVIDRAMON,
    CRY_DEVIMON,
#endif //P_FAMILY_DEVIDRAMON
#if P_FAMILY_DEXDORUMON
    CRY_DEXDORUMON,
    CRY_DIATRYMON,
#endif //P_FAMILY_DEXDORUMON
#if P_FAMILY_DIGMON
    CRY_DIGMON,
    CRY_DINOHYUMON,
#endif //P_FAMILY_DIGMON
#if P_FAMILY_DOBERMON
    CRY_DOBERMON,
    CRY_DOBERMON_X,
#endif //P_FAMILY_DOBERMON
#if P_FAMILY_DOGGYMON
    CRY_DOGGYMON,
    CRY_DOKUGUMON,
#endif //P_FAMILY_DOGGYMON
#if P_FAMILY_DOLPHMON
    CRY_DOLPHMON,
#endif //P_FAMILY_DOLPHMON
#if P_FAMILY_DONSHOUMON
    CRY_DONSHOUMON,
#endif //P_FAMILY_DONSHOUMON
#if P_FAMILY_DORUGAMON
    CRY_DORUGAMON,
    CRY_DORULUMON,
#if P_MEGA_EVOLUTIONS
    CRY_DORULUMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_DORUGAMON
#if P_FAMILY_DRIMOGEMON
    CRY_DRIMOGEMON,
    CRY_EBIDRAMON,
#if P_GEN_4_CROSS_EVOS
    CRY_DUSKNOIR,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_DRIMOGEMON
#if P_FAMILY_ELEPHANMON
    CRY_ELEPHANMON,
#endif //P_FAMILY_ELEPHANMON
#if P_FAMILY_EOSMON_CHAMPION
#if P_GEN_4_CROSS_EVOS
    CRY_CHINGLING,
#endif //P_GEN_4_CROSS_EVOS
    CRY_EOSMON_CHAMPION,
#endif //P_FAMILY_EOSMON_CHAMPION
#if P_FAMILY_EXERMON
    CRY_EXERMON,
#if P_MEGA_EVOLUTIONS
    CRY_EXERMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_EXERMON
#if P_FAMILY_EXVEEMON_VIRUS
    CRY_EXVEEMON_VIRUS,
    CRY_EYESMON,
#if P_MEGA_EVOLUTIONS
    CRY_EYESMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#if P_GEN_4_CROSS_EVOS
    CRY_FROSLASS,
#endif //P_GEN_4_CROSS_EVOS
#endif //P_FAMILY_EXVEEMON_VIRUS
#if P_FAMILY_EYESMON_SCATTERMODE
    CRY_EYESMON_SCATTERMODE,
    CRY_FANGMON,
    CRY_FILMON,
#endif //P_FAMILY_EYESMON_SCATTERMODE
#if P_FAMILY_FIRAMON
    CRY_FIRAMON,
    CRY_FLADRAMON,
    CRY_FLAWIZAMON,
#endif //P_FAMILY_FIRAMON
#if P_FAMILY_FLARIZAMON
    CRY_FLARIZAMON,
#endif //P_FAMILY_FLARIZAMON
#if P_FAMILY_FLYBEEMON
    CRY_FLYBEEMON,
#endif //P_FAMILY_FLYBEEMON
#if P_FAMILY_FLYMON
    CRY_FLYMON,
    CRY_FRIGIMON,
    CRY_FROGMON,
#if P_MEGA_EVOLUTIONS
    CRY_FROGMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_FLYMON
#if P_FAMILY_FUGAMON
    CRY_FUGAMON,
    CRY_GANEMON,
    CRY_GAOGAMON,
#if P_MEGA_EVOLUTIONS
    CRY_GAOGAMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_FUGAMON
#if P_FAMILY_GARGOMON
    CRY_GARGOMON,
#endif //P_FAMILY_GARGOMON
#if P_FAMILY_GARGOYLMON
    CRY_GARGOYLMON,
#endif //P_FAMILY_GARGOYLMON
#if P_FAMILY_GARURUMON
    CRY_GARURUMON,
#endif //P_FAMILY_GARURUMON
#if P_FAMILY_GARURUMON_X
    CRY_GARURUMON_X,
#if P_MEGA_EVOLUTIONS
    CRY_GARURUMON_X_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_GARURUMON_X
#if P_FAMILY_GATOMON
    CRY_GATOMON,
#if P_MEGA_EVOLUTIONS
    CRY_GATOMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_GATOMON
#if P_FAMILY_GATOMON_X
    CRY_GATOMON_X,
#if P_PRIMAL_REVERSIONS
    CRY_GATOMON_X_PRIMAL,
#endif //P_PRIMAL_REVERSIONS
#endif //P_FAMILY_GATOMON_X
#if P_FAMILY_GEKOMON
    CRY_GEKOMON,
#if P_PRIMAL_REVERSIONS
    CRY_GEKOMON_PRIMAL,
#endif //P_PRIMAL_REVERSIONS
#endif //P_FAMILY_GEKOMON
#if P_FAMILY_GEOGREYMON
    CRY_GEOGREYMON,
#if P_MEGA_EVOLUTIONS
    CRY_GEOGREYMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_GEOGREYMON
#if P_FAMILY_GEREMON
    CRY_GEREMON,
#endif //P_FAMILY_GEREMON
#if P_FAMILY_GESOMON
    CRY_GESOMON,
#endif //P_FAMILY_GESOMON
#if P_FAMILY_DEATHMON_CMON_DIGIMON
    CRY_DEATHMON_CMON_DIGIMON,
    CRY_GREYMON,
    CRY_KABUTERIMON,
#endif //P_FAMILY_DEATHMON_CMON_DIGIMON
#if P_FAMILY_MERAMON
    CRY_MERAMON,
    CRY_NUMEMON,
    CRY_SEADRAMON,
#endif //P_FAMILY_MERAMON
#if P_FAMILY_TYRANNOMON
    CRY_TYRANNOMON,
    CRY_VEGIEMON,
    CRY_WHAMON,
#endif //P_FAMILY_TYRANNOMON
#if P_FAMILY_KOKATORIMON
    CRY_KOKATORIMON,
    CRY_VILEMON,
    CRY_ROACHMON,
#endif //P_FAMILY_KOKATORIMON
#if P_FAMILY_GORILLAMON
    CRY_GORILLAMON,
    CRY_IKKAKUMON,
#endif //P_FAMILY_GORILLAMON
#if P_FAMILY_KUWAGAMON
    CRY_KUWAGAMON,
    CRY_LEOMON,
#endif //P_FAMILY_KUWAGAMON
#if P_FAMILY_SHADRAMON
    CRY_SHADRAMON,
    CRY_RAIDRAMON,
    CRY_TOGEMON,
#endif //P_FAMILY_SHADRAMON
#if P_FAMILY_GROWLMON
    CRY_GROWLMON,
    CRY_STINGMON,
#endif //P_FAMILY_GROWLMON
#if P_FAMILY_TUSKMON
    CRY_TUSKMON,
    CRY_MONOCHROMON,
#endif //P_FAMILY_TUSKMON
#if P_FAMILY_MEKANORIMON
    CRY_BURMY,
    CRY_WORMADAM,
    CRY_MOTHIM,
#endif //P_FAMILY_MEKANORIMON
#if P_FAMILY_TESLAJELLYMON
    CRY_TESLAJELLYMON,
    CRY_RAREMON,
#endif //P_FAMILY_TESLAJELLYMON
#if P_FAMILY_SUKAMON
    CRY_SUKAMON,
#endif //P_FAMILY_SUKAMON
#if P_FAMILY_SHELLMON
    CRY_SHELLMON,
    CRY_STARMON,
#endif //P_FAMILY_SHELLMON
#if P_FAMILY_TORTOMON
    CRY_TORTOMON,
    CRY_CHERRIM,
#endif //P_FAMILY_TORTOMON
#if P_FAMILY_SHELLOS
    CRY_SHELLOS,
    CRY_GASTRODON,
#endif //P_FAMILY_SHELLOS
#if P_FAMILY_GUARDROMON
    CRY_GUARDROMON,
    CRY_HONEYBEEMON,
#endif //P_FAMILY_GUARDROMON
#if P_FAMILY_HYOGAMON
    CRY_HYOGAMON,
    CRY_ICEDEVIMON,
#if P_MEGA_EVOLUTIONS
    CRY_ICEDEVIMON_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_HYOGAMON
#if P_FAMILY_ICEMON
    CRY_ICEMON,
    CRY_NINJAMON,
#endif //P_FAMILY_ICEMON
#if P_FAMILY_JUNGLEMOJYAMON
    CRY_JUNGLEMOJYAMON,
    CRY_SHELLNUMEMON,
#endif //P_FAMILY_JUNGLEMOJYAMON
#if P_FAMILY_KIWIMON
    CRY_KIWIMON,
    CRY_MORISHELLMON,
#endif //P_FAMILY_KIWIMON
#if P_FAMILY_MUSYAMON
    CRY_MUSYAMON,
#endif //P_FAMILY_MUSYAMON
#if P_FAMILY_NISEDRIMOGEMON
    CRY_NISEDRIMOGEMON,
#endif //P_FAMILY_NISEDRIMOGEMON
#if P_FAMILY_ORCAMON
    CRY_ORCAMON,
    CRY_PIDMON,
    CRY_GARCHOMP,
#if P_MEGA_EVOLUTIONS
    CRY_GARCHOMP_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_ORCAMON
#if P_FAMILY_RIOLU
    CRY_RIOLU,
    CRY_LUCARIO,
#if P_MEGA_EVOLUTIONS
    CRY_LUCARIO_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_RIOLU
#if P_FAMILY_HIPPOPOTAS
    CRY_HIPPOPOTAS,
    CRY_HIPPOWDON,
#endif //P_FAMILY_HIPPOPOTAS
#if P_FAMILY_SKORUPI
    CRY_SKORUPI,
    CRY_DRAPION,
#endif //P_FAMILY_SKORUPI
#if P_FAMILY_CROAGUNK
    CRY_CROAGUNK,
    CRY_TOXICROAK,
#endif //P_FAMILY_CROAGUNK
#if P_FAMILY_CARNIVINE
    CRY_CARNIVINE,
#endif //P_FAMILY_CARNIVINE
#if P_FAMILY_FINNEON
    CRY_FINNEON,
    CRY_LUMINEON,
#endif //P_FAMILY_FINNEON
#if P_FAMILY_SNOVER
    CRY_SNOVER,
    CRY_ABOMASNOW,
#if P_MEGA_EVOLUTIONS
    CRY_ABOMASNOW_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_SNOVER
#if P_FAMILY_ROTOM
    CRY_ROTOM,
#endif //P_FAMILY_ROTOM
#if P_FAMILY_UXIE
    CRY_UXIE,
#endif //P_FAMILY_UXIE
#if P_FAMILY_MESPRIT
    CRY_MESPRIT,
#endif //P_FAMILY_MESPRIT
#if P_FAMILY_AZELF
    CRY_AZELF,
#endif //P_FAMILY_AZELF
#if P_FAMILY_DIALGA
    CRY_DIALGA,
#endif //P_FAMILY_DIALGA
#if P_FAMILY_PALKIA
    CRY_PALKIA,
#endif //P_FAMILY_PALKIA
#if P_FAMILY_HEATRAN
    CRY_HEATRAN,
#endif //P_FAMILY_HEATRAN
#if P_FAMILY_REGIGIGAS
    CRY_REGIGIGAS,
#endif //P_FAMILY_REGIGIGAS
#if P_FAMILY_GIRATINA
    CRY_GIRATINA,
#endif //P_FAMILY_GIRATINA
#if P_FAMILY_CRESSELIA
    CRY_CRESSELIA,
#endif //P_FAMILY_CRESSELIA
#if P_FAMILY_MANAPHY
    CRY_PHIONE,
    CRY_MANAPHY,
#endif //P_FAMILY_MANAPHY
#if P_FAMILY_DARKRAI
    CRY_DARKRAI,
#endif //P_FAMILY_DARKRAI
#if P_FAMILY_SHAYMIN
    CRY_SHAYMIN_LAND,
    CRY_SHAYMIN_SKY,
#endif //P_FAMILY_SHAYMIN
#if P_FAMILY_ARCEUS
    CRY_ARCEUS,
#endif //P_FAMILY_ARCEUS
#if P_FAMILY_D_AIRDRAMON
    CRY_D_AIRDRAMON,
#endif //P_FAMILY_D_AIRDRAMON
#if P_FAMILY_D_DEVIMON
    CRY_D_DEVIMON,
    CRY_D_MERAMON_CMON_DIGIMON,
    CRY_D_METALGREYMON,
#endif //P_FAMILY_D_DEVIMON
#if P_FAMILY_D_TYRANNOMON
    CRY_D_TYRANNOMON,
    CRY_MAMEMON,
    CRY_METALGREYMON_VIRUS,
#endif //P_FAMILY_D_TYRANNOMON
#if P_FAMILY_METALMAMEMON
    CRY_METALMAMEMON,
    CRY_MONZAEMON,
    CRY_SKULLGREYMON,
#endif //P_FAMILY_METALMAMEMON
#if P_FAMILY_ANDROMON
    CRY_ANDROMON,
    CRY_ANGEWOMON,
#endif //P_FAMILY_ANDROMON
#if P_FAMILY_SCORPIOMON
    CRY_SCORPIOMON,
    CRY_MEGAKABUTERIMON_BLUE,
    CRY_DRAGOMON,
#endif //P_FAMILY_SCORPIOMON
#if P_FAMILY_DIGITAMAMON
    CRY_DIGITAMAMON,
    CRY_ETEMON,
#endif //P_FAMILY_DIGITAMAMON
#if P_FAMILY_EXTYRANNOMON
    CRY_EXTYRANNOMON,
    CRY_GIROMON,
#endif //P_FAMILY_EXTYRANNOMON
#if P_FAMILY_MAGNAANGEMON
    CRY_MAGNAANGEMON,
    CRY_MAGNAANGEMON_PRIESTMODE,
#endif //P_FAMILY_MAGNAANGEMON
#if P_FAMILY_JAGAMON
    CRY_JAGAMON,
    CRY_LADYDEVIMON,
#endif //P_FAMILY_JAGAMON
#if P_FAMILY_MAMMOTHMON
    CRY_MAMMOTHMON,
    CRY_METALGREYMON,
#endif //P_FAMILY_MAMMOTHMON
#if P_FAMILY_WEREGARURUMON
    CRY_WEREGARURUMON,
    CRY_DINOBEEMON,
    CRY_PAILDRAMON,
#endif //P_FAMILY_WEREGARURUMON
#if P_FAMILY_WARGROWLMON
    CRY_WARGROWLMON,
    CRY_LILLYMON,
#endif //P_FAMILY_WARGROWLMON
#if P_FAMILY_MASTERTYRANNOMON
    CRY_MASTERTYRANNOMON,
    CRY_TRICERAMON,
    CRY_ARUKENIMON,
#endif //P_FAMILY_MASTERTYRANNOMON
#if P_FAMILY_MARINEDEVIMON
    CRY_MARINEDEVIMON,
    CRY_MEGASEADRAMON,
#endif //P_FAMILY_MARINEDEVIMON
#if P_FAMILY_MEGADRAMON
    CRY_MEGADRAMON,
    CRY_METALTYRANNOMON,
#endif //P_FAMILY_MEGADRAMON
#if P_FAMILY_DATAMON
    CRY_DATAMON,
#if P_MEGA_EVOLUTIONS
    CRY_OKUWAMON,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_DATAMON
#if P_FAMILY_PUMPKINMON
    CRY_PUMPKINMON,
    CRY_PIXIMON,
    CRY_SHOGUNGEKOMON,
#endif //P_FAMILY_PUMPKINMON
#if P_FAMILY_ZUDOMON
    CRY_ZUDOMON,
    CRY_AEROVEEDRAMON,
    CRY_ASURAMON,
#endif //P_FAMILY_ZUDOMON
#if P_FAMILY_MEGAKABUTERIMON_RED
    CRY_MEGAKABUTERIMON_RED,
#endif //P_FAMILY_MEGAKABUTERIMON_RED
#if P_FAMILY_BIGMAMEMON
    CRY_BIGMAMEMON,
#endif //P_FAMILY_BIGMAMEMON
#if P_FAMILY_TINMON
    CRY_TINMON,
    CRY_BLOSSOMON,
    CRY_BLUEMERAMON,
#endif //P_FAMILY_TINMON
#if P_FAMILY_BRACHIOMON
    CRY_BRACHIOMON,
    CRY_KIMERAMON,
    CRY_CYBERDRAMON,
#endif //P_FAMILY_BRACHIOMON
#if P_FAMILY_SKULLMERAMON
    CRY_SKULLMERAMON,
    CRY_DERAMON,
#endif //P_FAMILY_SKULLMERAMON
#if P_FAMILY_PHANTOMON
    CRY_PHANTOMON,
    CRY_GARUDAMON,
#endif //P_FAMILY_PHANTOMON
#if P_FAMILY_GIGADRAMON
    CRY_GIGADRAMON,
#if P_HISUIAN_FORMS
    CRY_BASCULEGION,
#endif //P_HISUIAN_FORMS
#endif //P_FAMILY_GIGADRAMON
#if P_FAMILY_KINGSUKAMON
    CRY_KINGSUKAMON,
    CRY_DIVERMON,
    CRY_METEORMON,
#endif //P_FAMILY_KINGSUKAMON
#if P_FAMILY_CHERRYMON
    CRY_CHERRYMON,
    CRY_DARMANITAN,
#endif //P_FAMILY_CHERRYMON
#if P_FAMILY_KNIGHTMON
    CRY_KNIGHTMON,
#endif //P_FAMILY_KNIGHTMON
#if P_FAMILY_MUMMYMON
    CRY_MUMMYMON,
    CRY_OROCHIMON,
#endif //P_FAMILY_MUMMYMON
#if P_FAMILY_ICELEOMON
    CRY_ICELEOMON,
    CRY_PARROTMON,
#endif //P_FAMILY_ICELEOMON
#if P_FAMILY_SIGILYPH
    CRY_SIGILYPH,
#endif //P_FAMILY_SIGILYPH
#if P_FAMILY_YAMASK
    CRY_YAMASK,
    CRY_COFAGRIGUS,
#if P_GALARIAN_FORMS
    CRY_RUNERIGUS,
#endif //P_GALARIAN_FORMS
#endif //P_FAMILY_YAMASK
#if P_FAMILY_TIRTOUGA
    CRY_TIRTOUGA,
    CRY_CARRACOSTA,
#endif //P_FAMILY_TIRTOUGA
#if P_FAMILY_ARCHEN
    CRY_ARCHEN,
    CRY_ARCHEOPS,
#endif //P_FAMILY_ARCHEN
#if P_FAMILY_TRUBBISH
    CRY_TRUBBISH,
    CRY_GARBODOR,
#endif //P_FAMILY_TRUBBISH
#if P_FAMILY_ZORUA
    CRY_ZORUA,
    CRY_ZOROARK,
#endif //P_FAMILY_ZORUA
#if P_FAMILY_MINCCINO
    CRY_MINCCINO,
    CRY_CINCCINO,
#endif //P_FAMILY_MINCCINO
#if P_FAMILY_GOTHITA
    CRY_GOTHITA,
    CRY_GOTHORITA,
    CRY_GOTHITELLE,
#endif //P_FAMILY_GOTHITA
#if P_FAMILY_SOLOSIS
    CRY_SOLOSIS,
    CRY_DUOSION,
    CRY_REUNICLUS,
#endif //P_FAMILY_SOLOSIS
#if P_FAMILY_DUCKLETT
    CRY_DUCKLETT,
    CRY_SWANNA,
#endif //P_FAMILY_DUCKLETT
#if P_FAMILY_VANILLITE
    CRY_VANILLITE,
    CRY_VANILLISH,
    CRY_VANILLUXE,
#endif //P_FAMILY_VANILLITE
#if P_FAMILY_DEERLING
    CRY_DEERLING,
    CRY_SAWSBUCK,
#endif //P_FAMILY_DEERLING
#if P_FAMILY_EMOLGA
    CRY_EMOLGA,
#endif //P_FAMILY_EMOLGA
#if P_FAMILY_KARRABLAST
    CRY_KARRABLAST,
    CRY_ESCAVALIER,
#endif //P_FAMILY_KARRABLAST
#if P_FAMILY_FOONGUS
    CRY_FOONGUS,
    CRY_AMOONGUSS,
#endif //P_FAMILY_FOONGUS
#if P_FAMILY_FRILLISH
    CRY_FRILLISH,
    CRY_JELLICENT,
#endif //P_FAMILY_FRILLISH
#if P_FAMILY_ALOMOMOLA
    CRY_ALOMOMOLA,
#endif //P_FAMILY_ALOMOMOLA
#if P_FAMILY_JOLTIK
    CRY_JOLTIK,
    CRY_GALVANTULA,
#endif //P_FAMILY_JOLTIK
#if P_FAMILY_FERROSEED
    CRY_FERROSEED,
    CRY_FERROTHORN,
#endif //P_FAMILY_FERROSEED
#if P_FAMILY_KLINK
    CRY_KLINK,
    CRY_KLANG,
    CRY_KLINKLANG,
#endif //P_FAMILY_KLINK
#if P_FAMILY_TYNAMO
    CRY_TYNAMO,
    CRY_EELEKTRIK,
    CRY_EELEKTROSS,
#endif //P_FAMILY_TYNAMO
#if P_FAMILY_ELGYEM
    CRY_ELGYEM,
    CRY_BEHEEYEM,
#endif //P_FAMILY_ELGYEM
#if P_FAMILY_LITWICK
    CRY_LITWICK,
    CRY_LAMPENT,
    CRY_CHANDELURE,
#endif //P_FAMILY_LITWICK
#if P_FAMILY_AXEW
    CRY_AXEW,
    CRY_FRAXURE,
    CRY_HAXORUS,
#endif //P_FAMILY_AXEW
#if P_FAMILY_CUBCHOO
    CRY_CUBCHOO,
    CRY_BEARTIC,
#endif //P_FAMILY_CUBCHOO
#if P_FAMILY_CRYOGONAL
    CRY_CRYOGONAL,
#endif //P_FAMILY_CRYOGONAL
#if P_FAMILY_SHELMET
    CRY_SHELMET,
    CRY_ACCELGOR,
#endif //P_FAMILY_SHELMET
#if P_FAMILY_STUNFISK
    CRY_STUNFISK,
#endif //P_FAMILY_STUNFISK
#if P_FAMILY_MIENFOO
    CRY_MIENFOO,
    CRY_MIENSHAO,
#endif //P_FAMILY_MIENFOO
#if P_FAMILY_DRUDDIGON
    CRY_DRUDDIGON,
#endif //P_FAMILY_DRUDDIGON
#if P_FAMILY_GOLETT
    CRY_GOLETT,
    CRY_GOLURK,
#endif //P_FAMILY_GOLETT
#if P_FAMILY_PAWNIARD
    CRY_PAWNIARD,
    CRY_BISHARP,
#if P_GEN_9_CROSS_EVOS
    CRY_KINGAMBIT,
#endif //P_GEN_9_CROSS_EVOS
#endif //P_FAMILY_PAWNIARD
#if P_FAMILY_BOUFFALANT
    CRY_BOUFFALANT,
#endif //P_FAMILY_BOUFFALANT
#if P_FAMILY_RUFFLET
    CRY_RUFFLET,
    CRY_BRAVIARY,
#endif //P_FAMILY_RUFFLET
#if P_FAMILY_VULLABY
    CRY_VULLABY,
    CRY_MANDIBUZZ,
#endif //P_FAMILY_VULLABY
#if P_FAMILY_HEATMOR
    CRY_HEATMOR,
#endif //P_FAMILY_HEATMOR
#if P_FAMILY_DURANT
    CRY_DURANT,
#endif //P_FAMILY_DURANT
#if P_FAMILY_DEINO
    CRY_DEINO,
    CRY_ZWEILOUS,
    CRY_HYDREIGON,
#endif //P_FAMILY_DEINO
#if P_FAMILY_LARVESTA
    CRY_LARVESTA,
    CRY_VOLCARONA,
#endif //P_FAMILY_LARVESTA
#if P_FAMILY_COBALION
    CRY_COBALION,
#endif //P_FAMILY_COBALION
#if P_FAMILY_TERRAKION
    CRY_TERRAKION,
#endif //P_FAMILY_TERRAKION
#if P_FAMILY_VIRIZION
    CRY_VIRIZION,
#endif //P_FAMILY_VIRIZION
#if P_FAMILY_TORNADUS
    CRY_TORNADUS_INCARNATE,
    CRY_TORNADUS_THERIAN,
#endif //P_FAMILY_TORNADUS
#if P_FAMILY_THUNDURUS
    CRY_THUNDURUS_INCARNATE,
    CRY_THUNDURUS_THERIAN,
#endif //P_FAMILY_THUNDURUS
#if P_FAMILY_RESHIRAM
    CRY_RESHIRAM,
#endif //P_FAMILY_RESHIRAM
#if P_FAMILY_ZEKROM
    CRY_ZEKROM,
#endif //P_FAMILY_ZEKROM
#if P_FAMILY_LANDORUS
    CRY_LANDORUS_INCARNATE,
    CRY_LANDORUS_THERIAN,
#endif //P_FAMILY_LANDORUS
#if P_FAMILY_KYUREM
    CRY_KYUREM,
#if P_FUSION_FORMS
    CRY_KYUREM_WHITE,
    CRY_KYUREM_BLACK,
#endif //P_FUSION_FORMS
#endif //P_FAMILY_KYUREM
#if P_FAMILY_KELDEO
    CRY_KELDEO,
#endif //P_FAMILY_KELDEO
#if P_FAMILY_MELOETTA
    CRY_MELOETTA,
#endif //P_FAMILY_MELOETTA
#if P_FAMILY_GENESECT
    CRY_GENESECT,
#endif //P_FAMILY_GENESECT
#if P_FAMILY_HERCULESKABUTERIMON
    CRY_HERCULESKABUTERIMON,
    CRY_MAGNADRAMON,
    CRY_MAGNAMON,
#endif //P_FAMILY_HERCULESKABUTERIMON
#if P_FAMILY_WARGREYMON
    CRY_WARGREYMON,
    CRY_METALGARURUMON,
    CRY_OMNIMON,
#endif //P_FAMILY_WARGREYMON
#if P_FAMILY_CRESGARURUMON
    CRY_CRESGARURUMON,
    CRY_BLITZGREYMON,
    CRY_BIOSUPINOMON,
#endif //P_FAMILY_CRESGARURUMON
#if P_FAMILY_ROSEMON
    CRY_ROSEMON,
    CRY_DINOREXMON,
#endif //P_FAMILY_ROSEMON
#if P_FAMILY_DINOMON
    CRY_DINOMON,
    CRY_MARINEANGEMON,
    CRY_METALETEMON,
#endif //P_FAMILY_DINOMON
#if P_FAMILY_METALSEADRAMON
    CRY_METALSEADRAMON,
    CRY_PUKUMON,
    CRY_SABERLEOMON,
#endif //P_FAMILY_METALSEADRAMON
#if P_FAMILY_APOCALYMON
    CRY_APOCALYMON,
    CRY_BABAMON,
#endif //P_FAMILY_APOCALYMON
#if P_FAMILY_FLABEBE
    CRY_FLABEBE,
    CRY_FLOETTE,
    CRY_FLOETTE_ETERNAL,
    CRY_FLORGES,
#endif //P_FAMILY_FLABEBE
#if P_FAMILY_BOLTMON
    CRY_BOLTMON,
    CRY_CREEPYMON,
#endif //P_FAMILY_BOLTMON
#if P_FAMILY_DEVITAMAMON
    CRY_DEVITAMAMON,
    CRY_DIABOROMON,
#endif //P_FAMILY_DEVITAMAMON
#if P_FAMILY_FURFROU
    CRY_FURFROU,
#endif //P_FAMILY_FURFROU
#if P_FAMILY_GOLDRAMON
    CRY_GOLDRAMON,
    CRY_GURURUMON,
#endif //P_FAMILY_GOLDRAMON
#if P_FAMILY_PHOENIXMON
    CRY_PHOENIXMON,
    CRY_JIJIMON,
    CRY_AEGISLASH,
#endif //P_FAMILY_PHOENIXMON
#if P_FAMILY_KINGETEMON
    CRY_KINGETEMON,
    CRY_MILLENNIUMMON,
#endif //P_FAMILY_KINGETEMON
#if P_FAMILY_MACHINEDRAMON
    CRY_MACHINEDRAMON,
    CRY_PIEDMON,
#endif //P_FAMILY_MACHINEDRAMON
#if P_FAMILY_PUPPETMON
    CRY_PUPPETMON,
    CRY_MALAMAR,
#endif //P_FAMILY_PUPPETMON
#if P_FAMILY_BINACLE
    CRY_BINACLE,
    CRY_BARBARACLE,
#endif //P_FAMILY_BINACLE
#if P_FAMILY_SKRELP
    CRY_SKRELP,
    CRY_DRAGALGE,
#endif //P_FAMILY_SKRELP
#if P_FAMILY_CLAUNCHER
    CRY_CLAUNCHER,
    CRY_CLAWITZER,
#endif //P_FAMILY_CLAUNCHER
#if P_FAMILY_HELIOPTILE
    CRY_HELIOPTILE,
    CRY_HELIOLISK,
#endif //P_FAMILY_HELIOPTILE
#if P_FAMILY_TYRUNT
    CRY_TYRUNT,
    CRY_TYRANTRUM,
#endif //P_FAMILY_TYRUNT
#if P_FAMILY_AMAURA
    CRY_AMAURA,
    CRY_AURORUS,
#endif //P_FAMILY_AMAURA
#if P_FAMILY_HAWLUCHA
    CRY_HAWLUCHA,
#endif //P_FAMILY_HAWLUCHA
#if P_FAMILY_DEDENNE
    CRY_DEDENNE,
#endif //P_FAMILY_DEDENNE
#if P_FAMILY_CARBINK
    CRY_CARBINK,
#endif //P_FAMILY_CARBINK
#if P_FAMILY_GOOMY
    CRY_GOOMY,
    CRY_SLIGGOO,
    CRY_GOODRA,
#endif //P_FAMILY_GOOMY
#if P_FAMILY_KLEFKI
    CRY_KLEFKI,
#endif //P_FAMILY_KLEFKI
#if P_FAMILY_PHANTUMP
    CRY_PHANTUMP,
    CRY_TREVENANT,
#endif //P_FAMILY_PHANTUMP
#if P_FAMILY_PUMPKABOO
    CRY_PUMPKABOO,
    CRY_PUMPKABOO_SUPER,
    CRY_GOURGEIST,
    CRY_GOURGEIST_SUPER,
#endif //P_FAMILY_PUMPKABOO
#if P_FAMILY_BERGMITE
    CRY_BERGMITE,
    CRY_AVALUGG,
#endif //P_FAMILY_BERGMITE
#if P_FAMILY_NOIBAT
    CRY_NOIBAT,
    CRY_NOIVERN,
#endif //P_FAMILY_NOIBAT
#if P_FAMILY_XERNEAS
    CRY_XERNEAS,
#endif //P_FAMILY_XERNEAS
#if P_FAMILY_YVELTAL
    CRY_YVELTAL,
#endif //P_FAMILY_YVELTAL
#if P_FAMILY_ZYGARDE
    CRY_ZYGARDE_50,
    CRY_ZYGARDE_10,
    CRY_ZYGARDE_COMPLETE,
#endif //P_FAMILY_ZYGARDE
#if P_FAMILY_DIANCIE
    CRY_DIANCIE,
#if P_MEGA_EVOLUTIONS
    CRY_DIANCIE_MEGA,
#endif //P_MEGA_EVOLUTIONS
#endif //P_FAMILY_DIANCIE
#if P_FAMILY_HOOPA
    CRY_HOOPA_CONFINED,
    CRY_HOOPA_UNBOUND,
#endif //P_FAMILY_HOOPA
#if P_FAMILY_VOLCANION
    CRY_VOLCANION,
#endif //P_FAMILY_VOLCANION
#if P_FAMILY_ROWLET
    CRY_ROWLET,
    CRY_DARTRIX,
    CRY_DECIDUEYE,
#endif //P_FAMILY_ROWLET
#if P_FAMILY_LITTEN
    CRY_LITTEN,
    CRY_TORRACAT,
    CRY_INCINEROAR,
#endif //P_FAMILY_LITTEN
#if P_FAMILY_POPPLIO
    CRY_POPPLIO,
    CRY_BRIONNE,
    CRY_PRIMARINA,
#endif //P_FAMILY_POPPLIO
#if P_FAMILY_PIKIPEK
    CRY_PIKIPEK,
    CRY_TRUMBEAK,
    CRY_TOUCANNON,
#endif //P_FAMILY_PIKIPEK
#if P_FAMILY_YUNGOOS
    CRY_YUNGOOS,
    CRY_GUMSHOOS,
#endif //P_FAMILY_YUNGOOS
#if P_FAMILY_GRUBBIN
    CRY_GRUBBIN,
    CRY_CHARJABUG,
    CRY_VIKAVOLT,
#endif //P_FAMILY_GRUBBIN
#if P_FAMILY_CRABRAWLER
    CRY_CRABRAWLER,
    CRY_CRABOMINABLE,
#endif //P_FAMILY_CRABRAWLER
#if P_FAMILY_ORICORIO
    CRY_ORICORIO_BAILE,
    CRY_ORICORIO_POM_POM,
    CRY_ORICORIO_PAU,
    CRY_ORICORIO_SENSU,
#endif //P_FAMILY_ORICORIO
#if P_FAMILY_CUTIEFLY
    CRY_CUTIEFLY,
    CRY_RIBOMBEE,
#endif //P_FAMILY_CUTIEFLY
#if P_FAMILY_ROCKRUFF
    CRY_ROCKRUFF,
    CRY_LYCANROC_MIDDAY,
    CRY_LYCANROC_MIDNIGHT,
    CRY_LYCANROC_DUSK,
#endif //P_FAMILY_ROCKRUFF
#if P_FAMILY_WISHIWASHI
    CRY_WISHIWASHI_SOLO,
    CRY_WISHIWASHI_SCHOOL,
#endif //P_FAMILY_WISHIWASHI
#if P_FAMILY_MAREANIE
    CRY_MAREANIE,
    CRY_TOXAPEX,
#endif //P_FAMILY_MAREANIE
#if P_FAMILY_MUDBRAY
    CRY_MUDBRAY,
    CRY_MUDSDALE,
#endif //P_FAMILY_MUDBRAY
#if P_FAMILY_DEWPIDER
    CRY_DEWPIDER,
    CRY_ARAQUANID,
#endif //P_FAMILY_DEWPIDER
#if P_FAMILY_FOMANTIS
    CRY_FOMANTIS,
    CRY_LURANTIS,
#endif //P_FAMILY_FOMANTIS
#if P_FAMILY_MORELULL
    CRY_MORELULL,
    CRY_SHIINOTIC,
#endif //P_FAMILY_MORELULL
#if P_FAMILY_SALANDIT
    CRY_SALANDIT,
    CRY_SALAZZLE,
#endif //P_FAMILY_SALANDIT
#if P_FAMILY_STUFFUL
    CRY_STUFFUL,
    CRY_BEWEAR,
#endif //P_FAMILY_STUFFUL
#if P_FAMILY_BOUNSWEET
    CRY_BOUNSWEET,
    CRY_STEENEE,
    CRY_TSAREENA,
#endif //P_FAMILY_BOUNSWEET
#if P_FAMILY_COMFEY
    CRY_COMFEY,
#endif //P_FAMILY_COMFEY
#if P_FAMILY_ORANGURU
    CRY_ORANGURU,
#endif //P_FAMILY_ORANGURU
#if P_FAMILY_PASSIMIAN
    CRY_PASSIMIAN,
#endif //P_FAMILY_PASSIMIAN
#if P_FAMILY_WIMPOD
    CRY_WIMPOD,
    CRY_GOLISOPOD,
#endif //P_FAMILY_WIMPOD
#if P_FAMILY_SANDYGAST
    CRY_SANDYGAST,
    CRY_PALOSSAND,
#endif //P_FAMILY_SANDYGAST
#if P_FAMILY_PYUKUMUKU
    CRY_PYUKUMUKU,
#endif //P_FAMILY_PYUKUMUKU
#if P_FAMILY_TYPE_NULL
    CRY_TYPE_NULL,
    CRY_SILVALLY,
#endif //P_FAMILY_TYPE_NULL
#if P_FAMILY_MINIOR
    CRY_MINIOR,
#endif //P_FAMILY_MINIOR
#if P_FAMILY_KOMALA
    CRY_KOMALA,
#endif //P_FAMILY_KOMALA
#if P_FAMILY_TURTONATOR
    CRY_TURTONATOR,
#endif //P_FAMILY_TURTONATOR
#if P_FAMILY_TOGEDEMARU
    CRY_TOGEDEMARU,
#endif //P_FAMILY_TOGEDEMARU
#if P_FAMILY_MIMIKYU
    CRY_MIMIKYU,
#endif //P_FAMILY_MIMIKYU
#if P_FAMILY_BRUXISH
    CRY_BRUXISH,
#endif //P_FAMILY_BRUXISH
#if P_FAMILY_DRAMPA
    CRY_DRAMPA,
#endif //P_FAMILY_DRAMPA
#if P_FAMILY_DHELMISE
    CRY_DHELMISE,
#endif //P_FAMILY_DHELMISE
#if P_FAMILY_JANGMO_O
    CRY_JANGMO_O,
    CRY_HAKAMO_O,
    CRY_KOMMO_O,
#endif //P_FAMILY_JANGMO_O
#if P_FAMILY_TAPU_KOKO
    CRY_TAPU_KOKO,
#endif //P_FAMILY_TAPU_KOKO
#if P_FAMILY_TAPU_LELE
    CRY_TAPU_LELE,
#endif //P_FAMILY_TAPU_LELE
#if P_FAMILY_TAPU_BULU
    CRY_TAPU_BULU,
#endif //P_FAMILY_TAPU_BULU
#if P_FAMILY_TAPU_FINI
    CRY_TAPU_FINI,
#endif //P_FAMILY_TAPU_FINI
#if P_FAMILY_COSMOG
    CRY_COSMOG,
    CRY_COSMOEM,
    CRY_SOLGALEO,
    CRY_LUNALA,
#endif //P_FAMILY_COSMOG
#if P_FAMILY_NIHILEGO
    CRY_NIHILEGO,
#endif //P_FAMILY_NIHILEGO
#if P_FAMILY_BUZZWOLE
    CRY_BUZZWOLE,
#endif //P_FAMILY_BUZZWOLE
#if P_FAMILY_PHEROMOSA
    CRY_PHEROMOSA,
#endif //P_FAMILY_PHEROMOSA
#if P_FAMILY_XURKITREE
    CRY_XURKITREE,
#endif //P_FAMILY_XURKITREE
#if P_FAMILY_CELESTEELA
    CRY_CELESTEELA,
#endif //P_FAMILY_CELESTEELA
#if P_FAMILY_KARTANA
    CRY_KARTANA,
#endif //P_FAMILY_KARTANA
#if P_FAMILY_GUZZLORD
    CRY_GUZZLORD,
#endif //P_FAMILY_GUZZLORD
#if P_FAMILY_NECROZMA
    CRY_NECROZMA,
#if P_FUSION_FORMS
    CRY_NECROZMA_DUSK_MANE,
    CRY_NECROZMA_DAWN_WINGS,
#if P_ULTRA_BURST_FORMS
    CRY_NECROZMA_ULTRA,
#endif //P_ULTRA_BURST_FORMS
#endif //P_FUSION_FORMS
#endif //P_FAMILY_NECROZMA
#if P_FAMILY_MAGEARNA
    CRY_MAGEARNA,
#endif //P_FAMILY_MAGEARNA
#if P_FAMILY_MARSHADOW
    CRY_MARSHADOW,
#endif //P_FAMILY_MARSHADOW
#if P_FAMILY_POIPOLE
    CRY_POIPOLE,
    CRY_NAGANADEL,
#endif //P_FAMILY_POIPOLE
#if P_FAMILY_STAKATAKA
    CRY_STAKATAKA,
#endif //P_FAMILY_STAKATAKA
#if P_FAMILY_BLACEPHALON
    CRY_BLACEPHALON,
#endif //P_FAMILY_BLACEPHALON
#if P_FAMILY_ZERAORA
    CRY_ZERAORA,
#endif //P_FAMILY_ZERAORA
#if P_FAMILY_MELTAN
    CRY_MELTAN,
    CRY_MELMETAL,
#endif //P_FAMILY_MELTAN
#if P_FAMILY_TOMORIMON
    CRY_TOMORIMON,
    CRY_ONIBIMON,
    CRY_RILLABOOM,
#endif //P_FAMILY_TOMORIMON
#if P_FAMILY_SCORBUNNY
    CRY_SCORBUNNY,
    CRY_RABOOT,
    CRY_CINDERACE,
#endif //P_FAMILY_SCORBUNNY
#if P_FAMILY_SOBBLE
    CRY_SOBBLE,
    CRY_DRIZZILE,
    CRY_INTELEON,
#endif //P_FAMILY_SOBBLE
#if P_FAMILY_SKWOVET
    CRY_SKWOVET,
    CRY_GREEDENT,
#endif //P_FAMILY_SKWOVET
#if P_FAMILY_ROOKIDEE
    CRY_ROOKIDEE,
    CRY_CORVISQUIRE,
    CRY_CORVIKNIGHT,
#endif //P_FAMILY_ROOKIDEE
#if P_FAMILY_BLIPBUG
    CRY_BLIPBUG,
    CRY_DOTTLER,
    CRY_ORBEETLE,
#endif //P_FAMILY_BLIPBUG
#if P_FAMILY_NICKIT
    CRY_NICKIT,
    CRY_THIEVUL,
#endif //P_FAMILY_NICKIT
#if P_FAMILY_GOSSIFLEUR
    CRY_GOSSIFLEUR,
    CRY_ELDEGOSS,
#endif //P_FAMILY_GOSSIFLEUR
#if P_FAMILY_WOOLOO
    CRY_WOOLOO,
    CRY_DUBWOOL,
#endif //P_FAMILY_WOOLOO
#if P_FAMILY_CHEWTLE
    CRY_CHEWTLE,
    CRY_DREDNAW,
#endif //P_FAMILY_CHEWTLE
#if P_FAMILY_YAMPER
    CRY_YAMPER,
    CRY_BOLTUND,
#endif //P_FAMILY_YAMPER
#if P_FAMILY_ROLYCOLY
    CRY_ROLYCOLY,
    CRY_CARKOL,
    CRY_COALOSSAL,
#endif //P_FAMILY_ROLYCOLY
#if P_FAMILY_APPLIN
    CRY_APPLIN,
    CRY_FLAPPLE,
    CRY_APPLETUN,
#if P_GEN_9_CROSS_EVOS
    CRY_DIPPLIN,
    CRY_HYDRAPPLE,
#endif //P_GEN_9_CROSS_EVOS
#endif //P_FAMILY_APPLIN
#if P_FAMILY_SILICOBRA
    CRY_SILICOBRA,
    CRY_SANDACONDA,
#endif //P_FAMILY_SILICOBRA
#if P_FAMILY_CRAMORANT
    CRY_CRAMORANT,
#endif //P_FAMILY_CRAMORANT
#if P_FAMILY_ARROKUDA
    CRY_ARROKUDA,
    CRY_BARRASKEWDA,
#endif //P_FAMILY_ARROKUDA
#if P_FAMILY_TOXEL
    CRY_TOXEL,
    CRY_TOXTRICITY_AMPED,
    CRY_TOXTRICITY_LOW_KEY,
#endif //P_FAMILY_TOXEL
#if P_FAMILY_SIZZLIPEDE
    CRY_SIZZLIPEDE,
    CRY_CENTISKORCH,
#endif //P_FAMILY_SIZZLIPEDE
#if P_FAMILY_CLOBBOPUS
    CRY_CLOBBOPUS,
    CRY_GRAPPLOCT,
#endif //P_FAMILY_CLOBBOPUS
#if P_FAMILY_SINISTEA
    CRY_SINISTEA,
    CRY_POLTEAGEIST,
#endif //P_FAMILY_SINISTEA
#if P_FAMILY_HATENNA
    CRY_HATENNA,
    CRY_HATTREM,
    CRY_HATTERENE,
#endif //P_FAMILY_HATENNA
#if P_FAMILY_IMPIDIMP
    CRY_IMPIDIMP,
    CRY_MORGREM,
    CRY_GRIMMSNARL,
#endif //P_FAMILY_IMPIDIMP
#if P_FAMILY_MILCERY
    CRY_MILCERY,
    CRY_ALCREMIE,
#endif //P_FAMILY_MILCERY
#if P_FAMILY_FALINKS
    CRY_FALINKS,
#endif //P_FAMILY_FALINKS
#if P_FAMILY_PINCURCHIN
    CRY_PINCURCHIN,
#endif //P_FAMILY_PINCURCHIN
#if P_FAMILY_SNOM
    CRY_SNOM,
    CRY_FROSMOTH,
#endif //P_FAMILY_SNOM
#if P_FAMILY_STONJOURNER
    CRY_STONJOURNER,
#endif //P_FAMILY_STONJOURNER
#if P_FAMILY_EISCUE
    CRY_EISCUE_ICE,
    CRY_EISCUE_NOICE_FACE,
#endif //P_FAMILY_EISCUE
#if P_FAMILY_INDEEDEE
    CRY_INDEEDEE_M,
    CRY_INDEEDEE_F,
#endif //P_FAMILY_INDEEDEE
#if P_FAMILY_MORPEKO
    CRY_MORPEKO_FULL_BELLY,
    CRY_MORPEKO_HANGRY,
#endif //P_FAMILY_MORPEKO
#if P_FAMILY_CUFANT
    CRY_CUFANT,
    CRY_COPPERAJAH,
#endif //P_FAMILY_CUFANT
#if P_FAMILY_DRACOZOLT
    CRY_DRACOZOLT,
#endif //P_FAMILY_DRACOZOLT
#if P_FAMILY_ARCTOZOLT
    CRY_ARCTOZOLT,
#endif //P_FAMILY_ARCTOZOLT
#if P_FAMILY_DRACOVISH
    CRY_DRACOVISH,
#endif //P_FAMILY_DRACOVISH
#if P_FAMILY_ARCTOVISH
    CRY_ARCTOVISH,
#endif //P_FAMILY_ARCTOVISH
#if P_FAMILY_DURALUDON
    CRY_DURALUDON,
#if P_GEN_9_CROSS_EVOS
    CRY_ARCHALUDON,
#endif //P_GEN_9_CROSS_EVOS
#endif //P_FAMILY_DURALUDON
#if P_FAMILY_DREEPY
    CRY_DREEPY,
    CRY_DRAKLOAK,
    CRY_DRAGAPULT,
#endif //P_FAMILY_DREEPY
#if P_FAMILY_ZACIAN
    CRY_ZACIAN_HERO,
    CRY_ZACIAN_CROWNED,
#endif //P_FAMILY_ZACIAN
#if P_FAMILY_ZAMAZENTA
    CRY_ZAMAZENTA_HERO,
    CRY_ZAMAZENTA_CROWNED,
#endif //P_FAMILY_ZAMAZENTA
#if P_FAMILY_ETERNATUS
    CRY_ETERNATUS,
    CRY_ETERNATUS_ETERNAMAX,
#endif //P_FAMILY_ETERNATUS
#if P_FAMILY_KUBFU
    CRY_KUBFU,
    CRY_URSHIFU_SINGLE_STRIKE,
    CRY_URSHIFU_RAPID_STRIKE,
#endif //P_FAMILY_KUBFU
#if P_FAMILY_ZARUDE
    CRY_ZARUDE,
#endif //P_FAMILY_ZARUDE
#if P_FAMILY_REGIELEKI
    CRY_REGIELEKI,
#endif //P_FAMILY_REGIELEKI
#if P_FAMILY_REGIDRAGO
    CRY_REGIDRAGO,
#endif //P_FAMILY_REGIDRAGO
#if P_FAMILY_GLASTRIER
    CRY_GLASTRIER,
#endif //P_FAMILY_GLASTRIER
#if P_FAMILY_SPECTRIER
    CRY_SPECTRIER,
#endif //P_FAMILY_SPECTRIER
#if P_FAMILY_CALYREX
    CRY_CALYREX,
#if P_FUSION_FORMS
    CRY_CALYREX_ICE,
    CRY_CALYREX_SHADOW,
#endif //P_FUSION_FORMS
#endif //P_FAMILY_CALYREX
#if P_FAMILY_ENAMORUS
    CRY_ENAMORUS_INCARNATE,
    CRY_ENAMORUS_THERIAN,
#endif //P_FAMILY_ENAMORUS
#if P_FAMILY_SPRIGATITO
    CRY_SPRIGATITO,
    CRY_FLORAGATO,
    CRY_MEOWSCARADA,
#endif //P_FAMILY_SPRIGATITO
#if P_FAMILY_FUECOCO
    CRY_FUECOCO,
    CRY_CROCALOR,
    CRY_SKELEDIRGE,
#endif //P_FAMILY_FUECOCO
#if P_FAMILY_QUAXLY
    CRY_QUAXLY,
    CRY_QUAXWELL,
    CRY_QUAQUAVAL,
#endif //P_FAMILY_QUAXLY
#if P_FAMILY_LECHONK
    CRY_LECHONK,
    CRY_OINKOLOGNE_M,
    CRY_OINKOLOGNE_F,
#endif //P_FAMILY_LECHONK
#if P_FAMILY_TAROUNTULA
    CRY_TAROUNTULA,
    CRY_SPIDOPS,
#endif //P_FAMILY_TAROUNTULA
#if P_FAMILY_NYMBLE
    CRY_NYMBLE,
    CRY_LOKIX,
#endif //P_FAMILY_NYMBLE
#if P_FAMILY_PAWMI
    CRY_PAWMI,
    CRY_PAWMO,
    CRY_PAWMOT,
#endif //P_FAMILY_PAWMI
#if P_FAMILY_TANDEMAUS
    CRY_TANDEMAUS,
    CRY_MAUSHOLD_THREE,
    CRY_MAUSHOLD_FOUR,
#endif //P_FAMILY_TANDEMAUS
#if P_FAMILY_FIDOUGH
    CRY_FIDOUGH,
    CRY_DACHSBUN,
#endif //P_FAMILY_FIDOUGH
#if P_FAMILY_SMOLIV
    CRY_SMOLIV,
    CRY_DOLLIV,
    CRY_ARBOLIVA,
#endif //P_FAMILY_SMOLIV
#if P_FAMILY_SQUAWKABILLY
    CRY_SQUAWKABILLY,
#endif //P_FAMILY_SQUAWKABILLY
#if P_FAMILY_NACLI
    CRY_NACLI,
    CRY_NACLSTACK,
    CRY_GARGANACL,
#endif //P_FAMILY_NACLI
#if P_FAMILY_CHARCADET
    CRY_CHARCADET,
    CRY_ARMAROUGE,
    CRY_CERULEDGE,
#endif //P_FAMILY_CHARCADET
#if P_FAMILY_TADBULB
    CRY_TADBULB,
    CRY_BELLIBOLT,
#endif //P_FAMILY_TADBULB
#if P_FAMILY_WATTREL
    CRY_WATTREL,
    CRY_KILOWATTREL,
#endif //P_FAMILY_WATTREL
#if P_FAMILY_MASCHIFF
    CRY_MASCHIFF,
    CRY_MABOSSTIFF,
#endif //P_FAMILY_MASCHIFF
#if P_FAMILY_SHROODLE
    CRY_SHROODLE,
    CRY_GRAFAIAI,
#endif //P_FAMILY_SHROODLE
#if P_FAMILY_BRAMBLIN
    CRY_BRAMBLIN,
    CRY_BRAMBLEGHAST,
#endif //P_FAMILY_BRAMBLIN
#if P_FAMILY_TOEDSCOOL
    CRY_TOEDSCOOL,
    CRY_TOEDSCRUEL,
#endif //P_FAMILY_TOEDSCOOL
#if P_FAMILY_KLAWF
    CRY_KLAWF,
#endif //P_FAMILY_KLAWF
#if P_FAMILY_CAPSAKID
    CRY_CAPSAKID,
    CRY_SCOVILLAIN,
#endif //P_FAMILY_CAPSAKID
#if P_FAMILY_RELLOR
    CRY_RELLOR,
    CRY_RABSCA,
#endif //P_FAMILY_RELLOR
#if P_FAMILY_FLITTLE
    CRY_FLITTLE,
    CRY_ESPATHRA,
#endif //P_FAMILY_FLITTLE
#if P_FAMILY_TINKATINK
    CRY_TINKATINK,
    CRY_TINKATUFF,
    CRY_TINKATON,
#endif //P_FAMILY_TINKATINK
#if P_FAMILY_WIGLETT
    CRY_WIGLETT,
    CRY_WUGTRIO,
#endif //P_FAMILY_WIGLETT
#if P_FAMILY_BOMBIRDIER
    CRY_BOMBIRDIER,
#endif //P_FAMILY_BOMBIRDIER
#if P_FAMILY_FINIZEN
    CRY_FINIZEN,
    CRY_PALAFIN_ZERO,
    CRY_PALAFIN_HERO,
#endif //P_FAMILY_FINIZEN
#if P_FAMILY_VAROOM
    CRY_VAROOM,
    CRY_REVAVROOM,
#endif //P_FAMILY_VAROOM
#if P_FAMILY_CYCLIZAR
    CRY_CYCLIZAR,
#endif //P_FAMILY_CYCLIZAR
#if P_FAMILY_ORTHWORM
    CRY_ORTHWORM,
#endif //P_FAMILY_ORTHWORM
#if P_FAMILY_GLIMMET
    CRY_GLIMMET,
    CRY_GLIMMORA,
#endif //P_FAMILY_GLIMMET
#if P_FAMILY_GREAVARD
    CRY_GREAVARD,
    CRY_HOUNDSTONE,
#endif //P_FAMILY_GREAVARD
#if P_FAMILY_FLAMIGO
    CRY_FLAMIGO,
#endif //P_FAMILY_FLAMIGO
#if P_FAMILY_CETODDLE
    CRY_CETODDLE,
    CRY_CETITAN,
#endif //P_FAMILY_CETODDLE
#if P_FAMILY_VELUZA
    CRY_VELUZA,
#endif //P_FAMILY_VELUZA
#if P_FAMILY_DONDOZO
    CRY_DONDOZO,
#endif //P_FAMILY_DONDOZO
#if P_FAMILY_TATSUGIRI
    CRY_TATSUGIRI_CURLY,
    CRY_TATSUGIRI_DROOPY,
    CRY_TATSUGIRI_STRETCHY,
#endif //P_FAMILY_TATSUGIRI
#if P_FAMILY_GREAT_TUSK
    CRY_GREAT_TUSK,
#endif //P_FAMILY_GREAT_TUSK
#if P_FAMILY_SCREAM_TAIL
    CRY_SCREAM_TAIL,
#endif //P_FAMILY_SCREAM_TAIL
#if P_FAMILY_BRUTE_BONNET
    CRY_BRUTE_BONNET,
#endif //P_FAMILY_BRUTE_BONNET
#if P_FAMILY_FLUTTER_MANE
    CRY_FLUTTER_MANE,
#endif //P_FAMILY_FLUTTER_MANE
#if P_FAMILY_SLITHER_WING
    CRY_SLITHER_WING,
#endif //P_FAMILY_SLITHER_WING
#if P_FAMILY_SANDY_SHOCKS
    CRY_SANDY_SHOCKS,
#endif //P_FAMILY_SANDY_SHOCKS
#if P_FAMILY_IRON_TREADS
    CRY_IRON_TREADS,
#endif //P_FAMILY_IRON_TREADS
#if P_FAMILY_IRON_BUNDLE
    CRY_IRON_BUNDLE,
#endif //P_FAMILY_IRON_BUNDLE
#if P_FAMILY_IRON_HANDS
    CRY_IRON_HANDS,
#endif //P_FAMILY_IRON_HANDS
#if P_FAMILY_IRON_JUGULIS
    CRY_IRON_JUGULIS,
#endif //P_FAMILY_IRON_JUGULIS
#if P_FAMILY_IRON_MOTH
    CRY_IRON_MOTH,
#endif //P_FAMILY_IRON_MOTH
#if P_FAMILY_IRON_THORNS
    CRY_IRON_THORNS,
#endif //P_FAMILY_IRON_THORNS
#if P_FAMILY_FRIGIBAX
    CRY_FRIGIBAX,
    CRY_ARCTIBAX,
    CRY_BAXCALIBUR,
#endif //P_FAMILY_FRIGIBAX
#if P_FAMILY_GIMMIGHOUL
    CRY_GIMMIGHOUL,
    CRY_GHOLDENGO,
#endif //P_FAMILY_GIMMIGHOUL
#if P_FAMILY_WO_CHIEN
    CRY_WO_CHIEN,
#endif //P_FAMILY_WO_CHIEN
#if P_FAMILY_CHIEN_PAO
    CRY_CHIEN_PAO,
#endif //P_FAMILY_CHIEN_PAO
#if P_FAMILY_TING_LU
    CRY_TING_LU,
#endif //P_FAMILY_TING_LU
#if P_FAMILY_CHI_YU
    CRY_CHI_YU,
#endif //P_FAMILY_CHI_YU
#if P_FAMILY_ROARING_MOON
    CRY_ROARING_MOON,
#endif //P_FAMILY_ROARING_MOON
#if P_FAMILY_IRON_VALIANT
    CRY_IRON_VALIANT,
#endif //P_FAMILY_IRON_VALIANT
#if P_FAMILY_KORAIDON
    CRY_KORAIDON,
#endif //P_FAMILY_KORAIDON
#if P_FAMILY_MIRAIDON
    CRY_MIRAIDON,
#endif //P_FAMILY_MIRAIDON
#if P_FAMILY_WALKING_WAKE
    CRY_WALKING_WAKE,
#endif //P_FAMILY_WALKING_WAKE
#if P_FAMILY_IRON_LEAVES
    CRY_IRON_LEAVES,
#endif //P_FAMILY_IRON_LEAVES
#if P_FAMILY_POLTCHAGEIST
    CRY_POLTCHAGEIST,
    CRY_SINISTCHA,
#endif //P_FAMILY_POLTCHAGEIST
#if P_FAMILY_OKIDOGI
    CRY_OKIDOGI,
#endif //P_FAMILY_OKIDOGI
#if P_FAMILY_MUNKIDORI
    CRY_MUNKIDORI,
#endif //P_FAMILY_MUNKIDORI
#if P_FAMILY_FEZANDIPITI
    CRY_FEZANDIPITI,
#endif //P_FAMILY_FEZANDIPITI
#if P_FAMILY_OGERPON
    CRY_OGERPON,
#endif //P_FAMILY_OGERPON
#if P_FAMILY_GOUGING_FIRE
    CRY_GOUGING_FIRE,
#endif //P_FAMILY_GOUGING_FIRE
#if P_FAMILY_RAGING_BOLT
    CRY_RAGING_BOLT,
#endif //P_FAMILY_RAGING_BOLT
#if P_FAMILY_IRON_BOULDER
    CRY_IRON_BOULDER,
#endif //P_FAMILY_IRON_BOULDER
#if P_FAMILY_IRON_CROWN
    CRY_IRON_CROWN,
#endif //P_FAMILY_IRON_CROWN
#if P_FAMILY_TERAPAGOS
    CRY_TERAPAGOS,
#endif //P_FAMILY_TERAPAGOS
#if P_FAMILY_PECHARUNT
    CRY_PECHARUNT,
#endif //P_FAMILY_PECHARUNT
    CRY_COUNT,
};

#endif // GUARD_CONSTANTS_CRIES_H
