gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"

gText_Counselor_Welcome::
	.string "Hey there! I'm your summer camp\p"
	.string "group leader!\p"
	.string "Before we begin, lets go\n"
	.string "over basic safety while you\l"
	.string "are staying here.\p"
	.string "$"

gText_Counselor_Safety::
	.string "While we will try to make\n"
	.string "every activity as safe as\l"
	.string "possible, unexpected events\l"
	.string "can happen.\p"
	.string "The most important rule is to\n"
	.string "stick to your group.\p"
	.string "In the event of an\n"
	.string "emergency, find your group\l"
	.string "mates and make your way to\l"
	.string "the nearest adult.\p"
	.string "If no adult can be\n"
	.string "found, head straight back\l"
	.string "to your cabin where you\l"
	.string "can shelter from the\l"
	.string "elements and have access to\l"
	.string "a phone to call for help.\p"
	.string "$"

gText_Counselor_Identity::
	.string "Now I just need to double\p"
	.string "check who you are.\p"
	.string "$"
	
gText_Counselor_AreYouReady::
	.string "All right, I'm going to head\p"
	.string "confirm with admin, you guys\l"
	.string "unpack and in a bit, we will\l"
	.string "start summer camp in full.\p"
	.string "$"

gText_Counselor_TimeSkip::
	.string "1 HOUR LATER.\n"
	.string "$"

gText_Counselor_Panic::
	.string "Joe: Watch out everyone!\p"
	.string "Its snowing hard, make sure\n"
	.string "to gather at the lodge now\l"
	.string "while we wait for the adults\p"
	.string "$"